### ISSUE TITLE
Legal Committee Meeting on Patents

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#100]
Heya,

The Node.js Foundation Board of Directors has been discussing issues related to patent protection.

The discussion has reached the point where input from the TSC and CTC has become very important. As a result we are holding a special meeting of the legal committee and inviting anyone from the TSC and CTC to join.

The meeting will be Monday May 16th at 2pm PT. Let me know if you would like to be invited and I will add you.

/cc @nodejs/tsc @nodejs/ctc

**Comment by jasnell** [comment]
Please add me to the list. Will this be phone or in person?

**Comment by nebrius** [comment]
I would like to join as well

**Comment by Fishrock123** [comment]
Please also invite me.

~Jeremiah

**Comment by bnoordhuis** [comment]
> The discussion has reached the point where input from the TSC and CTC has become very important.

Can you say more on why that is?

**Comment by Starefossen** [comment]
Yes, more info on this one would probably be appreciated by the community.

**Comment by rvagg** [comment]
marking ctc-agenda so we discuss this briefly tomorrow

**Comment by jasnell** [comment]
@mikeal... please correct me if I am wrong but I have to assume that this is likely a continuation of the corporate and individual CLA discussion. I can go into more detail on this on the CTC call today but I'd much prefer to hold off and see where the legal committee has landed on this before having too much discussion.

**Comment by rvagg** [comment]
Whether the CTC meeting goes ahead this week is hinging on the outcome of this discussion, as per https://github.com/nodejs/node/issues/6692#issuecomment-218455785, that's in your hands @jasnell.

**Comment by mhdawson** [comment]
I'd like to be invited.

**Comment by thefourtheye** [comment]
Parent protection? What's going to be patented?

**Comment by Fishrock123** [comment]
> Patent protection? What's going to be patented?

I'm not sure but I think it has less to do with anything "we" hold rather than what the foundation might hold?

**Comment by jasnell** [comment]
The discussion is primarily about introducing individual and corporate
contributor license agreements in order to provide additional protections
*against* patents. Specifically, the argument is that the current DCO only
covers copyright. In theory, someone could contribute patented intellectual
property to Node that could put the project and users at risk of litigation
because we do not currently require certification of patent license in the
form of a CLA.
On May 11, 2016 7:31 AM, "Sakthipriyan Vairamani" <notifications@github.com>
wrote:

Parent protection? What's going to be patented?

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/nodejs/TSC/issues/100#issuecomment-218477315>

**Comment by mikeal** [comment]
Let's not jump to CLA/CCLA. A healthy part of the discussion in the board meeting was just getting the technical side up to date on what the actual problem is and then working towards a solution. CLA/CCLA is a path towards a solution but this is also about a solid problem statement and getting some of the technical side up to date on that.

**Comment by mikeal** [comment]
> Can you say more on why that is?

Patent grants are something many open source projects deal with when accepting incoming contributions. The concern is simple, a license covers copyright but it doesn't assign or give rights to the project or its users for any patented materials someone may have contributed.

There are several licenses that take care of this (Apache2, the upcoming BSD+Patents) but one of them is not the MIT license which is what we use. This lack of protection is a concern and there are a few different ways we can try to solve it. All of them would require work and buyin from the technical community so we need to loop in members of the TSC/CTC who would like to take this on and work towards a solution.

**Comment by jasnell** [comment]
@mikeal +1 ... that's largely why I want to hear from the legal committee before getting too far into the discussion. I'd like to hear more about their current thinking of the problem.

Expanding on this a bit more for discussion.

One of the concerning scenarios that is bringing this up is this:

When an individual contributor brings code into Node.js, there is a potential that whatever that code does, the intellectual property may be owned by that individuals employer and the individual developer may *not* have sufficient rights to grant a patent license to the Node.js Foundation for use of that IP. This puts the Foundation (and Node.js users) at risk of litigation if someone decides to come along and assert those IP rights later. For instance, Developer Terry optimizes a part of Node.js using a new performance optimization algorithm patented by their employer. Terry may or may not have known that the algorithm was patented by her employer, and the employer may or may not have known that Terry used it in a contribution to Node.js. Later, Terry's employer sells those patents to a third party whose sole business is to go around suing people who use the patents they own. Because the DCO currently only covers *copyright*, there's no clearly defined license for Node.js to be using the algorithm in question.

Now, if that algorithm can easily be removed or replaced in Node.js if it ever comes into question, then we really have no problem because if the issue ever did come up we could simply swap it out. However, if the algorithm was used extensively or considered to be central to a core feature of Node, then we could be facing a significant challenge.

As @mikeal indicates, there are several possible approaches for dealing with the issue. IBM (my employer) has floated the idea of using a CLA/CCLA as is done with other major open source projects but that is just one possible path. What we need to do at this point is discuss what other possible approaches there may be to addressing this issue. Updating the OSS license we use to include an explicit patent license grant is another possible approach.

A key risk is that we end up with a solution that causes too much friction when accepting new contributions so we need to make sure we are being deliberate here and carefully weighing the options.

**Comment by mcollina** [comment]
It is not just node, but also all of its dependencies, and other Node.js Foundations projects as well, e.g. readable-stream, express, and all their dependencies.

**Comment by williamkapke** [comment]
The meeting date in the OP has past & I assume it took place.

@mikeal Please consider updating this thread with any relevant information you can and closing it.

**Comment by bnoordhuis** [comment]
What was the conclusion?

(Was there a conclusion?)

**Comment by jasnell** [comment]
Nothing concrete beyond the fact that we need to do *something*. 

Fundamentally, the options are: (a) We stick with the MIT license and existing DCO and do nothing further, (b) We switch wholesale to an OS license that includes patent protection (e.g. Apache), (c) We accept all new contributions past a specific point in time under a new OS license that includes patent protection while continuing to use MIT for prior contributions, (d) We augment the DCO with Individual and/or Corporate CLAs, (e) We do some combination of these.

Given how excruciatingly long it takes for us to get input from the Foundation legal committee, the @nodejs/tsc and @nodejs/ctc are likely going to have to simply pick a path.

**Comment by bnoordhuis** [comment]
(a) and (c) seem like the most practical ones.  (b) would need formal approval from everyone who has code in the tree and I don't think anyone wants to go back to (d).

**Comment by ChALkeR** [comment]
What would (c) look like? Will it just state «all contritions from {date} are double licensed under MIT and Apache Licenses» somewhere in the LICENSE file? Or would every contributor need to explicitly accept that (In a way similar to CLA)?

The approval for (b) could be made optional. The chances that everyone (there are about 1000 contributors mentioned in the [AUTHORS](https://github.com/nodejs/node/blob/master/AUTHORS) file) would approve that is near zero (I'm pretty sure that at least someone is even not reachable), but partial approval by itself could lower the riscs here, can't it?

**Comment by jasnell** [comment]
Option (c) would be: All contributions from {date} are {new license}, All
contributions before {date} are MIT.

The complicating factor for (c) is: Because new contributions can alter old
contributions, to know which license is in use for any given line of code,
the git history would need to be consulted.
