### ISSUE TITLE
Issues with freenode irc

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#1031]
I don't know how active the node.js freenode irc has been these days (if at all) but given the issues that are happening there, we may want to distance ourselves from it.

Refs: https://gist.github.com/joepie91/df80d8d36cd9d1bde46ba018af497409
Refs: https://nodejs.org/en/get-involved/

![image](https://user-images.githubusercontent.com/439929/118829643-236c9300-b873-11eb-9544-287fdb3345b0.png)

**Comment by targos** [comment]
I personally stopped using IRC a few months ago because I was unable to sign in to irccloud. Now I reluctantly use the openjs slack.

**Comment by devsnek** [comment]
dunno about #node.js but I think something we could do proactively is wipe out mentions of #node-dev

**Comment by targos** [comment]
https://github.com/tc39/Reflector/issues/374 is probably a private repo (I don't have access)

**Comment by jasnell** [comment]
> tc39/Reflector/issues/374 is probably a private repo (I don't have access)

Ah right yeah... good point.

**Comment by ljharb** [comment]
The node channels are safely owned on libera, so moving there would be pretty straightforward.

We'll need to "register the project" with libera staff, but we'll be fine in the meantime.

**Comment by mhdawson** [comment]
I've not using IRC much recently either.  If there is still active use, I agree we might want to move.

**Comment by mcollina** [comment]
This was recently published: https://freenode.net/news/freenode-is-foss.

**Comment by ljharb** [comment]
A number of projects - Ubuntu, zsh, couchdb, etc - have officially moved to libera, fwiw
 - http://zsh.sourceforge.net/Arc/irc.html
 - https://lists.ubuntu.com/archives/ubuntu-irc/2021-May/001923.html
 - https://twitter.com/couchdb/status/1395389989345800201?s=21

**Comment by MylesBorins** [comment]
TBH I think that if we are planning to move off freenode we should just switch off IRC as a default chat. The primary benefit, imho, to freenode was the center of gravity. If we are going to move that I think it is worth revisiting IRC as a platform altogether.

**Comment by ljharb** [comment]
Do you mean for the community, or for the project team? I think those are two very different sets of considerations.

**Comment by MylesBorins** [comment]
@ljharb I'm talking about for the project team. If we want to "officially migrate" the #nodejs I think that would be more the responsibility of the ops in that channel and perhaps the @nodejs/community-committee ... as we are in the TSC repo I was focusing on project co-ordination

**Comment by bnb** [comment]
Happy to help enable the project and the community to move to whatever platform. I'd +1 @MylesBorins's assertion that if we're going to move, it should probably be off of IRC as a whole... especially since a lot of those in leadership who I thought _were_ active seem to have stopped being active on IRC.

I'd also like to be upfront that I'm kinda cautious about this, as we've had discussions around this for years and it's directly burnt people out and caused them to leave the project. Years ago I had to give up being opinionated as a form of self-care in this specific discourse. Given that, I'm happy to help support whatever the project decides to go with and provide any context that would be helpful (like how the [Electron Discord](discord.gg/electron) is going / lessons learned).

**Comment by Trott** [comment]
Here is a screen-capture of the only two messages (off-topic) in the #node-dev channel on Freenode in the last week:

![image](https://user-images.githubusercontent.com/718899/119429900-a2732880-bcc4-11eb-903f-a46303d9586d.png)

I think we probably should remove mention of #node-dev from the repo and put some kind of auto-message in the room telling people it's not monitored anymore. That will also mean change in the moderation repo, I think, since IRC mods are included in there somewhere in the docs.

**Comment by ljharb** [comment]
@Trott to be fair, i'm still monitoring it, but in that case i was hesitant to point the person at the `#node.js` freenode channel if there's going to be a decision to officially migrate it to libera (where it exists, and is monitored, by the same people)

**Comment by Trott** [comment]
I guess my point wasn't so much that the person didn't get an answer but that nobody has had anything on-topic to say in over a week.

I'm OK with keeping it if we have active projects folks using it. I definitely don't log in to IRC nearly as much as I used to.

**Comment by bnb** [comment]
Also worth noting that freenode has updated their policy to effectively hijack official channels if they point to a different place and have removed their ban on racial, ethnic, religious, and gender-based hate. 

Based on this I strongly believe that freenode as it exists now does not uphold the stated values of the Node.js project and we should migrate off of it entirely.

https://github.com/freenode/web-7.0/commit/1194a3e71a427a669ccdddee22006416d46eeb43

**Comment by mcollina** [comment]
I concur with @bnb.

**Comment by ljharb** [comment]
I'd be happy to close and forward all the project channels to the community channel; the problem now is that any channel that's actually closed, and advertises that it's moved elsewhere, will be taken over by freenode staff - which would make things much worse (the taken-over channel could become toxic and unsafe for node users, and we'd have no way of making them aware of that).

The way I'd prefer to proceed is change the website to point to libera for the community channel, and wherever the project decides for the project channels (libera, slack, or otherwise), forward the project channels to the community channel, and then quietly, over time, migrate the community channel to libera, where it already exists and is staffed and moderated under the node project's code of conduct by the same people.

**Comment by bnb** [comment]
For what it’s worth, they “accidentally” banned everyone who was logged in with IRCCloud. They’ve asserted they’ve undone that, though I’ve seen people saying they’re still banned (and I myself can’t figure out how to reconnect - I get “Disconnected - Killed: (Facility Blocked)”).

**Comment by devsnek** [comment]
Banning IRCCloud was not an accident and they are not going to revert it.

**Comment by bl-ue** [comment]
>https://github.com/tc39/Reflector/issues/374 is probably a private repo (I don't have access)

Sorry that this off-topic, but why is it private?

**Comment by devsnek** [comment]
@bl-ue the reflector is where tc39 shares private details about meeting locations and governance and whatnot.

**Comment by cspotcode** [comment]
What options are being considered for #node-dev and project channels?  I assume the options are:

- Libera or other IRC
- Slack
- Discord
- no chat; preferring to communicate via github and video calls

Are the relevant tradeoffs for IRC vs Slack/Discord: avoiding proprietary/closed source servers, vs usability?  Are there other relevant factors?

**Comment by ljharb** [comment]
There already exists a node Slack and the OpenJS Foundation slack, and the same main channel on libera.

The only discussion here imo is really, do we have “no irc” or so we change “dead irc” to point to “new irc”.

**Comment by cspotcode** [comment]
For `#node-dev`-type discussions, for example discussing a node pull request, is one of those options better or more preferred than the others?  Echoing earlier comments, I'm happy to use whichever chat system is preferred.  If possible, it would be simpler as a hopeful new contributor to know a single one to use.

**Comment by Trott** [comment]
Speaking only for myself and not the other 20+ members of the TSC...

For general Node.js help/broader community, there's already a #node.js channel on Libera (thanks, @ljharb, I think?). 

But for project coordination...

> * Libera or other IRC

Unlikely we'll move to Libera or other IRC. #node-dev on Freenode was already only lightly used by us. I don't think we're looking for more channels. The active people in Node.js core are already overwhelmed with notifications for the most part.

> * Slack

There is an existing #nodejs-dev channel on the OpenJS Foundation Slack that some of us use/monitor. 

> * Discord

There is no official Discord used for project coordination and I don't sense an appetite for creating one for the same reason that we don't want to move to a new IRC platform.

> * no chat; preferring to communicate via github and video calls

GitHub (including GitHub Discussions and far too many repositories), video calls here and there, the existing Slack sometimes, and email for private business. Oh, and HackerOne for security stuff.

Before the rise of COVID-19, we also had twice-a-year collaborator summits that most of the highly-active collaborators would attend. (It coincided with big conferences that companies would often send folks to, and the Foundation would provide travel funds for those of us who don't work for big tech companies that will pay for us to go to big tech events.) I don't know if that will resume if and when the world gets the disease under control, but they were immensely helpful. As impractical as is may seem (and as wasteful as it may actually be) to fly everyone to a location just to lay the groundwork for future work on the project, it was incredibly useful to have everyone in the same place and focused on Node.js.

> Are the relevant tradeoffs for IRC vs Slack/Discord: avoiding proprietary/closed source servers, vs usability? Are there other relevant factors?

For me, at least, the biggest factor is that there are already too many channels of communication for any person to reasonably be expected to stay on top of (unless, perhaps, you are paid to work on Node.js full time, but most of us are not, and many of us aren't paid to work on it at all).

**Comment by Trott** [comment]
> For `#node-dev`-type discussions, for example discussing a node pull request, is one of those options better or more preferred than the others?

I would say that GitHub is always preferred as a first option for things that aren't private, but for real-time communication, I would say use the OpenJS Foundation #nodejs-dev Slack channel, only because it exists right now and (as far as I can tell) is the most actively-used of the real-time options among folks on the project currently.

**Comment by cspotcode** [comment]
Thanks, sounds good to me.

> For me, at least, the biggest factor is that there are already too many channels of communication for any person to reasonably be expected to stay on top of

My questions are asked in this spirit.  As an outsider wading into the codebase and hoping to send a first pull request, it is always helpful to have clear, up-to-date guidance in the docs.  This thread is helpful in the interim.

**Comment by devsnek** [comment]
fwiw I find github works well enough for node interactions. I'd love to set up a proper real time chat on discord or matrix or anything with proper moderation but as long as openjs is obsessed with slack I doubt that will happen.

**Comment by bnb** [comment]
> Before the rise of COVID-19, we also had twice-a-year collaborator summits that most of the highly-active collaborators would attend. (It coincided with big conferences that companies would often send folks to, and the Foundation would provide travel funds for those of us who don't work for big tech companies that will pay for us to go to big tech events.) I don't know if that will resume if and when the world gets the disease under control, but they were immensely helpful.

Genuinely miss these and have been noticing my own lack of attachment to individuals in the org that I used to feel strengthened after they happened. Genuinely hope we revive them when it's reasonable and safe.

**Comment by Trott** [comment]
Seems like this can be closed at this point, but if I'm wrong, please re-open.
