### ISSUE TITLE
Regular roll-up reporting for active working groups

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#109]
Per the 2016-06-02 Meeting minutes:

> Rod to propose on GitHub that we ask for regular roll-up reporting for active working groups, ask what they are working on and planning on working on.

I've personally been wanting to see this. I seems odd to me to see these comments on the last few month's meetings:

> - we really didn't have an agenda to discuss
> - We only have 'Define "Node.js core"' #84 on our agenda so I think we should skip the formal meeting this week and have a quick catch-up in a private meeting instead.
> - Nothing critical on the agenda.

IMHO, I think updating the community should be considered pretty darn important if not critical. Sure- maybe there are only ~4 of us on the live stream... but the video views on youtube are in the hundreds. 

May I even go so far as to suggest that video views and/or # of subscribers should be a [KPI](https://en.wikipedia.org/wiki/Performance_indicator).

**Comment by rvagg** [comment]
added to tsc-agenda, we'll get this ball rolling

**Comment by rvagg** [comment]
**Proposed plan, based on discussion during meeting @ 2016-06-16 #110 with embellishments by me:**

## What

A blog-post style report that contains a section for each project, working group, team or repository that has meaningful information to share with the broader community. @Fishrock123 is already doing basic reporting on WG activity on the NodeSource blog (e.g. https://nodesource.com/blog/nodejs-wg-weekly-july-25-2016/). The difference is that the proposed reports would come from the groups themselves and may be used to promote things of importance to that group and they would be much less frequent.

The TSC would take responsibility for collating reports but the content must be provided from the groups themselves. A non-reporting group should not hold up the publication of a report as that will quickly lead to this process running out of steam as groups are likely to be unable to report from time to time.

## When

To begin with, the aim is to publish a new report every two months (and we'll never use the term "bi-monthly"!), although we may adjust this as we gain experience and we may even alternate content depending on how much information is flowing through.

## Who

For each reporting period, the TSC will attempt to get a representative from each of the following groups and projects to provide a section of the report. Additional groups that would like to be published (e.g. less active groups, informal groupings, ad-hoc groups, language groups, etc.) should also have the ability to be included and it should be made clear that this facility is available.

Groups:

* TSC
* CTC
* LTS
* Diagnostics
* Inclusivity
* Build
* Benchmarking
* Website
* Testing
* Documentation

Projects:

* citgm
* node-gyp
* nan
* libuv
* nodejs-github-bot

## Content

Content suggestions for the groups providing report sections:

* Interesting activity that promotes the kind of work the group is doing
* Requests for input from the user community and details on how to provide that input
* Upcoming meetings that are open to public participation
* Other activities where public participation is desired
* Details on how to get involved, the kind of work to be done, the kind of time commitment, the kind of impact that can be made on the Node ecosystem
* Promotion / kudos for third parties for resources provided for the activities of the group
* Case studies
* Interesting resources available on the web that are related to the work of the group

Projects may want to report:

* Releases made since last reporting and details of what was included in those releases
* Upcoming or ongoing work
* Roadmaps or other planning information
* Details of how to get involved

**Comment by williamkapke** [comment]
This topic gets a sad face for now 😞 

2017 resolution!? 🎉

**Comment by rvagg** [comment]
Taken off tsc-agenda, I'm going to be honest that this is not at thing I'm going to get to in the next couple of months at least. There is discussion of a regular podcast which would cover a good portion of this stuff so that'll help at least.

**Comment by jasnell** [comment]
The current plan for this that I have in mind is inviting individual working groups to provide quick reports either by joining in the TSC meeting or posting comments in the meeting announcement thread prior to the TSC meeting. I hope to have some details put together in the coming week or so.

**Comment by mhdawson** [comment]
My understanding of current coverage that we have for people in the TSC with  respect to WGs

Website
Streams
Build (coverage -> Rod, Michael)
Diagnostics (coverage -Josh, I'm also ramping up involvement)
i18n (covers translations)
Evangelism  (does this fit with community commitee ?)
Docker
Addon API  (coverage -> Ben).  There is also the question of whether the the api WG that was never fully chartered should be pulled in.  If that was the case we'd have more coverage.
Benchmarking (coverage -> Michael)
Post-mortem (coverage -> Michael
Intl - (main participant is Stephen Loomis)
Documentation (being de-chartered)
Testing (being de-chartered) - do think there is a gap here.
LTS (being chartered, coverage Michael, James)

**Comment by mcollina** [comment]
I don't think it should be up to individuals to report on wg status. How about asking each wg to provide a status update every month, or biweekly if there is needed?
I think it can provide a nice heartbeat of wg activities.

**Comment by mhdawson** [comment]
I'd like us to put together a list of key areas (wgs and others) and then work towards having a review on the progress on each of those in the TSC meetings.  Examples of areas not covered by the wg so far would be:

* testing
* feature requests
* roadmap

and I'm sure with some thought we'll come up with others.

**Comment by mhdawson** [comment]
Issues with some of the areas I've thought of to start: https://github.com/nodejs/TSC/issues/278
