### ISSUE TITLE
Define "Node.js core" - Mark II

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#113]
In the last TSC meeting we discussed how to make progress on defining the scope for "node.js core".  We agreed that a list based approach might work and I took the action to put together the initial list to restart the conversation.  As opposed to trying to define "Node.js core" it attempts to define were the CTC/TSC has autonomy.

May or may not be what the TSC members had in mind but my starting point for discussion.

---

These are the areas that the CTC/TSC has autonomy in making decisions.  Outside of these areas the CTC/TSC will collaborate with the board when making decisions:
- Code/Doc/ changes to any of the repositories under github/nodejs
- Standards and processes covering contributions to repositories under github/nodejs
- Infrastructure and build tools for components built from github/nodejs
- Release types/schedules/frequency/delivery vehicles
- Which external components Node will depend on and how they will be bundled into Node distributions.  (Examples include node-gyp, v8, opensll, etc.).  This does not include bringing a dependent project itself under the foundation umbrella, but does cover including a copy of the code for the dependency in the deps tree or including them in the node distributions (ex npm).
- Creating new repositories under github/nodejs and building new code/components in these repositories that may or may not be shipped as part of Node.  This is different than moving an existing project/community under the foundation umbrella and adding it to github/nodejs.
- Overall technical direction for Node.js.  This includes the top level technical direction as well as decisions on which specific features will be included/excluded and where to encourage contributions within the community as well as all aspects of how the technical direction is managed.

**Comment by mhdawson** [comment]
@nodejs/tsc

**Comment by williamkapke** [comment]
Thanks for the starting point @mhdawson. I'm surprised there hasn't been feedback already. 😕 

Here are my thoughts:

CTC/TSC can't be used interchangeably like this. The TSC oversees everything technical in the Node Foundation (currently) but _most_ of that responsibility is delegated to the CTC. This is an important distinction, for example, in the bullets that refer to repos "under github/nodejs" since that includes Inclusivity, Moderation, TSC ..etc which are not within the CTC's scope.

I *think* I'm correct that the CTC is the result of the approval of the [Core TLP application](https://github.com/nodejs/TSC/blob/master/Applications/Core-TLP.md) that initially defined Core's scope.   So, I am wondering if CTC should choose their own scope and this should be moved to the new CTC repo? After all, they're the ones that would be doing the work. In other words: Is the TSC assigning work or is the CTC volunteering to do work..? Ultimately, it would need to be approved by the TSC either way.

This **MIGHT** be better suited as a PR so the individual points can be commented on. Although, I'm not personally convinced THAT is a great way to collaborate on it either. A temporary repo may be better for collaborating.

I do not think this will be a fast/easy process. IMO, this processes will yield the best progress if it is done in stages:
1) solicit items
2) flush out a baseline scope that only includes the undisputed items.
3) breakout topics that are "grey areas".
3) commit to an initial scope by `X` date. Boards tend to like it when they have deliverable dates.
4) remind everyone that the processes allows for bringing in additional items as they are flushed out.

Now that we have 2 collaborator summits set up this year, I recommend setting something up for this topic. 👍 

cc @nodejs/ctc

**Comment by mhdawson** [comment]
Happy do do PR or whatever else, but would be good to have input from some of the other TSC members as well.

**Comment by eljefedelrodeodeljefe** [comment]
If possible please bear "module core"(see https://github.com/nodejs/node/issues/7098) in mind, or at least don't exclude it, with whatever the discussion in https://github.com/nodejs/TSC/issues/84 and https://github.com/nodejs/TSC/issues/115 yields.

**Comment by mhdawson** [comment]
In last TSC meeting this was reviewed and it was suggested that we should move to a PR to let people comment/refine the wording.  PR here: https://github.com/nodejs/TSC/pull/116
with some of the comments from the meeting incorporated.

**Comment by williamkapke** [comment]
@mhdawson This PR is superseded by https://github.com/nodejs/TSC/pull/144 right?
Consider closing?

**Comment by mhdawson** [comment]
Agreed closing
