### ISSUE TITLE
Update TSC meeting times

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1132]
Reminder issue so that we close on updating after the timezone change.

**Comment by mhdawson** [comment]
All TSC members were asked to update their availability a few weeks ago.

@ChALkeR is going to run the availability script to find the new best times.

**Comment by Trott** [comment]
I got my own script back into shape and the combination of times it determined were the most fair were:

Wednesday UTC 12:00
Wednesday UTC 21:00
Thursday UTC 14:00
Thursday UTC 17:00

Here's what that looks like in our various time zones.

Pacific Time (Los Angeles, 4 TSC members):

4AM Wednesday
1PM Wednesday
6AM Thursday
9AM Thursday

Eastern Time (New York, 6 TSC members):

7AM Wednesday
4PM Wednesday
9AM Thursday
noon Thursday

Greenwich Mean Time (London, 2 TSC members):

noon Wednesday
9PM Wednesday
2PM Thursday
5PM Thursday

Central European Time (Berlin, Rome, Stockholm, Zürich, 5 TSC members):

1PM Wednesday
10PM Wednesday
3PM Thursday
6PM Thursday

Moscow Time (Moscow, 1 TSC member):

3PM Wednesday
midnight Thursday
5PM Thursday
8PM Thursday

India Time (Bangalore, 1 TSC member):

5:30PM Wednesday
2:30AM Thursday
7:30PM Thursday
10:30PM Thursday

China Time (Shanghai, 1 TSC member):

8PM Wednesday
5AM Thursday
10PM Thursday
1AM Friday

**Comment by mhdawson** [comment]
I'd need to find somebody to cover the 7 AM ET slot but +1 from me since it that is what works the best across the TSC members.

**Comment by Trott** [comment]
> I'd need to find somebody to cover the 7 AM ET slot but +1 from me if that is what works the best across the TSC members.
> I'd need to find somebody to cover the 7 AM ET slot but +1 from me if that is what works the best across the TSC members.

That 7AM Eastern Time is the only meeting time that isn't asking someone in China to stay up past 9PM or get up by 5AM, so I think it's pretty essential to the fairness algorithm. It's also the only time that even comes close (but it still misses!) to typical business hours for folks in India. And the only one that is, in fact, during normal business hours in Moscow. You get the idea. 

Fairness is going to pretty much guarantee at least one awful time in the mix for everyone or nearly everyone, so the idea that there needs to be a vice chair or something like that seems pretty compelling. (It wouldn't be me, though, because that time is even worse for me. It would probably need to be one of the TSC members in Europe or Asia, or else someone who is a morning person.)

**Comment by Trott** [comment]
I also wonder if we'd be better off not having any decision-making process around meeting time changes but instead automating it. I'm thinking something like this:

* Automate the process of adjusting people's times based on daylight savings adjustments in their local time zones. This means people will only need to adjust their availability data in the spreadsheet when their availability actually changes or perhaps when they relocate from one time zone to a different time zone.
* Use the meeting time checker to produce the combination of meeting times that are most fair based on its current algorithm which in my script involves creating a floor for how bad meeting combinations can be permitted to be, and then finding the combination of meetings with the smallest standard deviation between availability of participants. The floor is so that the script doesn't decide that the most fair time combinations would be ones where no one is able to attend. (That would be most fair! Just not very practical.) The standard deviation minimization is so that everyone's availability is as similar as possible.
* If people don't like the outcome, they can't vote it down or make alternative suggestions, which is the part of the process that wastes time and is incredibly irritating to me. Instead, they can adjust their availability data (which won't make big changes because they're only one person) or propose changes to the script/algorithm which they would have to justify.
* Schedule the meeting script to run monthly. Significant changes will almost never happen except at daylight savings time. There maybe changes as we onboard/offboard people but they would likely be small adjustments.
* If we have everyone subscribed to a Google Calendar, keeping up to date on meeting times could be low/no effort for most/all TSC members.

**Comment by mcollina** [comment]
I can chair the 12 UTC meeting meeting (minus unplanned travel).

**Comment by mhdawson** [comment]
@Trott I like your suggestion of automating and going with what it suggests unless there are objections/counter suggestions. We most often end up going with what the tool suggests anyway and that would speed the process.

**Comment by mhdawson** [comment]
It's almost a week after @Trott posted the new times, unless we have objections by Friday I'd suggest we update the times starting next week. @nodejs/tsc one more mention/chance to object/raise concerns before we do that.

**Comment by mhdawson** [comment]
I'm going to update for next week based on the next times

**Comment by mhdawson** [comment]
Ok, calendar updated, closing.
