### ISSUE TITLE
TSC Elections - One position or two?

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#128]
@nodejs/tsc: The Foundation bylaws identify two electable positions within the TSC:
- The TSC Chair - conducts the TSC meetings
- The TSC Director - represents the TSC on the Node.js foundation board.

The bylaws allow the TSC to elect the same individual to both positions; which is what we did when we elected @rvagg to the position last year. We need to decide if we want to keep these positions together or separate them in the next election.

**Comment by jasnell** [comment]
My vote would be to separate these to help spread out the workload. Separating out would also reduce the perception of the Chair and Director being a de facto BDFL (which isn't the case but can be the perception).

**Comment by jasnell** [comment]
@rvagg -- the TSC would love your thoughts on this based on your experience over the last year.

**Comment by williamkapke** [comment]
I hope the TSC does what is written in the By-Laws.... or proposes a change to the board to update them to say there is only 1 position. The board has a duty to make sure the governing documents are followed. Sure, _maybe_ this particular issue may not, for example, threaten the 501(c)(6) status... but it just takes a bit of process to guarantee it doesn't. So why not do just it?

**Comment by nebrius** [comment]
I think the idea is to consider if we want to elect the same person to both positions, not merge the positions into a single one, right @jasnell?

**Comment by jasnell** [comment]
Right, sorry I wasn't clear. The Bylaws give the TSC the option of electing the same person to both roles, which we did last year with Rod. We had only a single election. We can choose to do that again this time or split it into separate elections and decide that we want different people in each (which I would recommend)

**Comment by williamkapke** [comment]
Sure, the TSC could vote and decide to have the Director and Chair be the same person. However, it seems this could be equally achieved by just having the TSC do a second vote where people can choose to vote for the same person. This also keeps it flexible for future TSC members IMHO. I guess I don't see what declaring "the position be the same person" really achieves.

Also, the Director position is not necessarily designated annually. It is done...
> At the time of **any** election of Directors where the number of Platinum Directors is two or greater

Election of directors may happen from time-to-time for various reasons defined in the By-Laws.

All that said: If my opinion counted, I'd like it to just stay as @rvagg for both! >:-)

**Comment by rvagg** [comment]
/cc @nodejs/ctc as this impacts them as well.

Really sorry for being slow to this party, a more timely response would have been helpful given the timing of the board anniversary but I've needed some space recently to regroup and consider my position on this, amongst other things!

Having done that, first I have some general thoughts to share on _leadership_ that relate to some of the things raised in #126 and beyond, then I have a proposal to make. So please forgive my philosophising if you're just looking for the meat of what I have to say. Before I do that, however, I want to acknowledge something where I believe I'm at fault: when we initially did TSC chair election we agreed to hold a fresh election after 3 - 4 months, after a stability period for the Foundation. Both Bert and I were very keen to be involved in that startup period due to the likely impact the chair would be able to make in the Foundation. We never set a firm time period and it was never followed up and I believe it should at least have been acknowledged but it wasn't and I won't bother making excuses for that. I'm sorry.

This last year has been both very fulfilling and also a very rough ride, my hair is noticeably greyer than it was 12 months ago! It's been extremely satisfying to be part, along with all of you, of forming this Foundation and setting in process something that has a robustness that ought to outlive any of the individuals involved—this has been one of my primary aims—I want all of us to have certainty that when we move on that we are simply handing our responsibilities over to fresh hands and that the ship will continue to sail and go from strength to strength. We have built something that is bigger than individuals and even bigger than any company, or collection of companies involved; look at the list of companies involved and investing in what we do and consider for a moment how amazing that is. We have companies with both overlapping _and_ conflicting and competitive interests participating together in a forum where we are completely focused on the mutual benefit, we are working on a win/win/win and it's going so much better than my cynical mind imagined when we started this, at a time when the tension between many of the various companies involved was beginning to be toxic. Fast forward a year and it only hit me at NodeSummit this year how far we had come and what a radically different ecosystem we now exist in in terms of commercial involvement and cooperation (actually, [_coopetition_](https://en.wikipedia.org/wiki/Coopetition)).

That said, it's not been easy for me personally. I don't get to code much anymore, I have to carve out occasional time to do that just for my own sanity! I've also found myself being something of a lightning rod for criticism and critique that people have against Node in general; I accept that part of that comes from me as a person but a large portion of it is because people are simply used to finding an individual at the top of an open source food chain and our governance model doesn't fit their expectations of how things work and I get to be the default for them. Most weeks I'm also operating far outside of my comfort zone in so many ways and that's always tiring.

We still have some way to go before I can walk away happy with what we've achieved, here's some things that I think we still need to do better on:

* **Define our organisational structure**: something we've been circling around in our TSC meetings for a few months now without making a whole lot of progress. The pain here comes from the aborted attempts to set up an umbrella organisation for expanding the number of projects we have which left us in a limbo state where the TSC isn't simply a separate meeting of the core leadership team, like the original proposal was for, but a fully separate body ready to administer a collective of projects with the core being just one of those with its own governing body. We've come back to an agreement across the whole Foundation that the technical team here is all about core and even though our definition of "core" might be a bit more expansive than nodejs/node, it still dominates our Venn diagram of interests. So I _really_ want us to sort this out, properly define our structure such that the TSC exists to _support_ Node core and support the CTC and core Collaborators and the projects that exists to make core a complete package. There are lots of awkward questions still to be answered, including: authority is granted in core by contribution, Collaborators and CTC are formed from those showing up to do the work in core, but how is the TSC formed in such a way as to ensure it stays aligned with the CTC but is able to draw from a pool of people more appropriate for the kind of work the TSC does (which will include people who don't necessarily have the time or inclination to contribute code, docs, etc.)? Also, the TSC has a defined position by the Foundation by-laws so technically has power over the CTC, but how do we ensure that the TSC is accountable to the CTC? Or maybe we just need to collapse the two groups back in to one again and simplify things!
* **Broaden our leadership, increase the visibility of our key people and reduce our _lightning rod problem_**: I'm not Mr Node, I have no right to claim that title and people who try and give me that title have no right to do so. It's my facilitation skills that have me doing what I'm doing and it's our amazing team of _doers_ that need to be raised up. @mikeal was trying to sensitively allude to our problems here in #126 and I completely agree with him in that a healthy organisation would have a regular flow of individuals taking leadership positions, both internally—being able to coordinate and facilitate, and externally—being able to speak to the ecosystem/community/public/press about what we do _with authority_. I believe the external perception of what we do is still too concentrated. Plus, we need to reduce our [bus factor](https://en.wikipedia.org/wiki/Bus_factor) even further than we have already!
* **Navigate sensitive relationships with external organisations to the benefit of Node**: we have a few of these in play at the moment, I'm not going to go into too much detail because .. "sensitive" .. but our relationship with TC39 is the obvious one here and even though we've made some progress, it really hasn't got us very far as recent evidence suggests. We've pulled together so much over the past year that goes toward ensuring the long-term health, viability and success of Node but we still have some significant vulnerabilities that we have next to no control over. I'm sure it would be as devastating to you all as it would be to me to have everything we have built come tumbling down because of an external threat that we were unable to protect ourselves against. I'm not suggesting we have things to be afraid of, but that we need to be realistic about the nature of our successes to date and that there is a certain level of fragility to that success; so there's still a lot of work to do!
* **Increase our focus on _users_**: our governance model has gone a looooooong way to achieving this (I cannot overstate how much progress I believe we've made in aligning Node with the interests of its users over the past year), but I personally still have a lot of concerns about the inward focus that comes so naturally to us when navigating difficult topics. If we accept that our core mission is to "Increase the Adoption of Node.js" (which we have done as a TSC, and implicitly as a Foundation), then users are key to that and detached technical naval gazing is an enemy. I don't have any concrete proposals here or even specific critique but it's a topic that needs some focus.

So, given all of that, here's my proposal. **I would like to**:

* stand again as TSC Director
* keep the by-laws definition of TSC Director and TSC Chair tied to the same individual
* revisit the position again in 12 months for either renewal or change
* decrease the level of my involvement in the technical activities of nodejs/node (although this has been happening this year already)
* change the nature of our TSC and CTC meetings such that the _Meeting Chair_, or _Meeting Facilitator_ for each body is a rotating position and not tied directly to TSC Director/Chair although is managed by it

On the last point, during the term of their responsibility, a facilitator for our meetings would be responsible for:

* announcing meetings and pre-publishing agendas for discussion
* facilitating any private / sensitive discussions can take place in an appropriate manner
* deciding time and day and frequency for meetings, given general agreement amongst participants of any material change
* ensuring that minutes are taken (by someone)
* ensuring that minutes are posted to the appropriate location after the meeting has taken place
* ensure that, where possible, recordings are published (somewhere, by someone)
* ensure that, where possible, meetings are broadcast for maximal public participation

To start with, the term length would be two months for individuals taking this responsibility. That I, as the TSC Chair would be responsible for:

* ensuring that someone actually has the responsibility at any point in time, which would mean coming up with a forward-looking schedule that can be filled at least a couple of terms ahead
* ensuring that faciliators have the tools they need, which would mainly include conferencing tooling (e.g. Uberconference, including the ability to take recordings for publishing, likely migrating to a new, more suitable tool, that we'll get the Foundation to pay for).
* encouraging broad participation in this facilitation role, which might mean prodding people who may not consider themselves up to the job
* ensuring that the role is undertaken by individuals who have broad enough respect amongst the group of meeting participants (a facilitator should not be the source of friction!), not that I can think of anyone we have at the moment that would be problematic

Note that I'm suggesting that the TSC and CTC be managed separately here, it will likely be a very different list of candidates for both groups but they will require the same assistance from TSC Chair to make it work. I'm also not ruling out the possibility of having non-TSC and non-CTC members take on a meeting facilitation role, in fact I think it would be quite healthy to have outsiders do some facilitation. @williamkapke and @joshgav come to mind here for TSC (although I'd also be keen to find a logical path for them both to become members of the TSC but that's a different matter) and perhaps @nebrius could assist with CTC facilitation, for example.

So that's my proposal, I'd like to stand for the TSC position on the board and to serve as "TSC Chair" with the understanding that, if elected, I'd like us to make changes to how things are run on a day to day basis. That should take some of the focus off me and raise other individuals up, it should also free up some of my time and mental space to deal with the big topics I outlined above, which I have not been able to give enough attention to to date.

**Comment by jasnell** [comment]
Works for me. +1

**Comment by nebrius** [comment]
+1 from me too.

I like the idea of appointing different people as note-taker and as facilitator of meetings, and having those people rotate over time. Off the cuff, two months sounds like an appropriate amount of time. I'd be willing to facilitate CTC meetings, if people feel that I'm good enough at facilitating (I can never tell tbh).

**Comment by joshgav** [comment]
I think we still need two elections as @williamkapke said, to hew to our bylaws. So the conclusion here should actually be that there are two positions and @rvagg is nominating himself for both. Right?

NB: I'm here to help in whatever ways I can :)
