### ISSUE TITLE
TSC Elections - Nominations

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#129]
@nodejs/tsc - Given that it is time for the TSC Elections, we need nominations. @nodejs/tsc members: please post a comment here if you're putting your name into the hat for consideration. Keeping in mind that we need to decide still if we're wanting to keep the TSC Director and Chair positions together or separate (https://github.com/nodejs/TSC/issues/128), please indicate whether you are interested in consideration for _either_ or _both_ of the positions.

We do have the option of allowing @rvagg to continue in both positions for the next year if he is so willing. @rvagg: if you would, please indicate your preference here.

The voting process for the election will be documented separately.

_Note_: This issue is for nominations only. This thread is not intended to discuss or debate the nominations or to discuss/debate the process or any other related issues. All comments other than nominations will be deleted.

**Comment by jasnell** [comment]
Assuming *if-and-only-if* @rvagg does not wish to continue in the position for the next year, I would like to put myself forward for consideration as the next TSC Board Director. I have been close to the Foundation effort from the beginning and have a deep understanding of the processes and requirements for the role.

I very much believe that the roles of the TSC Director and TSC Chair should be separated out from one another; and feel that the project as a whole would benefit significantly by doing so. Therefore, I would prefer that the Chair position go to someone else (I have a couple folks in mind that I feel would be perfect but I'm going to wait to see if they self-nominate ;-) ...)

Of course, however, I must say that I am completely happy with @rvagg's representation and leadership of the TSC and, if he decides that he would like to continue within the role, then he certainly would have my full support.

**Comment by rvagg** [comment]
See length comment @ https://github.com/nodejs/TSC/issues/128#issuecomment-242079136, summarised as:

> I'd like to stand for the TSC position on the board and to serve as "TSC Chair" with the understanding that, if elected, I'd like us to make changes to how things are run on a day to day basis.

Those changes are outlined in the linked comment.

**Comment by rvagg** [comment]
So here's my suggestion for moving forward with this, speak up if you have an alternative.

* I'll represent the TSC at this week's board meeting (today) as my final meeting during the current term of position of TSC Director
* I'm standing again as per https://github.com/nodejs/TSC/issues/128#issuecomment-242079136 and so far don't believe there has been anyone else that wants to stand for an election as well, please speak up *now* if you want to. This is the thread where you should note that you are standing.
* We'll hold a formal vote for the next TSC meeting - here on GitHub and during the meeting so we can get a quorum. This issue is tagged as tsc-agenda so we'll use it for voting. I'll drop a note in here in a few days to give enough time for additional nominations and then we can proceed.

**Comment by rvagg** [comment]
@nodejs/tsc this is up for voting at this week's meeting. I'm the only one standing for the positions of both TSC Director and TSC Chair (with "chair" taking the form of rotating meeting chair facilitator as outlined [here](https://github.com/nodejs/TSC/issues/128#issuecomment-242079136) if I am accepted). Without additional candidates, I either need to be ratified or rejected for the position. If you are on the @nodejs/tsc then please either drop two votes for both positions or do so during the meeting, otherwise silence will be taken as an abstention but we may come chasing you down if we can't get at least 1/2 the existing TSC.
