### ISSUE TITLE
Opportunity: Grace Hopper Open Source Day (virtual) Sept 22, 2023

### ISSUE THREAD

**Issue by PaulaPaul** [nodejs/TSC#1372]
AnitaB's [Grace Hopper Celebration](https://ghc.anitab.org/) (GHC) is the world's largest conference for women and non-binary  technologists, with more than 30K attendees at the hybrid virtual / in-person conference. Open Source Day (OSD) has been a tradition at the conference for over a decade.

GHC’s annual Open Source Day will be held again this year on September 22, 2023.  It is a pure virtual event for open source contributors to collaborate and share knowledge. GHC is seeking OSD CFP submissions for projects that offer attendees the chance to get hands-on experience with real-world software development lifecycles such as designing, coding, and testing. OSD projects must include a team of at least one woman or non-binary core maintainer. 

**The [GHC CFP process](https://ghc.anitab.org/become-a-speaker/submit-session-proposal/) ends on April 26th, 2023.**

Node.js was one of the most popular projects featured at last year's Grace Hopper Celebration Open Source Day (OSD), and we are hoping the Node.js team will make it a yearly tradition. Information about the opportunity to participate again this year, by submitting to the CFP, is below.

* Node.js Open Source Project Proposal

By raising this issue I'm seeking support from the TSC members in submitting nodejs as an OSD project again this year, and am happy to coordinate the CFP response if there is interest.

If Node.js is submitted as an OSD project, we will want to include up to 3 contributing mentors committed to technical-focused, good first issues. Maintainer/mentor teams will introduce the project, answer questions, and support attendee contributions. OSD projects will gain visibility and same-day contributions, as well as help grow the pool of future contributors. Maintainer/mentor teams will introduce the project, answer questions, and support attendees in making contributions.

* Open Source Day Workshop proposal: 'Your First Node.js Contribution'

In addition, NearForm expects to submit an [Open Source Day Workshop](https://app.sessionboard.com/submit/grace-hopper-celebration-2023/d7692142-015a-42b4-b806-c769c50340e9) proposal on the topic of 'Your First Node.js Contribution', updated with new 'good first issues' based on Security WG efforts.  Please reach out to @RafaelGSS if you are interested in collaborating on this workshop.

OSD Workshops  are for learning new skills, co-creating resources, or solving problems. Workshops are 60-minute, virtual sessions with up to 4 speakers. Workshop proposals can be geared to any/all skill levels and backgrounds about technologies, projects, processes, community, and more to help attendees level up their Open Source contribution skills.

**Comment by Trott** [comment]
Adding the TSC agenda label because I think the TSC should confirm that we want to do this and who will be taking the lead on things like "identifying 30 or 50 good tasks for folks".

**Comment by mcollina** [comment]
+1 to do this! I can possibly come up with a few tasks in Undici, we have a gazillion amount of issues. I'm not sure if I would be able to mentor, because I will be traveling.

**Comment by RafaelGSS** [comment]
As discussed in the last TSC meeting, we're seeking a few volunteers for this initiative. If you want to participate, feel free to reach out to me (or send a message in this thread). Current list:

* @RafaelGSS
*
*

ping @nodejs/collaborators

**Comment by bmuenzenmeyer** [comment]
I'd be happy to participate again as a mentor. A lot of the effort was helping with project setup, debugging, etc. which is a great way to give back. As an aside, last year I volunteered through my employer, but am now a Node.js triager. Either way, I am game!

**Comment by Qard** [comment]
Happy to help if I'm available then. :)

**Comment by Trott** [comment]
I want to emphasize that getting people to volunteer to mentors is the easy part. **What we really need to make sure we do ahead of time is have at least one person responsible for curating 30 (or preferably 50) tasks for people to do.** If I were to be doing this again, I'd probably end up going through our test coverage and trying to identify lines that can be reasonably covered with tests that only use public APIs (no `--expose-internals` or anything like that--that's a test anti-pattern that should only be used when absolutely necessary) and without having to do too much in the way of weird shenanigans. Most of those kinds of tasks have been picked over already, but a diligent search in the code coverage reports, especially in any large blobs of code that have been added relatively recently, will probably turn up enough tasks. I'd budget 6 hours of time for finding these, possibly more. It sounds like a lot, and maybe it is, but I always find that it takes way more time than you think it will.

It's also important that these tasks be kept out of public view, lest some "helpful" person come a long and do 10 of them. I don't even like to share them with other mentors ahead of time because then duplicate tasks get handed out. You can try something like a spreadsheet that only mentors have access to where they mark off tasks that they've given out. But you really have to know that all the mentors will actually mark the tasks and not hand them out without marking them. Last year, I think I had the list of tasks and didn't share it. There is always a 5 or 10 minute period where a lot of people want tasks in rapid succession and you fall behind and it's stressful. But it works out. What worked best in the past was having tasks on physical slips of paper that you handed to the mentor/mentee. Then the task just went to one person automatically.  But I don't know of an easy way to emulate that in a Zoom setting.

**Comment by mhdawson** [comment]
@RafaelGSS I think @Trott is wanting to make sure that by voluntering in https://github.com/nodejs/TSC/issues/1372#issuecomment-1514919510 you will cover finding the required tasks. I think you were volunteering to do the submission, but the question was if you were comfortable with finding all the tasks if nobody else (which is the current state as I understand it) has volunteered to help find tasks.

**Comment by Trott** [comment]
> @RafaelGSS I think @Trott is wanting to make sure that by voluntering in [#1372 (comment)](https://github.com/nodejs/TSC/issues/1372#issuecomment-1514919510) you will cover finding the required tasks. I think you were volunteering to do the submission, but the question was if you were comfortable with finding all the tasks if nobody else (which is the current state as I understand it) has volunteered to help find tasks.

Oh, I wasn't asking about Rafael in particular, but sure, that's fine to ask. I just wanted to make sure that we didn't skip the task-collation step.

**Comment by PaulaPaul** [comment]
@RafaelGSS I think we can also leverage the comment from @mcollina and our own internal Hub for support on this-
Since the CFP deadline is tomorrow by end of day, would you like to collaborate on the submission sometime today or early tomorrow?
Also thank you to all who've collaborated/commented on this issue!

**Comment by danielleadams** [comment]
Thanks all for getting this effort started. Were we able to submit the project?

**Comment by RafaelGSS** [comment]
Yes! Hope to get an answer soon.

**Comment by RafaelGSS** [comment]
Curated issue list for GH Day:

*

Feel free to update this issue with good-first-issues.

**Comment by mcollina** [comment]
@RafaelGSS I think it might be better to have a quick sync on this a week or two prior to the event because any gfi that is added now will likely be closed by then.

**Comment by Trott** [comment]
> @RafaelGSS I think it might be better to have a quick sync on this a week or two prior to the event because any gfi that is added now will likely be closed by then.

Or...keep the list private and curate away!

**Comment by RafaelGSS** [comment]
> Or...keep the list private and curate away!

How was it done last year?

**Comment by Trott** [comment]
> > Or...keep the list private and curate away!
> 
> How was it done last year?

I curated a list in a document that I believe I shared with two of the other mentors, but that was it.

**Comment by mhdawson** [comment]
I think this is long since passed so closing.

**Comment by jellyfishcake** [comment]
Hi, 
I am working on a GHC Open Source Day project proposal for my project. We have a similar issue as you, where a curated list of 'good first bugs' might be gone between now and GHC day. I am curious what you put in the GHC proposal form for 'Issues Link: All issues must be triaged, not focused on documentation, and labeled as “good first issue."' if you want to keep the list hidden.
Thank you!
