### ISSUE TITLE
Moderation Team annual certification

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1390]
TSC folks: React with 👍 to support this proposal, 👎 to oppose it, and 👀  to abstain/express neutrality. Thanks!

I propose that the following members be certified for Moderation Team this year:

* @aduh95
* @benjamingr 
* @ovflowd 
* @othiym23 
* @ryanmurakami 
* @Trott 
* @JohnTitor 

@nodejs/tsc @nodejs/moderation 

Certification does not require a vote unless someone on TSC opposes this action. I propose leaving this open until the next TSC meeting and, if no one opposes it, deem it passed via consensus assuming sufficient TSC members provide 👍 (and 👀  ) reactions such that it would pass if it were a vote.

**Comment by benjamingr** [comment]
Might be a good time to solicit (I know I keep doing it but it's worth a try) other TSC members who think they are a good fit for moderation to self-nominate. We are still the smallest we've ever been (since 2 members left and one joined) which means there are less views taken into account and less cultures/perspectives.

**Comment by mcollina** [comment]
Thank you for all the hard work!
