### ISSUE TITLE
Let's detail the process for how funds are distributed for travel

### ISSUE THREAD

**Issue by nebrius** [nodejs/TSC#145]
According to my best understanding, there are three sources of funding available for TSC members
- Community fund, as managed by @feross
- General Foundation funds
- Community Travel Fund (colloquially referred to as the TSC fund)

The process for requesting funds from one of the sources, and which fund should be tapped, is not currently documented clearly. We should create a document that instructs people how to apply for funds and which fund they should apply for.

This issue was motivated by https://github.com/nodejs/TSC/issues/141.

**Comment by feross** [comment]
Community fund is not up and running yet. We still have a bit of work to do to get Node board approval. Hoping to have that all in place by end of year.

**Comment by yoshuawuyts** [comment]
How much funds are available anyhow? We know it should be somewhere upwards of 2 million per year (e.g. gold / silver / bronze sponsor levels, etc.) but numbers don't seem to be publicly available. Perhaps mild side track, but if this is a public chat about money, it'd be cool to know how much there is :tada:

**Comment by feross** [comment]
@yoshuawuyts Yeah, your guess is roughly right. The foundation should really publish this information. cc @mikael

**Comment by mikeal** [comment]
Answers!

> Community fund, as managed by @feross

This is not setup, we still need the final doc worked out and a board resolution passed along with a budget allocation from the general fund.

> Community Travel Fund (colloquially referred to as the TSC fund)

$45K are in this fund, none of it has been touched, and it expires at the end of the year. The TSC can pass resolutions to spend this at its own discretion and any approved travel expenses can be sent to ap@linuxfoundation.org for re-imbursement (CC me as well).

> General Foundation funds

This one is a bit tricky. The foundation was formed mid-year which meant that we had a July - July budget for the first year. We now have a 6 month budget in place that brings us through the end of this year.

Because both of our large events fall in that 6 month period we are over-allocated in the 6 month cycle (as in we will be spending more than we get in revenue). We have enough surplus from the previous cycle to cover it but it's not a great time to do *new* allocations.

In order to get new funds out of the general fund (in 2016 or 2017) it requires a board resolution. Rod, as the TSC chair, can bring a resolution to the board at any time, and I'm on the hook to help him draft it if he needs it.

**Comment by TheAlphaNerd** [comment]
can we use the travel fund to bring ctc members to interactive us? should I
open a separate issue for this?

**Comment by Fishrock123** [comment]
> $45K are in this fund, none of it has been touched, and it expires at the end of the year. The TSC can pass resolutions to spend this at its own discretion and any approved travel expenses can be sent to ap@linuxfoundation.org for re-imbursement (CC me as well).

Please remind me why I couldn't be flown out to the collaborator summit at Node.js Interactive EU. 😐 

... let's fly some of our non-NA folks into Interactive US for the collab summit down there? That way we get a bit of cross-continental community discussion that otherwise is unlikely imo.

**Comment by cjihrig** [comment]
> non-NA

non North American?

**Comment by mikeal** [comment]
The TSC can use the community travel fund at its own discretion. Log an issue for a resolution, pass it, and send an expense report to ap@linuxfoundation.org.

The reason the funds haven't been spent is because the TSC hasn't spent them, period. I can't give out those funds, they are allocated to the TSC to spend.

**Comment by mikeal** [comment]
BTW, expense reports sent to ap@linuxfoundation.org can use this template https://drive.google.com/previewtemplate?id=0Ak7JTr_5ZgQBdHVEOG5rX0FYdTNzak5IQnh6cnp0dXc&mode=public&ddrp=1#

**Comment by TheAlphaNerd** [comment]
I've opened an issue to request travel funds for interactive US

https://github.com/nodejs/TSC/issues/147

**Comment by Fishrock123** [comment]
@cjihrig that is what I intended yes, it is likely much harder for those folks to attend than it is for people in the states.

**Comment by williamkapke** [comment]
The "restrictions" set forth in the https://github.com/nodejs/TSC/blob/master/Member-Travel-Fund.md that was approved by the board is not being adhered to.

Board Minutes approving this here:
https://nodejs.org/static/documents/minutes/nodejs-foundation-board-meeting-2015-11-02.pdf
> RESOLVED: That the board hereby establishes a fund for Individual Member travel under the following conditions. That the fund be managed by the TSC and each member granted a stipend be approved by the TSC under a formally documented process based on EXHIBIT C. That the TSC may make improvements to this process documented at https://github.com/nodejs/TSC/blob/master/Member-Travel-Fund.md That the fund not exceed the $75K budget allocated for “Event and Tradeshow Participation.


Also note that they approved $75k and not $45k according to those minutes.

... can we get this updated?

**Comment by nebrius** [comment]
That is interesting. Is it true we can only approve funds for people to travel somewhere to _give a presentation_?
