### ISSUE TITLE
Code & Learn NI NA lead teacher travel fund request: Rich Trott

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/TSC#149]
**Travel fund request for Rich Trott**  

**Event:** Node Interactive NA
**Location:** Austin, TX, United States

**Code & Learn**--Rich will lead and organize event for welcoming folks to contribute to Node.js by walking through setup, supporting session time with mentors, and providing tasks that are beginner-friendly

**Stipend request size:** $1500
Stipend would cover flight and lodging for the duration of NI NA, which includes the Code & Learn.

I have opened this as part of discussions that occurred after the NI EU Code & Learn where it was realized that this is a really awesome effort that needs solid support and more preparation. I will be assisting with organizing(@hackygolucky) but I believe that by having both @Trott and @addaleax leading this event, we are setting it up for success.

**Comment by nebrius** [comment]
I'm in favor of this request.

**Comment by jasnell** [comment]
+1 from me as well.

**Comment by rvagg** [comment]
+1 but is $1.5k going to be required for someone in the US? I assume we'd just be setting the max here and it may not be required but I wouldn't mind understanding what the costs might look like for someone who is in the country.

**Comment by jasnell** [comment]
$1.5k seems reasonable for flights + hotel for travel within the U.S. (unfortunately).

**Comment by Trott** [comment]
My total travel costs will be approximately $1800.

My initial airfare for Node Interactive was $546 but I have to pay $200 to change the flight so I can stay for the last two days when Code & Learn and the Collaborators Summit are happening. (I initially booked my flight before those were announced.)

The hotel rate according to the conference website is $229 a night. I will arrive Monday and depart Friday, so that's four nights for a total of $916. There will be slightly more than 15% taxes and fees on top of that for a total exceeding $1053.

So my travel costs will be approximately $1800.

If the TSC decides that it really ought to only cover the difference between my original plans and the cost of having me stay for Code & Learn and the Collaborators Summit, then the total is approximately $527 for the hotel (2 additional nights I did not initially plan on) and $200 for the flight change for a total of approximately $727.

**Comment by jasnell** [comment]
I'm +1 for covering the full amount.

**Comment by mikeal** [comment]
Just a quick point of process:

* The board didn't pass this with a cap, so the TSC can exceed $1,500.
* The board *did* stipulate that the TSC would own and follow it's own process.
* The current process has a cap of $1,500, so someone should alter that before approving an expense that exceeds that amount.

**Comment by Trott** [comment]
Hi! Was there resolution on this in the last meeting? Or is this still an open issue?

**Comment by addaleax** [comment]
The resolution here was that this was passed with a cap of $2,000 for you and $3,000 for me, iirc.

**Comment by rvagg** [comment]
approved
