### ISSUE TITLE
Redesign the Vote bot with GitHub Actions

### ISSUE THREAD

**Issue by RedYetiDev** [nodejs/TSC#1564]
To preface this, **I am not a TSC member**, but I was looking through some past votes, and it seems very difficult to understand how the votes worked, both from me (a spectator) and a voters point-of-view.

I suggest that the Vote bot be changed to use the workflow_dispatch event, where each voting member will dispatch an event with their vote. This way, no one will see their vote, but it will also be easy to vote via the GitHub UI.

With my experience of privacy and security in GitHub actions, I believe this would be both a private and secure way to vote, if setup correctly.

I'm happy to look into setting this up, but I don't want to "overstep" my role as not a TSC member.

---

An example vote would be initialized via the dispatch of a vote start trigger, causing a PR to initiate a vote.

Each member would dispatch a vote trigger casting their vote.

Once ready to end, certain members would trigger a vote end event, and once ended, the votes will be cast.

**Comment by gireeshpunathil** [comment]
I am not familiar with the workflow dispatch event, but if it improves privacy, security and usability then I am in favour of that. is there a demo or something that we can watch to see how it works?

**Comment by RedYetiDev** [comment]
The `workflow_dispatch` event is a Github Actions event that allows for a member of the repository to manually trigger a workflow. Documentation on it is <https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch>, but essentially, each member would vote using a custom dispatch, such as the following example from the docs:
![](https://docs.github.com/assets/cb-78157/mw-1440/images/help/actions/workflow-dispatch-inputs.webp)

Docs on how to trigger the workflow can be found here: <https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow?tool=webui>

---

Keep in mind someone would still have to implement the action itself, I just find it easier to understand from an outsider perspective (when looking at past votes)

**Comment by RedYetiDev** [comment]
The only thing I don't quite understand is how the secret holders get their key parts? Does the vote creator know the decryption keys?

**Comment by RedYetiDev** [comment]
Thanks for the info!

My idea would be:

To open a vote, the vote opener would dispatch a vote_open workflow with the input PR number, and the bot would initiate a vote.

To vote in a vote, the voter would submit their vote (unencrypted) into a vote workflow dispatch, which would then encrypt and commit the vote. This method wouldn't have less privacy/security, as the votes would never be seen in plaintext, as the logs would mask them via `::add-mask`.

To end a vote, the vote opener would dispatch a vote_end event, and the votes would be decrypted and tallied.

**Comment by aduh95** [comment]
> To open a vote, the vote opener would dispatch a vote_open workflow with the input PR number, and the bot would initiate a vote.

That seems to be a worse UX that what we have already.

> To ~vote in a vote~ cast a vote, the voter would submit their vote (unencrypted) into a vote workflow dispatch, which would then encrypt and commit the vote. This method wouldn't have less privacy/security, as the votes would never be seen in plaintext, as the logs would mask them via `::add-mask`.

There's no way you could convince me that going from "the unencrypted ballot never leaves the voter computer" to "the ballot is encrypted in the cloud" is not a net-negative in terms of privacy.
But anyway, I doubt that would improve UX.

> To end a vote, the vote opener would dispatch a vote_end event, and the votes would be decrypted and tallied.

That's already what we have.

**Comment by aduh95** [comment]
That's correct, it's not possible to decrypt the vote ballots without revealing at least 3 secret parts (the number is configurable). If you try to close the vote with fewer secret parts, it will error out as it won't be able to get the private key. Note that that's a feature, not a bug.

**Comment by RedYetiDev** [comment]
Got it, thanks. I took your advice, and I made a demo: <https://github.com/RedYetiDev/nodejs-tsc-vote-demo/issues/4>. Currently, only I am allowed to vote (in the demo).

Voting is done via the following comment triggers:
`/create-vote` - Creates the vote
`/vote` - A user will comment a encrypted vote message
`/end-vote` - The vote creator comments this, and the private key (with a comment `Passphrase: ...`).

It's very crude with the comments right now, but the implementation works.

**Comment by aduh95** [comment]
Regarding `/create-vote` and `/end-vote`: compared to the current process, your proposal has a few downsides and no upsides AFAICT. Note that our `watch-vote.yml` workflow is disabled because it was annoying to have a workflow run each time someone comments anything (I guess that wouldn't matter on a repo dedicated to voting).

Regarding `/vote`: using comments is a bad idea anyway because they are mutable. The only upside I can think of is that it makes it possible for folks without write access to the repo to cast a vote without opening a PR – however that's not really something relevant for the TSC.

I spent a long time thinking about making the vote process smooth; that doesn't mean it's the best it can be, but before suggesting changing it, you should first be able to tell me what's wrong with the current one (the fact that you don't understand it is not a reason on itself). Usually, the optimal outcome of "I don't understand this" is a PR to improve docs, not a complete overhaul of the existing process.  I'm afraid in order to criticize something, you'd have to first understand it, otherwise your proposal will inevitably lack some important features. I'm happy to answer any question you have regarding the current process.

**Comment by RedYetiDev** [comment]
I obviously do not want to sound like I'm against the current voting system, as I'm not directly impacted by it (I'm not a voter). It's just that when I was looking through past votes, I noticed that it was difficult for some voters to get their votes in, for example if they used a different commit name, or if they had issues with the script. (In particular `#1540` had some errors).

> Regarding /create-vote and /end-vote: compared to the current process, your proposal has a few downsides and no upsides AFAICT. Note that watching comment was disabled because it was annoying to have a workflow run each time someone comments anything (I guess that wouldn't matter on a repo dedicated to voting).

If you setup a filter at the root job level, it would cause the workflow only to execute when the filter is matched (such as a valid comment command). This way, invalid comments will simply be skipped over.

> Regarding /vote: using comments is a bad idea anyway because they are mutable. The only upside I can think of is that it makes it possible for folks without write access to the repo to cast a vote without opening a PR – however that's not really something relevant for the TSC.

Running only on comment create makes it immutable, so they can't be changed later.

As for the upsides,
I think this provides an easier way to vote, as voters with the public key do not need to perform several steps to vote, they only need to encrypt and comment. That being said, I'm not a voter, so maybe the current process is good and everyone doesn't want to change it. If it aint broke don't fix it?

**Comment by RedYetiDev** [comment]
Also, my "proposal" is really just a theoretical, I don't want to interfere too much with the status quo.

**Comment by aduh95** [comment]
> as voters […] do not need to perform several steps to vote, they only need to encrypt and comment

That's literally several steps 😅 Currently, they only need to encrypt and commit (which is transparent if they use the CLI), so again I'm not really sure it's any better.

> voters with the public key

As its name implies, the public key is public, so everyone has it.

> If you setup a filter at the root job level, it would cause the workflow only to execute when the filter is matched (such as a valid comment command). This way, invalid comments will simply be skipped over.

Yeah it still appears on the PR list everyone makes any comment. Maybe it's not too bad, after all this repo doesn't see that many PRs – but it seems more logical to improve the current workflow that to come up with an entirely new one.



> I noticed that it was difficult for some voters to get their votes in, for example if they used a different commit name, or if they had issues with the script

You probably realise that's hardly a reason to switch: as time goes on, more issues are reported and fixed, and the system improves. Going to a brand new one will likely uncover new issues.

> I obviously do not want to sound like I'm against the current voting system
> maybe the current process is good and everyone doesn't want to change it

The thing is, if you want to propose a new one, you'd have to bring some strong arguments on how the current system is not good enough – the kind of problems that could not be fixed with the current system, and would require a complete overhaul. Or at least, some strong arguments on how the proposed system would be much better, and how it wouldn't be possible to make those improvements in the current system.
I believe there are some improvements you are suggesting that would fit perfectly well in the current system (e.g. maybe we could re-enable the watching of comments so there's no need for a manual workflow dispatch to close the vote).


> I'm not directly impacted by it (I'm not a voter)

Caritat is an open-source tool, it's not just for the TSC or Node.js (we used it with success at work to decide in which city should happen the next company meetup). So you're as qualified as any to criticize it and suggest improvements, and you're certainly welcome to use it.

**Comment by RedYetiDev** [comment]
Got it. My biggest concerns are that:
1) The bot creates the PR, not the issue author, they need to modify files and then trigger the bot
2) multiple votes cannot go at the same time
3) In order to vote, the CLI must be used, which isn't always accessible

--- 

3 can be fixed via the enabling of the workflow.
But 1 and 2 seem like pretty like they are part of the fundamental implementation.

Then again, there are thousand ways to achieve this, Caritat, GitHub actions, slack, etc. 

I think you are correct that it must be decided what to change before changing anything, but I think that discussion might be a good idea. Again, I don't want to fix something if it's not broken, but I'm also happy to help if it can be improved. (If that makes sense?)

---

Maybe other TSC voters have opinions on the pros/cons of the voting system? 

> again, I don't want to overstep into the TSC's job, so if this is something that's not needed, I'm happy to work on something else

**Comment by richardlau** [comment]
> 3. In order to vote, the CLI must be used, which isn't always accessible

This isn't true.

**Comment by aduh95** [comment]
> 1. The bot creates the PR, not the issue author, they need to modify files and then trigger the bot

What is the concern exactly?

> 2\. multiple votes cannot go at the same time

That's not true AFAIK. The current limitation is that there cannot be multiple PRs to open votes (which is certainly fixable), however once a vote is open, you can open another one (and another one, and another one) without waiting for the first one to close out.

> 3\. In order to vote, the CLI must be used, which isn't always accessible

There's a web UI, the CLI is one way to vote, it's not the only one. (and IMO, both "voting with the web UI" and "voting with the CLI" processes offer better UX than the workflow you proposed).

**Comment by RedYetiDev** [comment]
😅 It seems I don’t know how this works. I suppose you are right, thanks for indulging me :-)
