### ISSUE TITLE
unclear membership related terms and processes

### ISSUE THREAD

**Issue by sam-github** [nodejs/TSC#178]
I thought I had a reasonable grasp of the various memberships and criteria, but when I get asked really pointed questions, I start to realize I'm a bit hazy on the details.

Questions I had trouble answering (when pressed about them on irc), that I think should be clearer in the docs:

1. What is a contributor? https://nodejs.org/en/foundation/members/ uses term without definition. Is it "PR accepted"? Or is it "PR accepted or other significant contribution (such as activity in issue tracker)?" Something else? And @gib just pointed me to https://github.com/nodejs/members/issues/1, should that be linked from the foundation/members page?

2. What is a collaborator? https://github.com/nodejs/node/blob/master/README.md#collaborators I believe a collaborator is someone with github write permission on a repo and its associated tools (can push commits, close issues, add labels, etc.), but there is some question if it is necessarily true that all collaborators have github commit permissions, and the docs don't make it clear.

3. What is relationship of collaborator status in one github.com/nodejs/X sub-project to any other? In 1. above, its made clear that membership is free to contibutors in any project, but its not clear whether collaboration is repo-specific, but I think it is. So, for example, I'm not a nodereport collaborator, just a contributor.

4. https://github.com/nodejs/node/blob/master/GOVERNANCE.md#collaborators describes how to become a collaborator, though could use some clarity on "contribution", as for 1. Maybe some examples? It also doesn't say where to raise an issue: nodejs/CTC, nodejs/TSC, nodejs/node, elsewhere?

/cc @williamkapke who seems to know about these things

**Comment by williamkapke** [comment]
It is on my and @jasnell 's todo list to publish something that makes this more clear.

Check out https://github.com/nodejs/TSC/issues/89 ... scroll to my comment at the end for references to the official definitions.

**Comment by williamkapke** [comment]
Also, Contributor/Collaborator/Committer are terms used by the Technical part of the foundation WRT GitHub community participation.

Members/Membership is a legal definition used in the By-Laws to define a class of participation in the foundation. There are Corporate Members (they pay big $$) and then there are Individual Members (pay no $ **IF** a Collaborator).

**Comment by mikeal** [comment]
First of all, THANK YOU! These terms have been getting more and more confused over the last year and I'm grateful someone put together a detailed description of the problem.

Members/membership is an important term as it relates to the Node.js Foundation because it's a 501(c)6 "Member Organization," meaning that it is effectively responsible to its members and its governance is provided by its members.

Within that definition we have three classes of membership:

* Corporate Membership: dues paying member companies.
* Individual Membership: dues paying individuals.
* Associate Membership: non-dues paying non-profits and academic institutions.

Each class has limitations on how much representation they have at the board level (if any at all, associates are not represented directly on the board). For the individual membership we offer a discount of 100% of their dues if they are a contributor to a project under the foundation (we've defined this as any org member of any org under the foundation: nodejs, express, httpjs, pillarjs).

**Comment by jasnell** [comment]
@williamkapke ... thanks for the reminder on that. I'll dedicate some time next week to drafting up a first pass.

**Comment by williamkapke** [comment]
@jasnell let's try to remember to link #89 and #104 so they get closed out in the process.

**Comment by MylesBorins** [comment]
I've added TSC-Agenda to this. I think that we should discuss if this is something we still need to workshop or if this should be closed

**Comment by fhinkel** [comment]
Closing this because a lot has changed since this was opened. Feel free to reopen if needed, or, maybe better, open a separate issue for specific re-wording if needed.
