### ISSUE TITLE
WORKING_GROUPS.md not updated to mention CTC?

### ISSUE THREAD

**Issue by srl295** [nodejs/TSC#18]
https://github.com/nodejs/node/blob/master/WORKING_GROUPS.md does not mention the TSC/CTC (Core TLP). Is it out of date or am I misreading?

**Comment by williamkapke** [comment]
@srl295 Oy! Maybe things have already been cleared up for you...? It was confusing for me too.

Anyhow, I'll do my best to answer even though it has been so long since you posted. 

The TSC is an official Committee of the Board of Directors that oversees all things technical (Top of the Technical food chain!). So- it wouldn't be mentioned in that document.

The CTC is a Top-Level Project of the TSC's (not a Working Group). So, it wouldn't be listed there either.

The WORKING_GROUPS.md in Core (in /nodejs/node) only lists the "Core Working Groups" that fall under Core. (There is 1 Working Group that belongs to the TSC)

Check out: https://github.com/nodejs/TSC/issues/76

I recently did a PR to the website that includes ALL officially chartered Working Groups. See: https://nodejs.org/en/about/working-groups/

**Comment by orangemocha** [comment]
This issue predates https://github.com/nodejs/node/commit/18abb3ccc2e0917e1371ab9afae4852bdeaa298c. So I believe it's fixed. Feel free to reopen if you think otherwise :)
