### ISSUE TITLE
Applicability of the moderation policy to TLPs

### ISSUE THREAD

**Issue by saghul** [nodejs/TSC#22]
I just read through the new moderation policy documents (great work everyone!) and have some comments regarding its applicability for TLPs.

(Context: libuv is about to start the process of becoming one: https://github.com/libuv/libuv/issues/625)

The moderation policy document does mention TLPs in the "Applicability". The part I'd like to highlight here is:

```
Any alternative Moderation Policy used for a given repository must be included in the root directory of the repository using the Moderation-Policy.md filename. If a repository does not contain a Moderation-Policy.md file, then this default policy applies.
```

My reading of this is that if libuv (or any other project, for that matter) would become a TLP then the moderation policy in that document would apply, since we don't have one of our own.

This doesn't sound correct to me since they are different projects, governed independently. Moreover, the rest of the document does not mention TLPs, and the courses of action mentioned cannot even be technically applied, since TLPs are different GitHub organizations.

So, until there is an actual TLP (hopefully libuv becomes the first one!) I suggest the TLP related text is dropped from the "Applicability" section. The text can be extended afterwards to define its relation (or lack thereof) with regards to TLPs.

Thanks!

**Comment by mikeal** [comment]
There's also a practical problem here in that libuv has its own GitHub org and as so it will end up having a different list of moderators.

But, it would be good to find a policy that could apply to all TLPs because it's actually a big pain to write  up one of these for each project :) A moderation policy is something that you just hope you don't need and then once you do need it it's great to have it already written.

**Comment by saghul** [comment]
> But, it would be good to find a policy that could apply to all TLPs because it's actually a big pain to write up one of these for each project :) A moderation policy is something that you just hope you don't need and then once you do need it it's great to have it already written.

I don't disagree :-) However, there is no TLP in existance at the moment, and the single candidate exposes the problem as you outlined above. Hence my proposal for dropping the text from the current document and get back to it after we gather the experience with a first TLP.

**Comment by jasnell** [comment]
The moderation policy would apply by default to anything that's in the Node.js GitHub organization. While libuv exists in it's own GitHub organization with it's own repos, then it would need to choose to either adopt this policy or have it's own variant. As a best practice, whatever policy it chooses should go in as a Moderation-Policy.md file in the repo root.

**Comment by saghul** [comment]
> then it would need to choose to either adopt this policy or have it's own variant.

The [proposed charter](https://github.com/nodejs/TSC/pull/17) text mentions that this TLP gets its own governance, doesn't that imply that adpting any moderation policy (or not even adpting one) it's totally up to the TLP's governance? This is in conflic with the current text in the moderation policy document.

PS: Not trying to be an ass here, just making sure the text meets everyone's expectations.

**Comment by jasnell** [comment]
I'm not sure it is in conflict. Specifically note the text, 

> Individual Working Groups and Top Level Projects chartered by the TSC may adopt an alternative Moderation Policy for any repository under their stewardship

This means that libuv (and any TLP) is free to adopt it's own moderation policy. There are a couple of requirements given (such as making sure there is a `Moderation-Policy.md` file in the repo. If the TLP's moderation policy is that there is no moderation policy, then it would simply need to have a `Moderation-Policy.md` file that explicitly states that fact. e.g. 

```
The XYX Project does not have an established Moderation Policy
```
Or something along those lines. 

If you think improvements can be made to the current language, tho, a PR is more than welcome :-)

**Comment by mikeal** [comment]
> The proposed charter text mentions that this TLP gets its own governance, doesn't that imply that adpting any moderation policy (or not even adpting one) it's totally up to the TLP's governance? This is in conflict with the current text in the moderation policy document.

The may be true in the current text but we need to go through all of our policies and move from a "copy/paste" approach to a "copy on write approach."

When we started it seemed fine to expect working groups and eventually TLPs to just copy over baseline policies and adapt them over time. This turned out not to work very well, most working groups would forget to copy them over, and improvements to baseline policies rarely made it to those that did copy them over.

It makes sense that we should move to a model where TLPs and WGs are, by default, under baseline policies until such a point that they decide to design new policies or make modifications. This seems like the best way to maintain autonomy of project governance and reduce the cost and maintenance load of all the groups.

This is what @jasnell is eluding to, that our defaults moving forward is that "when this group does not define a policy it is under policy X" but we probably need to spend some time cleaning up the language in the project lifecycle and other policies to make that clear.

**Comment by saghul** [comment]
> It makes sense that we should move to a model where TLPs and WGs are, by default, under baseline policies until such a point that they decide to design new policies or make modifications. This seems like the best way to maintain autonomy of project governance and reduce the cost and maintenance load of all the groups.
> 
> This is what @jasnell is eluding to, that our defaults moving forward is that "when this group does not define a policy it is under policy X" but we probably need to spend some time cleaning up the language in the project lifecycle and other policies to make that clear.
> 

Sounds good. Are these policies available or is it being worked on?

> Just to be clear, the project still has the authority to adopt a different policy or make project specific changes to a policy, so we aren't removing any autonomy or project governance rights, we're just making it easier for projects to operate under foundation wide policies when they don't wish to write and maintain their own policies.

Yeah, I guessed that much. I'll try to come up with a PR that clarifies the language in the current text. The point of clarification being that TLPs oput of the Nodejs organization need to have some document because the baseline cannot be applied. (due to organization rights and so on).

Thanks everyone for keeping these discussions nice and open :-)

**Comment by jasnell** [comment]
Closing given that there has been no further discussion in over a year. Any additional discussion around this topic should be directed to the Community Committee
