### ISSUE TITLE
create public nodejs/collaborators repo

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#243]
It seems to me like there is a need for us to have a place for collaborators to discuss ideas that are not appropriate for the main tracker. 

I'd like to suggest that we create a new repo nodejs/collaborators, similar to nodejs/tsc and nodejs/ctc, as a place for these discussions to happen.

This could also be a great place to move conversations that have a good kernel but are inappropriate or derailing in other environments.

Unlike NG or EPS, collaborators would be an explicitly social repo, where we can explore ideas in good faith.

Thoughts @nodejs/collaborators

**Comment by addaleax** [comment]
Isn’t this basically what nodejs/CTC is supposed to be? If not: How would it be different? :)

**Comment by MylesBorins** [comment]
@addaleax perhaps you are right. After re-reading the README.md it is dawning on me that perhaps I had the wrong idea about what the CTC repos purpose was.

I'm going to close this with that in mind. If others think this has legs feel free to reopen

**Comment by Qard** [comment]
I've never really even looked at the CTC repo because the name just gave me the impression it was just for CTC members and not the greater contributor community. Might be nice to rename it to nodejs/collaborators.

**Comment by nebrius** [comment]
> I've never really even looked at the CTC repo because the name just gave me the impression it was just for CTC members and not the greater contributor community. Might be nice to rename it to nodejs/collaborators.

I never really looked at it either, for this same reason. I thought it's purpose would be analogous to nodejs/TSC which is just for TSC business.

**Comment by refack** [comment]
I support the `node/collaborators` idea. That way the `node/CTC` is kept for CTC related coordination.

**Comment by refack** [comment]
> > I've never really even looked at the CTC repo because the name just gave me the impression it was just for CTC members and not the greater contributor community. Might be nice to rename it to nodejs/collaborators.

> I never really looked at it either, for this same reason. I thought it's purpose would be analogous to nodejs/TSC which is just for TSC business.

You guys have been teaching me that wording makes a difference 👐 (no cynicism!)

**Comment by williamkapke** [comment]
FYI, this exists:
https://github.com/nodejs/collaboration

**Comment by addaleax** [comment]
I’m reopening, moving to nodejs/collaborators doesn’t seem like a bad idea. /cc @jasnell who originally created the repo, iirc

> FYI, this exists:
https://github.com/nodejs/collaboration

I know we talked about archiving that together with the nodejs/collaboration team, and I agree. It just seems like a stalled project that people only know about because it comes up in the autocompletion for nodejs/collaborators…

**Comment by refack** [comment]
> I’m reopening, moving to nodejs/collaborators doesn’t seem like a bad idea. /cc @jasnell who originally created the repo, iirc
> 
> FYI, this exists:
> https://github.com/nodejs/collaboration

But rename to `nodejs/Collaborators` yes? Re branding for new shot of life 
![image](https://cloud.githubusercontent.com/assets/96947/25044785/7b21905a-20f6-11e7-8bec-1360dd73eb2a.png)

**Comment by nebrius** [comment]
I forgot about nodejs/collaboration! It is also somewhat poorely named, as it's really nodejs/working-group-collaboration.

The idea behind that working group was to serve as a sort of clearing house for working groups, and to create a space for working groups to communicate with one another more easily. At the time, it was difficult for different working groups to talk to each other. IIRC myself and a few others from the now inactive nodejs/hardware WG were having a tough time getting in touch with folks we needed to in trying to get some initiatives going.

All of that said, I'm not sure this is as much of an issue anymore. nodejs/collaboration was created before the Node.js Foundation was created, and I _suspect_ that the structure we've created within the Foundation since then has more or less solved that particular problem. However, if there is still a need for such a group, then nodejs/community-committee is probably a good place to start organizing it.

**Comment by refack** [comment]
I jumped the gun, but I have a few questions I wanted to put in writing.

**Comment by jasnell** [comment]
At this point I am definitely -1 on creating another new repository for discussion. We have the existing nodejs/node, nodejs/ctc, nodejs/tsc, nodejs/NG, and nodejs/node-eps repositories. Perhaps the existing nodejs/collaboration repo can be repurposed, but I still see no need.

**Comment by addaleax** [comment]
Renaming `nodejs/CTC` to `nodejs/collaborators` seems perfectly fine to me.

**Comment by williamkapke** [comment]
> Renaming nodejs/CTC to nodejs/collaborators seems perfectly fine to me.

I'd rather we didn't do that. We mostly have a 1 to 1 relation to Committees/WGs/Teams and I think the consistency a good thing. Also- ya'll move a few documents from node core to this repo and those would be out-of-place if renamed to `collaborators`.

**Comment by jasnell** [comment]
I'm -1 on renaming nodejs/CTC as well. I simply see no benefit in doing so.

**Comment by refack** [comment]
> Renaming nodejs/CTC to nodejs/collaborators seems perfectly fine to me.

I thought the CTC needs a place to manage CTC specific issues.

I feel we are lacking a place to discuss idea that are unripe, or derailing. Since the `CTC`, `node` and `TSC` have a specific purpose and work under the "Consensus Seeking decision making model" where do we argue? Better, where can we have a discussion where we agree to disagree, a "Safe Place".
I still havn't found a place where I felt comfortable asking stupid questions (nodejs/CTC#100 exploded, [my pilot got push back as well](https://drive.google.com/open?id=0Bz0LZMH4OpErSkdSYVRfb2s2QjA) )

For you consideration...

P.S. Why is this discussion being held on the TSC (__Technical__ Steering Committee) repo? Shouldn't there be a dedicated `Governance` repo?

**Comment by addaleax** [comment]
> Why is this discussion being held on the TSC (Technical Steering Committee) repo?

Because the TSC owns all repositories under the `nodejs` Github organization by default, I guess. I don’t know. I would seem reasonable to me to have this discussion under nodejs/CTC but I don’t think the overhead of moving it again is worth it. :smile:

It seems to me like you are looking for a place that’s explicitly not looking for consensus-driven governance. If that’s the case (or if you generally want a place with other “rules”), then it would be good if you were explicit about that, so that we can see whether there is an actual desire for such a forum.

**Comment by refack** [comment]
I actually think @MylesBorins original  https://github.com/nodejs/TSC/issues/243#issue-221696885 states that very well.

>This could also be a great place to move conversations that have a good kernel but are __inappropriate or derailing in other environments__.

>Unlike NG or EPS, collaborators would be an __explicitly social repo__, where we can __explore ideas in good faith__.

I'm not talking about a cage-match repo, the contrary, a safe place.

**Comment by Trott** [comment]
> I'd rather we didn't do that. We mostly have a 1 to 1 relation to Committees/WGs/Teams and a repo. 

@williamkapke I hear you. I'm not disagreeing (or agreeing), but I definitely think we should take into consideration that acronyms like CTC, TSC, and even WG are kind of opaque to people who aren't actively involved in things like CTC, TSC, and various WGs. So naming a repo `CTC` works great for people like you and me, but not so great for newcomers. Heck, even people who have been involved with the project for months or longer often have no idea what the difference is between the concerns of the CTC and TSC.

I don't have an opinion (yet) but I certainly see the appeal of naming the repositories in a way such that you don't have to know anything about the project governance to have an idea of what will be discussed there.

**Comment by mikeal** [comment]
I think there's a few fundamental questions we need to answer here.

1. Do we *want* the CTC to form technical opinions as a group without first having a discussion with all the contributors?

Currently, technical issues escalate to the CTC after going through the Core repo. The CTC repo has been used for administrative tasks related to how the CTC and project operate, it hasn't been used to discussion technical issues.

2. Are there technical discussions about Core that we don't want in the Core repo.

We've resisted a purely discussion oriented repo related to Core to improve the visibility of those discussions and keep them in the Core repo. However, as the workload has grown people have tried to push less implementation specific discussions out of the repo. Is this the practice we want to endorse going forward or is this is a mistake? 

I'm not sure what the answers are here but there were a lot of reasons to lay things out the way they were and I want to make sure we're aware of the tradeoffs we're making as we consider moving some of this to another repo. Breaking stuff off into new repos has been a common practice as we've scaled things out but we've also had to remove some of the prior groups because they were spun out prematurely or were ineffective.

**Comment by refack** [comment]
@mikeal my 2 cents an older-then-the-hills-user / so-new-I'm-still-wet-behind-the-ears-Contributor
 
I strongly believe an all discussion repo is needed. For one, people in the functional repos expect/assume threads will lead to decisions. That mires the discourse, as people get defensive fast.
I personally had several bad experiences while trying to ask questions (admittedly while challenging implicit assumptions), people got very defensive very fast, to the point of aggression. I can only assume for fear of negative change, and protectiveness of the project.

Second point, we don't have a structured knowledge base. There's allot of institutional knowledge hidden within conversations in issues and PRs. Personally I had a hard time tracking down the reasoning behind decisions. And again when I ask, I get the door slammed in my face, confusing my curiosity for criticism.
I think that a discussion only repo will help concentrate this knowledge. I'm also volunteering to attempt and convert insightful discussions into wiki.

IMHO the repo should be as inclusive as can be so `CTC` is problematic (as noted above), maybe even the name `Contributors` is wrong, and it should be `technical discussion`

**Comment by mhdawson** [comment]
I can see the argument for another repo (as per the original suggestion in this repo) from the side of being able to subscribe to it or not.  For example, if we had a "half-baked-discussion" (picking a random name that reflects that ideas would not yet be fully formulated not what I'm suggesting :)) then only those who wanted to get involved in early discussion could subscribe.  

The assumption would be that the ideas discussed may or may not "graduate" to an issue in the node core repo once they were fleshed out.  I'd expect that after some discussion we'd find that some ideas which seemed a bit off the wall to start end up making sense and this would provide a place to let the brainstorming happen.

The second assumption is that  you'd not "miss out" by not participating in the earlier discussion as the discussion for ideas that went forward would still occur in the main node repo, just at a later point.

It those two assumptions don't hold, then I don't think another repo is as good an idea as discussions where decisions should be made for the project are probably best covered in one of the already existing repos.

**Comment by jasnell** [comment]
We already have homes for such discussions. The node-eps repository issue tracker, for instance. Why create yet another repo for folks to follow when the ones we already have aren't followed extensively? I see little evidence that adding yet another repo would help increase visibility.

**Comment by refack** [comment]
I think that `nodejs/EPS` has flatlined 😉 https://github.com/nodejs/node-eps/pulse
It also already has a creed "Node.js Enhancement Proposals for discussion on future API additions/changes to Node core"

While this suggestion is for a place that _"Unlike NG or EPS, collaborators would be an explicitly social repo, where we can explore ideas in good faith."_

**Comment by nebrius** [comment]
What about making nodejs/node-eps a bit more broad? It can contain formal proposals which follow the [format described in the README](https://github.com/nodejs/node-eps#format), and informal conversation focused threads.

As far as nodejs/node-eps flatlining, well, that's a thing that happens in open source sometimes, and it's entirely possible that either changing the format of that repo or creating a new conversation repo could still meet a similar fate.

**Comment by hackygolucky** [comment]
I love the idea of a collaborators repo. I contribute in various ways, but I don't think the discussions I'd like to have are generally appropriate for the Core repo or CTC repo discussions. I am also happy to weigh in where necessary in the various repos, but things like looking up Collaborators in one place is awesome for me to see as someone who needs to look that up to provide the free code for membership, as well as have meta discussions that maybe involve CTC/TSC/CommComm.

**Comment by jasnell** [comment]
I'm certainly not against the idea but I think we need to be mindful of the various other repos we have already (e.g. node-eps, NG, etc). Perhaps a guide that would help direct conversations to the right location. Of course, the other option is to have the Slack-vs-IRC discussion settled on the Community Committee side of things :-). My primary concern with a nodejs/collaborators repository is that we already have so many repositories to follow, and the volume of activity already makes it very difficult to track conversations.

**Comment by gibfahn** [comment]
>I don't think the discussions I'd like to have are generally appropriate for the Core repo or CTC repo discussions.

I think this is the key issue. Either we're not clear on what discussions are appropriate for the CTC repo, or there are discussions that aren't appropriate and we need another forum to discuss in. IDK which is the case, @hackygolucky if you could think of some examples that might be helpful.

>This could also be a great place to move conversations that have a good kernel but are inappropriate or derailing in other environments.
>
>Unlike NG or EPS, collaborators would be an explicitly social repo, where we can explore ideas in good faith.

So are these discussions okay in the CTC repo?

>but things like looking up Collaborators in one place is awesome for me to see as someone who needs to look that up to provide the free code for membership

I think cc/ `@nodejs/collaborators` or just looking at https://github.com/orgs/nodejs/teams/collaborators should cover that.

>as well as have meta discussions that maybe involve CTC/TSC/other working groups/CommComm

New collaborators automatically get write access to `CTC`, so they should also all be subscribed.

**Comment by refack** [comment]
I still feel there is no good separation between areas of discussion and areas of decision. Even though the PR process here is one of the better ones I've seen, there is still the "consensus driven decision" that IMHO makes people defensive (if they don't object something they don't want will happen).
I feel there should be a place to "fly test balloons" that pose no "risk" and that if and when will be turned into a real PR in code. A place where we don't strive to deceive just _"where we can explore ideas in good faith"_
For example my own nodejs/node#12935 and nodejs/node#12874, I'm not emotionally invested in them, they were "test balloons". Ideas I had, and took the time to turn into PR, with the knowledge they could be shelved. I enjoyed writing them, and found the discussion fruitful, but a bit defensive.
Maybe even just adding a "test balloon" label to PRs, with the promise not to remove it, but if and when spin off a new PR?

**Comment by jasnell** [comment]
Does this need to remain open?

**Comment by MylesBorins** [comment]
Closing for now. Can revsiit at a later date

**Comment by MylesBorins** [comment]
Closing for now. Can revsiit at a later date
