### ISSUE TITLE
TSC Director and Chair nominees- "Why I'm standing for election"

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#264]
As suggest here: https://github.com/nodejs/TSC/issues/259#issuecomment-301292534 this issue is for those who have accepted nominations to provide a "blurb" on why they are  standing for election and are a good fit for the job.

**Comment by mhdawson** [comment]
I'll go first:

My time with the Node.js community has taught me a lot about benefits of making sure we welcome all people and different types of contributions to the project. I see the opportunity to serve as the Director or Chair as a way to help build on the community's success in this area.  

In addition, I believe we should work to reach consensus on the key technical work that needs to be completed for future releases (a backlog of sorts), and then work to support those efforts.  To date we have made great strides through the work to improve tests/builds, code coverage, CiTGM, async hooks, N-API and so on. Let's accelerate this even further by identifying key areas, and then having the TSC work to support/promote them.  This could involve working groups or whatever approach makes the most sense.

While I do have my own beliefs, passions, and goals for the project, the last few years have demonstrated that we come to the best solution through dialog with more rather than less people.  As director or chair, I'd work to make sure we continue to follow the consensus seeking model and the benefits that come along with it.

I believe that my organizational skills, drive to make things happen and move forward, and shared values with the Node.js community makes me a good fit for one of these roles.  As the Director I would apply these skills/values to represent the priorities and efforts of the TSC/CTC.  As Chair I would apply these skills/values to work with the TSC to move forward relevant initiatives.

**Comment by jasnell** [comment]
I am putting my name in the hat for TSC Director because the role requires someone who understands the technical, political and business needs that exist across the whole of the Node.js project and has the aptitude for bridging and balancing those needs. The role also requires someone who not only has a strong personal vision for how the project needs to evolve but is willing and capable to work with others across the project and ecosystem on a shared vision that best enables continued growth and support for the whole of the ecosystem.

I have no desire to be the one who runs everything. I strongly feel that the Chair and Director positions should be separate roles filled by different people. I strongly feel that the working groups and individual contributors should have the greatest share of the authority and that the TSC and CTC should simply get out of their way as much as possible. The TSC should be viewed as a backstop and a resource, not as an authority from on high.

**Comment by mhdawson** [comment]
Just to clarify that I'm also +1 for separate people filling the Director and Chair roles.

**Comment by mhdawson** [comment]
Election done, closing
