### ISSUE TITLE
Shut down the Mailing List

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#268]
At CollabSummit we had a discussion about the mailing list.

Several people didn't even realize we *had* a mailing list. Pretty much everyone was horrified that nobody from the project is moderating it or answering questions even though it was previously an "official" communication channel.

For the last 2 years we've moved all discussions that *would* have been on the mailing list to GitHub. The TSC should make a decision now about actually shutting down the mailing list.

**Comment by isaacs** [comment]
I'd say "about time", but this is actually several years overdue.

**Comment by jasnell** [comment]
heh... that thing is still around? Which alias is it again? And yes, let's get it shut down.

**Comment by nebrius** [comment]
+1 on shutting it down.

**Comment by indutny** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by ChannelJuanNews** [comment]
+1

**Comment by jasnell** [comment]
Did this happen?

**Comment by MylesBorins** [comment]
Ping on this regarding mailing lists

**Comment by mhdawson** [comment]
I think this may be the mailing list that was mentioned: https://groups.google.com/forum/#!forum/nodejs

**Comment by mhdawson** [comment]
There have been 15-20 threads in each of Oct/Dec.

I assume we'd want to redirect those users to the help repo ?

**Comment by mhdawson** [comment]
@nodejs/TSC any objections to shutting down the mailing list ?

**Comment by mhdawson** [comment]
@rvagg do you have access to manage that mailing list. I'm guessing you might since you were able to give me those rights for nodejs-sec which is also a google mailing list.

**Comment by rvagg** [comment]
not I, iirc @bnoordhuis has some access on that one

**Comment by bnoordhuis** [comment]
I don't.  I believe that's @othiym23.

**Comment by othiym23** [comment]
I was handed moderation of the mailing list several years ago (~early 2014, IIRC) by TJ Fontaine in his role as project lead for Joyent, and since then it's been run by me, with @aredridel helping out from time to time. It's mostly quiescent and, I feel, does little harm; every message to the group is approved by either Aria or me, and I'm pretty strict about not approving content that runs contrary to the group's published rules (no spam, no job postings, no necroing several-years-old threads, no jerks).

At this point its primary value is its continued existence. Because of the twilight status of Google Groups, which exist in the interstices between mailing lists and forums, `nodejs` does still attract traffic through search that isn't caught by any GitHub issue trackers or IRC. Its usefulness, especially for newer Node users who don't know where else to go, is surprisingly high. Its reach is also further than you might expect, with there currently being 16,894 subscribers in the group (with the semi-obvious caveat that a significant percentage of those subscribers are ghosts or otherwise bitrotted).

I've offered a few times to hand it over to the Foundation, which in my mind entails bringing it under the aegis of the code of conduct and moderation guidelines, and handing off stewardship of it to whoever makes the most sense within the org (probably @nodejs/community-committee). I'm not going to argue strongly for its continued existence, but, given its low traffic (and low effort of maintenance), I'm a little surprised and dismayed to see the level of enthusiasm for shutting it down.  It's neither the flamewar zone nor the driving force that it was in days of yore; it's just another community tool that people can use to find help and promote their projects.

**Comment by aredridel** [comment]
+1 I'm happy to keep maintaining it as is.

**Comment by jasnell** [comment]
Is there a next step here or can this be closed?

**Comment by gibfahn** [comment]
Given that @othiym23 and @aredridel are happy to continue maintaining it, it is useful, and we haven't (AFAIK) had complaints, why not leave it as it is?

If someone wants to push for it to be brought into the foundation then that seems reasonable too, but otherwise I think this can be closed.

**Comment by othiym23** [comment]
It can take up to 12 hours for posts to get approved, or on the rare occasions where both @aredridel and I have our attentions elsewhere, maybe 24 hours. I think by and large posters are just surprised that messages don't go through instantly.

I'd be happy to add additional moderators should anyone else want to help out, but the level of activity is low enough, and the timeliness of the vast majority of posts irrelevant enough, that I don't think there's a pressing need. It's up to all y'all. It's a pretty light commitment.

**Comment by fhinkel** [comment]
As nobody has objected leaving them open, I'm closing this. Feel free to reopen if needed. 
@othiym23 and @aredridel thanks for taking care of the list!
