### ISSUE TITLE
Create an Admin team

### ISSUE THREAD

**Issue by nebrius** [nodejs/TSC#269]
As per the discussion in https://github.com/nodejs/TSC/pull/263, I propose that we create an Admin team that will handle the administrative duties that the TSC oversees.

The admin team would be tasked with:

- Managing travel requests
- Managing the budget for travel requests (and any other budgets the TSC oversees)
- Managing adding/removing users from the org/teams in GitHub
- Repository management (creating, archiving, etc)
- Manage communication between the board and the TSC on confidential matters (this one is a maybe IMO)

Let me know if I forgot anything on this list! 

The long term goal will be to charter a working group, but I think we should follow precedent and get a team set up and get some work done before chartering as a WG. Some of these tasks could also be shifted to CommComm, but I think it's a good idea to make these changes incrementally.

How does this sound to everyone? ping @nodejs/tsc.

If there are no objections or suggestions, I will create a repo for the admin team on Wednesday May 24 and start adding content.

**Comment by nebrius** [comment]
Oh, and for the record, I'm volunteering to help run this team.

**Comment by mikeal** [comment]
There have been multiple ideas floated for an "Admin Team" and I just want to reach some clarity on which this one proposing. There are essentially two versions I've heard:

* "Spin out the administrative decision making from the TSC into a group and then, potentially, collapse the TSC back into the CTC."
* "Spin out technical administration (comment moderation, org level banning, org level repo removal) into a subgroup that doesn't actually make the *decisions* about these actions but only implements them." Essentially this solves the "we have too many org owners" issue.

**Comment by nebrius** [comment]
I'm proposing the first option, "Spin out the administrative decision making from the TSC into a group."

That said, it may make sense to incorporate parts of the second into this as well. I suspect that in practice this admin team will do a mixture of the two depending on what's being discussed. Travel approval, for example, probably wouldn't bubble up to the TSC to make a decision, but repo management may.

I think that it's best to start working while we figure this out, as doing the work of implementing this will probably answer a lot of the questions we have around what the _best_ thing is, while also unearthing new questions.

**Comment by jasnell** [comment]
To be certain, this proposal has a few differences from my proposal in #263. I'm definitely +1 on having an admin team but a few points.

1. I'm not certain there's value is splitting this conversation off just yet. I think proposing this separately from #263 is just going to cause confusion. That said...

2. @nebrius said, `The long term goal will be to charter a working group` ... I do *not* think it should be a working group at any time really.

3. We should not do this if we do not also either adopt #263 or collapse the TSC/CTC back together into a single body, because there generally would be no point in doing so.

4. -1 on creating a repo for this at the current time.

5. The more I think about it, the more I like the idea of an Admin team that actual spans TSC and CommComm. We've had discussions about moderation and github organization ownership that actually make sense to *share* across the two. Having the CommComm Chair and either the TSC Director or Chair co-chair the Admin team, with team members coming from both groups makes a ton of sense. And the fact that it would not be a voting body, meaning that it would not actually *set* the policies, ensures a good check. It would also mean that the Admin team is accountable to both the TSC and CommComm.

**Comment by mikeal** [comment]
> Travel Approval

So far these have all been approved, but at some point it will become necessary for certain requests to be prioritized over others in order to stay within a budget. Something to keep in mind as you potentially offload that prioritization to a subgroup without a lot of guidance on how to do that prioritization.

> Manage communication between the board and the TSC on confidential matters (this one is a maybe IMO)

Currently, the Board Chair does this directly with the TSC. The TSC is also responsible for voting in the Board Chair. If you split these two things then the voters in the Board Chair Election may not have enough context to make an educated vote since they don't actually interact with the role.

**Comment by nebrius** [comment]
> @nebrius said, The long term goal will be to charter a working group ... I do not think it should be a working group at any time really.

I'm fine with this. I don't have a personal preference myself, I just know we had been informally calling it the "Admin WG" in discussion :)

> We should not do this if we do not also either adopt #263 or collapse the TSC/CTC back together into a single body, because there generally would be no point in doing so.

I would argue that forming this team is a necessary precondition for #263 or collapsing them back, and I get the impression that most people are in favor of making _some_ change. I think if we do not take this step, then #263/remerging will remain in discussion, so think of this as getting the ball rolling on larger changes.

> -1 on creating a repo for this at the current time.

Can you clarify? Is this because you don't think a repo is necessary for these activities? Or that we should not be forming the team at all? Other?

> The more I think about it, the more I like the idea of an Admin team that actual spans TSC and CommComm. We've had discussions about moderation and github organization ownership that actually make sense to share across the two. Having the CommComm Chair and either the TSC Director or Chair co-chair the Admin team, with team members coming from both groups makes a ton of sense. And the fact that it would not be a voting body, meaning that it would not actually set the policies, ensures a good check. It would also mean that the Admin team is accountable to both the TSC and CommComm.

I like this idea!

**Comment by nebrius** [comment]
> Currently, the Board Chair does this directly with the TSC. The TSC is also responsible for voting in the Board Chair. If you split these two things then the voters in the Board Chair Election may not have enough context to make an educated vote since they don't actually interact with the role.

🤔. FWIW I think the only reason to take this on would be because we decided to implement #263. As such, this would not happen right away.

**Comment by mhdawson** [comment]
I'll volunteer to participate in this team as well.
