### ISSUE TITLE
Not all members of the GitHub org are members of the members team

### ISSUE THREAD

**Issue by aqrln** [nodejs/TSC#284]
Sorry if it's not the right place to report it, but I couldn't come up with a better one.

As far as I understand, all members of the @nodejs GitHub organization should be members of the nodejs/members team, which is currently not the case (550 vs 446 people).

This is the list of GitHub org members who are not in the members team:

<details>
 <summary>Details</summary><p>

```
@agarwal-sandeep
@ak239
@amandeepmittal
@andrasq
@anirudh24seven
@aruneshchandra
@bcmarinacci
@bf4
@bmeurer
@boingoing
@bzoz
@cdnadmin
@Charlotteis
@claudiorodriguez
@CurryKitten
@curtisman
@davidmarkclements
@deian
@denysdovhan
@detailyang
@Devinsuit
@digitalinfinity
@drifkin
@EdMaurer
@ehsan
@ErisDS
@estliberitas
@eugeneo
@firedfox
@gabrielschulhof
@glennschler
@gokaygurcan
@gonenduk
@gr2m
@gsathya
@hhellyer
@htynkn
@hueniverse
@imran-iq
@jbajwa
@jeisinger
@jhamhader
@JiaLiPassion
@JimiHFord
@JoeDoyle23
@joshgav
@jpwesselink
@jrit
@junedev
@JustinBeckwith
@kfarnung
@kjin
@lance
@LaurentGoderre
@mattpodwysocki
@mgalexander
@michaelbpaulson
@mrkmarron
@MSLaguana
@mweagle
@node-forward-build
@nodejs-github-bot
@not-an-aardvark
@pavelfeldman
@pierreneter
@pin3da
@piperchester
@pmq20
@preco21
@princejwesley
@Qantas94Heavy
@qbit
@rachelnicole
@raphaelokon
@rnchamberlain
@roccomuso
@ronkorving
@RReverser
@ruggertech
@ryanmurakami
@saadq
@sakinac
@sampsongao
@SamuelBolduc
@scottgonzalez
@sethgaurav
@sinaomrani
@SomeoneWeird
@sotayamashita
@stefanmb
@tdtsh
@tpreusse
@trentontri
@undownding
@vdeturckheim
@whitlockjc
@wongzigii
@wraithan
@yanglei99
@yasinaydin
@ykzts
@yodeyer
@zdroid
@ZibbyKeaton

(104 total)
```

</p></details><br>

A quick and dirty script I used to generate this: https://gist.github.com/aqrln/2a1d865d37a35958d21ec9740d65e574

One can extends this script or write a new one to automatically add these users to the members team.

**Comment by addaleax** [comment]
I think it might be nice to have clearer rules around who’s a member of the org/of the members team in general (for example: Is it okay to add people to @mention-only teams like nodejs/url if they request it? They need to be added to the org for that. Should they be added to nodejs/members?).

One thing that I think we could do in any case is to make teams like nodejs/collaborators child teams of nodejs/members… right?

**Comment by mikeal** [comment]
Because there is no way to add "all org members" to a repo, and there is no way to @ reply all org members, we created the "members" team strictly for those purposes. So, every org member *should* be in the members group but it's not entirely automated so if people forget to do it when they add them to another team it doesn't happen until I run a script :)

BTW, I just ran the script again and added a bunch of people :)

**Comment by nebrius** [comment]
This raises a bit of a side topic: what should we do about people who were added as part of a WG, but then left said WG and are no longer active in the org? One of the people on the list above is a former member of the Inclusivity WG who stepped down.

**Comment by aqrln** [comment]
@mikeal thanks for getting this resolved :)

> but it's not entirely automated

I believe full automation should be pretty easy to do using an [organization webhook](https://developer.github.com/v3/orgs/hooks/) subscribed on [`OrganizationEvent`](https://developer.github.com/v3/activity/events/types/#organizationevent).

**Comment by Trott** [comment]
Adding `tsc-agenda` label (although I hope we can get resolution before the meeting) to get an answer to this question:

**Based on @mikeal's comment, we should remove people from the members team if they are not in any other team. Is it OK if I do that?**

Additional points in favor:

* Re-adding someone removed erroneously is straightforward, so it seems like a low-risk move.
* Removing people who are in members but nothing else would help a little bit with the push for 2FA.
* Membership in `members` gives access to the private moderation repo. IMO, that suggests we should actively manage that team.

/cc @nodejs/community-committee

**Comment by bnb** [comment]
@Trott I'd appreciate it if you could add cc-agenda as well 🙏

**Comment by Trott** [comment]
@nodejs/community-committee There was TSC consensus to move forward with removing folks who are members of the nodejs/members team and no other teams. Can I go ahead with this, or would you prefer to wait until after the January 4 CommComm meeting?

**Comment by pup** [comment]
fine by me, but if someone else want to wait until after the meeting, then let's do that

**Comment by mhdawson** [comment]
@Trott I'm +1 with my CommComm hat on as well.  @joyeecheung  I wonder if we can get/automate Mikeal's script.

**Comment by Trott** [comment]
I've done this for people who were only members of that group who also did not have 2FA enabled. If someone wants to find and remove the rest, I won't stop you. :-D

**Comment by joyeecheung** [comment]
@mhdawson 

As @aqrln proposed

> I believe full automation should be pretty easy to do using an organization webhook subscribed on OrganizationEvent.

But in the github-bot's readme there is:

> Org-wide webhooks are not allowed.

I wonder why there is a restriction on this? @phillipj

**Comment by phillipj** [comment]
From what I've understood its related to the same reasons we haven't
granted permissions to third-party GitHub apps/services like Travis CI.

A lot has changed the last year, i.e. the private org that has been
created, so historical concerns might not be valid anymore. Worth raising
the question again IMO.

**Comment by bnb** [comment]
Yes, from my understanding a lot of those changes were driven to allow org-wide access for projects and tools like this.

Could this be raised in a TSC meeting? It would be very helpful to get a solid update on it.

**Comment by mhdawson** [comment]
@bnd I think an issue that is focused on the question of org-wide access along with the specific question would be better than tagging this issue for the agenda.

**Comment by bnb** [comment]
@Trott I raised this in the last CommComm meeting, asking folks who haven't looked at it to take a look. There have apparently been no objections from the CommComm.

+1 from me personally, as well.

**Comment by jasnell** [comment]
Is there a next step here or can this be closed?

**Comment by Trott** [comment]
@jasnell Yes, a next step (might be considered scope creep, but I'm OK with it) is to make all relevant teams subteams of the members team so that there aren't individual members of the members team. 

I have that on my TODO list although if someone beats me to it, awesome. I think it was @targos's idea.

**Comment by Trott** [comment]
FYI, I've made @nodejs/hardware a subteam of the nodejs/members team and removed the people on the hardware team as direct members of the members team. (They are still members of the members team due to hardware being a subteam of members.) 

Hopefully they didn't get any misleading notifications about being removed from the members team. (Can you hardware folks let me know?) If not, then we can move forward with this pretty quickly and get this issue closed in a reasonable amount of time.

FYI @nodejs/community-committee

**Comment by dtex** [comment]
I did get the misleading notification, but I also got the notification on this issue.

**Comment by Trott** [comment]
It is done: `members` is now populated entirely from subteams. There are no individual members. 🎉 !!!

**Comment by Trott** [comment]
@nodejs/members If you received a notification that you are no longer a member of the GitHub nodejs org, please ignore it. It was the result of this administrative change. Sorry for the confusion, and thanks!

(You can tell that you're still a member if you weren't paying any attention to this issue and now are getting this notification because I @-mentioned the @nodejs/members team!)
