### ISSUE TITLE
Do we need policy on who should be org owners.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#289]
In the last TSC meeting when we discussed #125 we decided we should discuss if we need to formalize this or not.  Currently we handle it ad-hoc with people being added based on best judgement/need at the time.

The question we want to answer is:

" Is it ok to just continue to operate in this way or do we need a more formal documented policy ? "

Please comment.

**Comment by Trott** [comment]
> Currently we handle it ad-hoc with people being added based on best judgement/need at the time.

The list of owners has always been (or at least for a very long time) CTC + Mikeal. Presumably with Mikeal leaving the Foundation, it will be just CTC.

Whether or not `CTC === org owners` is the best way to handle things is a legitimate discussion point, but the org owners are not _ad hoc_ and have not been _ad hoc_ for years, if ever.

Also, whatever the decision, documenting it would be fabulous, obviously.

**Comment by nebrius** [comment]
@Trott perhaps a bit of context. We've been discussing for some time on whether or not members of the TSC should also be org owners. Given everyone on the TSC except me is also on the CTC it's more or less moot right now.

However.

There is a need for CommComm to have (a select few) of the permissions you can only get by being an org owner, specifically so that CommComm can add members to the org for itself and the teams and working groups it oversees. While we can always ask someone on the CTC add folks, we've found it to be cumbersome so far.

In https://github.com/nodejs/TSC/issues/285, we came to the conclusion that I should be added as an org owner this time around. Since I'm also on the TSC it's not that much of a stretch, but what about next time?

Also, there is no documented procedure for who is eligible and how one gets added as an owner. While our past approach may have been methodical, I would claim it still has been ad hoc from a procedural standpoint, because there's nothing that ensures we continue to follow this methodology in the future.

**Comment by Trott** [comment]
@nebrius Thanks. That context is very helpful. And yeah, I'd agree that `ad hoc` in that sense is correct. (Also, I got more than a few details wrong in my original comment and have edited it quite a bit. I tried to use strike-through where preserving the original wrong text might be important--that would be for the stuff I got _really_ wrong.)

One minor-but-possibly-important correction to what you wrote: I don't think you're the only person on TSC who is not on CTC. There are two others: Bert and Josh.

Since there are already two or three people on CommComm who are CTC, I'm surprised it didn't work to have one or more of them do the org stuff necessary. But if it didn't work well, then it didn't work well. ¯\\_(ツ)_/¯

**Comment by nebrius** [comment]
> One minor-but-possibly-important correction to what you wrote: I don't think you're the only person on TSC who is not on CTC. There are two others: Bert and Josh.

I always forget that Bert stepped down and Josh hasn't been added yet 😅 . I should get better at that.

> Since there are already two or three people on CommComm who are CTC, I'm surprised it didn't work to have one or more of them do the org stuff necessary. But if it didn't work well, then it didn't work well. ¯\(ツ)/¯

I'm guessing it's a matter of who's been active when we needed them? FWIW I'm not disparaging those people, it's totally fine, people are busy and whatnot.

**Comment by hackygolucky** [comment]
If we can have an active list of org owners specifically somewhere, I think that would be additionally helpful. For CommComm, that allows us to know who to ping or assign a task when we need an admin operation to occur.

**Comment by Trott** [comment]
> If we can have an active list of org owners specifically somewhere, I think that would be additionally helpful. For CommComm, that allows us to know who to ping or assign a task when we need an admin operation to occur.

This may change as this conversation works towards a conclusion, but as of right now, the org owners consist of the entire CTC, and that's it. CTC members are listed in the README for the nodejs/node repo.
