### ISSUE TITLE
Proposal to request community representation on Node.js Foundation Marketing Committee

### ISSUE THREAD

**Issue by rvagg** [nodejs/TSC#30]
Background: the Marketing Committee comprises mainly marketing people from many of the member companies of the foundation. They are the center of a significant amount of NF activity (the most activity perhaps?) and responsible for press releases, dealing with reporters and analysts, running the `@nodejs` Twitter account, they organised Node.js Interactive, and a bunch of other things and I'm likely not even aware of. They represent a very sizable spend by the Node.js Foundation, from memory they have the lion's share of the budget.

My concern is that their activities are almost entirely disconnected from what happens here, on GitHub, in IRC and other places where the the people driving the project forward exist. There's occasional overlap via @mikeal and I often hear/see snippets via our NodeSource marketing person and there's occasional mention in Node.js Foundation board meetings, but I know there's a lot that goes on that we never hear about. Usually I'm surprised at the scope of activity and analysis that goes on that we see nothing of here, with no mechanism for connecting the two ecosystems or providing value either way. To me this represents a big risk in the success of the Foundation, with potential for greater rifts developing between the financed activities and the community activities and a sense of _ownership_ of Node.js developing separately amongst the two groups leading to potential future conflict. Beyond that, there's very likely huge value being missed out on, for both groups, by not including community voices in marketing efforts _and vice versa_.

My straw-man proposal to start discussion is:

* Request from the Node.js Foundation Board and/or Marketing Committee that a number of community members be included in Marketing committee meetings, mailings, etc.
  - A representative nominated from the TSC
  - A representative nominated from the LTS WG
  - A representative nominated from the Inclusivity WG (if/when ratified)
  - A representative nominated from the Documentation WG (if/when ratified)

Implicit here is that:
 * There is representation from international efforts, TSC, Inclusivity and Documentation will hopefully have diverse international representation and pass that up through their Marketing Committee membership. I'm not sure we have an existing body we can use to represent these interests explicitly.
 * The representatives from these groups are responsible for filtering relevant information back into the community via their respective channels and we don't have to request explicitly from the Marketing Committee that information be provided.

**Comment by rvagg** [comment]
A representative from the Evangelism WG is an obvious oversight in my proposal.

The complete disconnect between Evangelism WG weekly posts on the nodejs.org blog and Marketing Committee press releases is another example of what I'm talking about. Another example is how release announcements are completely ignored by the Marketing Committee, e.g. the analysis of media that I've seen that they've undertaken doesn't look at any of this, the `@nodejs` Twitter account no longer makes release announcements and repeated attempts to get members of the release team access to that account have been rebuffed by Marketing folks. We're living in two worlds here that have no obvious intercept trajectories.

**Comment by Fishrock123** [comment]
cc @nodejs/tsc

**Comment by Fishrock123** [comment]
I'm in favor of anything that gets the marketing committee more connected to community efforts.

+1, would like so see an evangelism rep in there if any are still active.

**Comment by TheAlphaNerd** [comment]
I'm a member of a number of the WG's mentioned and would be up for getting involved. Should we have individual working groups nominate members or members of working groups volunteer?

**Comment by mikeal** [comment]
We can't really count on my overlap being enough here, I'm juggling a lot
of responsibilities and trying to bring in perspective from a lot of
places. This was working when we first started because there was just a lot
less going on but now there's just a *ton* of things happening.

One thing I will stress though, this is a reasonable time commitment.
There's a meeting every two weeks and materials sent out a few times a week
on average.

Another thing to think about, most of what the marketing committee does is
for the broader user community. More engaged and active Node.js developers
are well served by the evangelism work going on both from our Evangelism WG
and in the broader community and the foundation marketing efforts try their
best to be complimentary rather than competitive. So someone who is engaged
more in the user community is ideal for *most* of the work that is
happening there. This also means there's a lot of overlap between what
we're asking for out of these reps and the upcoming Individual Membership
Election for a board seat.

The marketing committee is a member committee, which means that any
corporate member at any level is on the committee. Which means it is quite
large, and growing larger, and it's getting more and more difficult to
reach quorum for votes. You're going to want to figure out if you even
want/need voting rights (votes are rare) for these reps or not.

Whatever you decide is the best course of action I'll work with you to draw
up a proposal for the board.

**Comment by jasnell** [comment]
This is good. While I do speak frequently with IBMs representatives in the marketing committee, we definitely do need more of a formal participation and connection.

**Comment by mikeal** [comment]
> the @nodejs Twitter account no longer makes release announcements

Can't we just automate this? If someone has a script I can get you a token for the account we can put in the secrets repo for these posts.

> The complete disconnect between Evangelism WG weekly posts on the nodejs.org blog and Marketing Committee press releases is another example of what I'm talking about. 

This is by design. 

The nodejs.org blog is part of the voice of the *project* and the *community*. I'm actually considering filtering out the press releases we post there so that they only show up under "announcements" in the foundation section. This voice is important, we need to be able give the community a place to speak publicly and in a somewhat authoritative voice. That goal is sometimes counter to the marketing and PR goals which, at times, are to be much more promotional. If we allowed the two to mix *too much* we devalue the voice of the project and become less authoritative.

You'll notice that today a post went out on Medium that is in a much different voice than anything we would want on the project blog. This is a better representation of how we want to separate these voices and target them at different audiences.

You have to remember, we have ~3.5 million users, we can't reach all of them with a single voice and there's a lot of targeting and selection that has to go in to appealing to different constituencies. 

I totally agree that we would benefit from better communication between these groups but I don't think the best end result is to completely unify these efforts because we have a lot of different goals and audiences and we'll end up reaching less people, not more, if we try to cram everything through a single pipeline. I also don't want to start to remove any responsibilities from the Evangelism WG or have them trying to run everything they do past a marketer, that would likely reduce contributions there to zero.

> There is representation from international efforts, TSC, Inclusivity and Documentation will hopefully have diverse international representation and pass that up through their Marketing Committee membership. I'm not sure we have an existing body we can use to represent these interests explicitly.

Perhaps the most robust way to structure this isn't to ask the board to appoint people from a bunch of specific WGs but instead to ask the board if the TSC can put people on the marketing committee in an advisory capacity at the TSC's discretion. That would allow any WG to ask the TSC if they can send a rep. They wouldn't have a voting seat but, IMO, that doesn't matter much -- most people give community reps a lot of influence and like to defer to them when possible.

This could also let the TSC more easily appoint people from WGs that aren't chartered yet if something comes up that the TSC really wants them to be involved in.

**Comment by rvagg** [comment]
> Perhaps the most robust way to structure this isn't to ask the board to appoint people from a bunch of specific WGs but instead to ask the board if the TSC can put people on the marketing committee in an advisory capacity at the TSC's discretion. That would allow any WG to ask the TSC if they can send a rep. They wouldn't have a voting seat but, IMO, that doesn't matter much -- most people give community reps a lot of influence and like to defer to them when possible.

That sound workable. I don't see having voting rights here helps a whole lot, this is mostly about connecting the efforts and advisory capacity would do that. It's also likely that having official voting rights doesn't add a whole lot of value beyond simply being involved in the conversation.

Being aware of, and being able to request resources for efforts at the community level would also be one of the aims here, there's a lot of money being thrown around and the work that we all do here on GitHub is _mostly_ not funded by that pool and it's possible that we could open up new avenues for community outreach with funding.

So, new proposal:

**TSC to ask the Foundation Board to be able to nominate >1 individuals to represent core and community efforts in an advisory / observation capacity in order to assist with connectivity between the two, currently separate outreach and communications efforts.**.

**Comment by Fishrock123** [comment]
> The marketing committee is a member committee, which means that any
corporate member at any level is on the committee. Which means it is quite
large, and growing larger, and it's getting more and more difficult to
reach quorum for votes. You're going to want to figure out if you even
want/need voting rights (votes are rare) for these reps or not.

Does it not also use lazy consensus? Also I don't think we'd need a vote.

> TSC to ask the Foundation Board to be able to nominate >1 individuals to represent core and community efforts in an advisory / observation capacity in order to assist with connectivity between the two, currently separate outreach and communications efforts.

That sounds good to me.

**Comment by mikeal** [comment]
> Does it not also use lazy consensus? Also I don't think we'd need a vote.

In practice: mostly, in the bylaws: nope. There are majority votes when stuff comes to a vote and there are quorum requirements. Most work ends up taking input from everyone and arriving somewhere everyone likes, many of those just go out and don't need to be voted on, but there are certain things that *have* to go to a vote in order to be completed and when they do we are required to reach a specific quorum.

**Comment by williamkapke** [comment]
I'm curious to know if this ever happened?
Status update?

**Comment by mikeal** [comment]
Yes, it did. Ashley from Inclusivity WG, Myles from LTS WG, and Julian from Evangelism have been invited :)
