### ISSUE TITLE
Re-merge TSC and CTC

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#312]
@nodejs/ctc @nodejs/tsc - We have discussed this for quite some time now. There is little continued reason for the TSC and CTC to continue as separate entities. I propose that we merge the CTC and TSC back into a single body. Essentially, what this means is (a) dechartering the CTC and (b) adding all current members of the CTC to the TSC. No TSC Charter changes are required. Some documentation would need to be updated, and the existing nodejs/ctc repository would be archived.

**Comment by cjihrig** [comment]
+1

**Comment by jasnell** [comment]
Here's my +1

**Comment by MylesBorins** [comment]
+!

**Comment by Fishrock123** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by indutny** [comment]
+1

**Comment by jasnell** [comment]
@nodejs/ctc and @nodejs/tsc members, while leaving emoji responses is fine in general, for this issue please indicate your position explicitly in a comment. I will prepare the necessary pull requests to kick this process off tomorrow.

**Comment by mscdex** [comment]
+1

**Comment by ofrobots** [comment]
+1.

**Comment by joyeecheung** [comment]
+1

**Comment by ChALkeR** [comment]
+1. I think that I liked the earlier proposal at https://github.com/nodejs/TSC/pull/263 more, though, but the change discussed here looks better than the current situation.

**Comment by flickz** [comment]
+1

**Comment by mcollina** [comment]
I'm +1.

**Comment by shigeki** [comment]
+1

**Comment by Trott** [comment]
I'm not opposed to this (yet), but I do think some additional things need to happen at the same time or else this is going to cause more problems than it will solve.

I'm going to greatly simplify things here (e.g., splitting problems into "technical" problems vs. "human" problems).

* As it stands now, this will basically result in the TSC being CTC + Josh Gavant. That's more representative of the project as a whole (in my opinion anyway) than the current remaining 9 members of the TSC, but...

* This is much larger than the current TSC. (It will be 23 people.) The CTC has been able to scale this big (again, in my opinion) in part because we've dealt with thorny technical problems mostly, and not thorny human problems or even thorny administrative problems. We discuss whether or not we should deprecate the `Buffer` constructor or whatever. Some people may feel strongly. Some may not have much of an opinion at all. Hopefully, we come to consensus. When we can't, we vote. After the vote, people are rarely resentful or bitter (as far as I know). If the vote doesn't go your way, you accept it and maybe plan to bring it up again in 6 months to see if things have changed.

* That process fundamentally does not work with thorny human problems (interpersonal disputes, accusations of misconduct, etc.). People are understandably more invested in outcomes and far more likely to be resentful when things don't go the way they believe they should. These problems need more care and attention, or at least a different kind of care and attention.

* A person who does well on a technical committee is not necessarily also skilled at community leadership and governance. (I'm not trying to excuse unacceptable behavior on the part of technical people. This is not "Oh, that person is a tech person, of course they don't know how to communicate." This is "Knowing a lot about Domain A does not automatically make you an expert in Domain B, even if Domain B has overlap with Domain A.")

* Additionally, I think we've yet to see excellent results in using our technical governance as a model for non-technical governance. Acceptable results? Sometimes. Great results? I could be wrong, but I'm not seeing it. Maybe engineering-focused solutions aren't the answer here.

Here are some thoughts. (And if I talked with you about this stuff today/tonight and I'm basically using your idea, feel free to call me out on it. Everything is a blur right now and I'm just typing what I think is important and correct.)

  * The TSC and/or CommComm might be able to handle Moderation policy enforcement. (Or maybe not. Guess we'll find out.)
  * Larger issues around conduct and interpersonal issues need to be handled by people skilled at this sort of thing. Perhaps professionals employed by the Foundation who are skilled at mediation, conflict resolution, etc.? I don't know what the answer is here, but questions of misconduct should probably be handled by some entity created by the Board. and not the people trying to figure out what version of V8 should ship in Node.js 9.
  * It may be worth considering terms for serving on the TSC. It's not so much to give people an opportunity to be voted off the island as much as it is providing an opportunity (at a regular cadence) to consider whether it's time to step down. If you have to decide yourself to do it, there's always "wait until next quarter". But if your term ends in December or whatever, then you have a natural and obvious time to move to Emeritus. It might take the weight off the decision a bit.

I have lots more thoughts, but those are the big ones, at least right now. Thanks for reading.

**Comment by jasnell** [comment]
@Trott ... already in progress. See [1](https://github.com/nodejs/TSC/pull/318), [2](https://github.com/nodejs/TSC/pull/276) and [3](https://github.com/nodejs/TSC/pull/219)

**Comment by fhemberger** [comment]
@jasnell Whatever you decide, please remember to open an issue/PR after the merge for the nodejs.org website.

**Comment by Fishrock123** [comment]
Re: @Trott 

As (at least partially) previously discussed we should form two groups:
- An admin / budget team probably spun of from the CTC.
- A separately appointed moderation team [like rustlang has](https://www.rust-lang.org/en-US/team.html#Moderation-team).

**Comment by mcollina** [comment]
I'm definitely 👍  on both. I personally do not want to engage in moderation activities (as other CTC members) and having a separate moderation team will solve the problem.

**Comment by jasnell** [comment]
Re: the admin team, please see https://github.com/nodejs/TSC/pull/219

**Comment by maxmckenzie** [comment]
+1

**Comment by joshgav** [comment]
+1, the members of the CTC are best qualified to technically steer the Node.js project(s) and should be part of the top-level decision-making body, glad to see this happening. I'd like to remain a TSC member and I try to put Node's interests first but if my membership is controversial do what's necessary with me :). Feel free to contact me directly too. [Postscript: I'm on parental leave at the moment.]

**Comment by jasnell** [comment]
This has landed. The CTC and TSC are now one.
@joshgav ... you're still on the TSC.

**Comment by Kimberly050174** [comment]
J
