### ISSUE TITLE
New TSC Director/Chair Elections

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#326]
@nodejs/tsc ... Now that the TSC and CTC have been merged back into a single body, I would like to call for a new TSC Chair and Director election. The prior election was held when there were only 13 members. Now that there are 22 members, it makes sense to run the election again, giving others the opportunity to put their hands up and giving the larger group the opportunity to vote.

@Trott and @mhdawson each have my absolute confidence and trust as chairs, but our process allows for only one official chair, so a decision would definitely need to be made there. 

The way that we have done this previously is to provide a period for individuals to self-nominate.

**Comment by Fishrock123** [comment]
I suggest that we have an _at minimum_ 2 week nomination period.

**Comment by joemccann** [comment]
@jasnell I have a couple of questions:

1) If the TSC and CTC are now a single body, what is this body now referred to as? TSC? CTC? Something else?

2) Since the TSC is now more or less absorbed into the CTC or dissolved altogether, help me understand the need for a new Chair for the nonexistent TSC? Obviously this question could be moot based on the answer(s) to my first question.

Thanks for your consideration.

**Comment by refack** [comment]
I want to ask why isn't the election open to a larger body (all Members or Core-Collaborators)?

**Comment by jasnell** [comment]
@joemccann ...

1. The "new" body is called the TSC and falls under the TSC Charter. Essentially what the merger did was dissolve the CTC and pull it's membership into the TSC.

2. It's the other way around. Whereas before we had a CTC Chair, a TSC Chair, and a TSC Directory, now there are only two positions: the TSC Chair and TSC Director.

@refack : In theory, the TSC could establish a process for voting among the full collaborator base but that proposal has not been made yet. If you have specific ideas on that, I invite you to open an issue or (better yet) open a PR with specific text. I do not think that a TSC Charter change would be required.

**Comment by jasnell** [comment]
I'd like to make it clear that I will *not* be nominating myself for either position.

**Comment by mhdawson** [comment]
+1 and I'd agree that 2 weeks to allow nominations makes sense.

**Comment by williamkapke** [comment]
**Note 1:** Pretty cool. 😎 

**Note 2:** The elected Director will serve the remainder of the term of the resigned position. [By-Laws Section 4.6](https://github.com/nodejs/board/blob/master/by-laws.md#section-46-vacancies)

**Note 3:** @mhdawson Are you resigning your position? Please drop a note- otherwise, you remain the person filling the By-Laws defined "Chair" role.

**Note 4:** The TSC charter still contradicts the By-Laws; it only mentions a Chairperson that serves on the board. When there is a conflict like that, the By-Laws win.
<sup>I'm still hoping the TSC will update [Section 7](https://github.com/nodejs/TSC/blob/master/TSC-Charter.md#section-7-elections) in the future to remove this confusion.</sup>

**Note 5:** The By-Laws do not restrict who can serve in the positions (e.g: TSC member). The TSC Charter, however, restricts it's definition of a "Chairperson" to the TSC members.

**Note 6:** I will not be nominating anyone.

**Comment by mhdawson** [comment]
@williamkapke are you saying I need to resign for their to be a new vote on the Chair position ?  I believe we should have a new vote but have not yet figured out what I want to do going forward.

**Comment by mhdawson** [comment]
To clarify I'm happy to do whatever we need for the new vote to take place, just want to do what is best in terms of transition between now and when the vote is completed.

**Comment by williamkapke** [comment]
@mhdawson Cool. Yes, you need to officially resign the position. You've _basically_ said it already... but a solid statement is always better to avoid confusion. (maybe just edit above?)

**Comment by yunong** [comment]
I would like to nominate @mhdawson for chair and @jasnell for director.

**Comment by mhdawson** [comment]
To make it official:

" In order to allow for a new vote on both the TSC Director and TSC Chair following the merge of the CTC/TSC I resign effective the same day that the vote for the new representatives opens".

I've worded this way to minimize the gap where we don't have representation but if that does not work for some reason just let me know.

**Comment by jasnell** [comment]
@yunong ... thank you, I appreciate the vote of confidence. What I would like to see at this point are others on the TSC being willing to step up and fill the role. If no one else does step forward by the time the nominations close, then I will accept the nomination.

**Comment by ofrobots** [comment]
@MylesBorins  is OOO for a couple of weeks, but I think he wanted to volunteer for the director position as well.

**Comment by MylesBorins** [comment]
I would like to self nominate for director

**Comment by mrhinkle** [comment]
We have legal counsel retained by the Foundation, I've asked him to take a look at the process here to make sure the interpretation of how the bylaws apply are interpreted correctly. So that the elections are successful and valid.

**Comment by mrhinkle** [comment]
From Andy Updegrove the Node.js Foundation Counsel, just to make sure it's clear what should happen. I hope this helps:

4.3(e): The TSC "shall designate a representative to the Board of Directors in accordance with Section 5.4(b)..." While the word "designate" is used, this Section defers to 5.4(b) to interpret what "designate" means. 

5.4(b):  The TSC "shall elect a Chair and a TSC Director (as defined in Section 4.3(e))...." So the clear answer is that the TSC votes to fill both positions.  

4.6(a): Provides that a vacancy "occurring as a result of the ... resignation ... of a Director who was ... nominated and elected by ... the TSC, may be filled by ... the TSC..." While the word "fills" because of previous language relating to both appointed as well as elected members, 4.6(a) goes on to state that the "term of a Director so ... elected shall be the unexpired portion of the term of the Director ... the Director so ... elected is replacing." 

The TSC elects a successor to a resigned TSC Director, with the replacement serving for the balance of the resigned Director's term.

**Comment by Trott** [comment]
Since I was the CTC chair, I guess it's worth making it explicit: I do not intend to run for TSC chair at this time.

For clarity: I am currently not the chair of anything. I *was* the chair of CTC. It doesn't exist anymore. @mhdawson was the chair of TSC and still is.

**Comment by rvagg** [comment]
4 days left for nominations.

Still looking for a Chair to help with the cat herding. Know that if you take chair then there will be others that will provide you with all the support you need to make it successful. Rich has done an amazing job (thanks again @trott) and I'm sure would lend a hand on any of the procedural work. I'm more than happy to lend a hand in any way you I can as I'd love to see someone flourish in this key role. It's been great to watch people on the team step up to take on areas of responsibility (@mcollina and @chalker I've been impressed by in particular) that have been vacated in this interim time and I'd hope we can keep that load-sharing going.

**Comment by mcollina** [comment]
Thanks @rvagg! I'm not self-nominating for any position because of my traveling for work.
However, I'm happy to support the new Chair and Director as much as they need!

**Comment by MylesBorins** [comment]
Since it doesn't seem to have been made official in here, or perhaps I am missing it, I would like to nominate @mhdawson as the chair

**Comment by Mickael-van-der-Beek** [comment]
@ChALkeR Are you thinking of nominating yourself?

**Comment by mhdawson** [comment]
@MylesBorins thanks for the nomination. I was waiting to see if other people wanted to take on the role, but since at this point there are no other nominations I'll accept the nomination.

**Comment by williamkapke** [comment]
@mhdawson - @yunong nominated you for director. Do you accept that nomination?

**Comment by benjamingr** [comment]
@thefourtheye has pointed out two weeks have passed. 

It looks like there is exactly one nomination for director (@MylesBorins) and exactly one for chair (@mhdawson) and two weeks have passed.

**Comment by mhdawson** [comment]
Adding to agenda so we discuss in the TSC meeting tomorrow

**Comment by geek** [comment]
I'd like to formally nominate @mhdawson for the director.

**Comment by mhdawson** [comment]
@geek thanks for the nomination but I'd like to maximize participation in the two roles and since Myles only nominated himself for Director I'd prefer to leave it as him being the sole candidate for Director and myself as the candidate for Chair.  Of course if other people want to take on either role then nominating them and having a vote makes sense.

**Comment by williamkapke** [comment]
@mhdawson The 2 week window has passed. Let's call it and close this out to remove confusion.

**Comment by jasnell** [comment]
@williamkapke ... If there's consensus among @nodejs/tsc members to do that, sure. 

@nodejs/tsc ... Please weigh in. The selection of the TSC director and the TSC chair is the TSC's responsibility. There wasn't much discussion for the 2 week nomination window. Does that imply we have a consensus on moving forward?

**Comment by Trott** [comment]
>  Does that imply we have a consensus on moving forward?

Yes.

**Comment by mcollina** [comment]
> Does that imply we have a consensus on moving forward?

Yes

**Comment by ChALkeR** [comment]
@Mickael-van-der-Beek No.

**Comment by Trott** [comment]
We have two positions and one nominee for each position. 

TSC Charter says:

> No election is required if there is only one candidate and no objections to the candidates election.

Unless someone is about to mount a vote-of-no-confidence effort against one of the candidates, there's nothing much to do or say here (unless someone wants to leave a nice note about how awesome they think Michael and/or Myles will be as the chair and director respectively).

I imagine we can formalize the results at tomorrow's meeting quickly.

**Comment by rvagg** [comment]
Yes, in the past we have taken single nominations to mean we just move forward with those individuals, no reason that shouldn't apply here. If someone objected strongly enough they should present an alternative. If there is loss of confidence during the term then we deal with it then with a separate process. +1

**Comment by jasnell** [comment]
Works for me. I do wish that the tsc members as a whole would demonstrate more engagement with this but I guess if no one has spoken up by now.... I certainly have no objections.

**Comment by thefourtheye** [comment]
+1 to @mhdawson for the TSC Chair and @MylesBorins for the TSC director.

**Comment by jasnell** [comment]
The election is complete.

**Comment by benjamingr** [comment]
Thanks for all your hard work as director @jasnell ! Congrats @MylesBorins

**Comment by jasnell** [comment]
Thank you @benjamingr
