### ISSUE TITLE
Clarification of "intentional, targeted trolling" claim made by Node.js representative

### ISSUE THREAD

**Issue by DelanoJ84** [nodejs/TSC#331]
On August 28, 2017 the ["Code of Conduct violations by Kat Marchán (/u/maybekatz & @maybekatz)" issue](https://github.com/nodejs/TSC/issues/325#issue-253509966) was opened which included multiple Code of Conduct breaches. @Fishrock123 closed it 12 minutes later and wrote "intentional, targeted trolling".

Could the board expand on this? @Fishrock123 did not explain what the "intentional, targeted trolling" was or whether he was referring to the person who was breaking the Code of Conduct through:

1. The use of sexualized language or imagery
2. Trolling, insulting/derogatory comments, and personal or political attacks
3. Other conduct which could reasonably be considered inappropriate in a professional setting

Or the person who opened the issue.

I'll add that I have copied the issue and submitted this report myself to the provided report@nodejs.org email. I am assuming the statement "this report appears to be random trolling not submitted in good faith" was referring to the improper means through which the CoC violation was reported and did not represent a policy of using the perceived "good faith" of the reporter to determine whether to enforce the Code of Conduct.

**Comment by fhinkel** [comment]
Closed, as author already emailed report@

**Comment by benjamingr** [comment]
Reports of code of conduct abuse are investigated by the moderation team in private - out of respect to the privacy of the sides involved. In any case kat is no longer a collaborator in the Node.js project for some time (her choice) so there won't be anything actionable anyway.

As for why Fishrock closed the issue is because the process was explained: 

> Legitimate, Code of conduct complaints should be reported to our report@nodejs.org alias. This report appears to be random trolling not submitted in good faith.

And making it public on purpose instead of reporting it as requested didn't seem like an effort done in good faith, to say the least.

**Comment by DelanoJ84** [comment]
@fhinkel I emailed the original ["Code of Conduct violations by Kat Marchán (/u/maybekatz & @maybekatz)" issue](https://github.com/nodejs/TSC/issues/325#issue-253509966) since it involves clear breaches of the Code of Conduct, though from @benjamingr's statement it seems her accusations would be more an issue for npmjs.

The claims that opening the issue was "targeting" kat, assuming it was directed at the opener, is a strange accusation to make while representing the foundation, particularly given how inflammatory the actual statements reported are and the fact that the reported person actually went out of her way to cause outrage. Regardless of whether the person opening the issue was "trolling", it seems odd that the present reason given by the board after someone improperly reports an issue over kat's inappropriate sexual comments and accusations is to claim the opener was the one somehow "targeting" this former contributor. A boilerplate reason to close the issue like "please report through the proper channels" or "kat is no longer a contributor" would be best, but it's odd that on top of the unneeded commentary the one person the board chooses to issue make this commentary on is not the one who seems to deliberately inciting further outrage and objectively causing more trouble for NodeJS but the person who opened the issue.

**Comment by MylesBorins** [comment]
@DelanoJ84 I'm locking the thread.

As mentioned earlier Kat is not a Node.js Collaborator and as such there is nothing actionable for us to do here. We do handle all moderation requests privately out of respect for all those involved.

One thing I do recognize here is that there is a need to improve how we communicate CoC violation reports regarding collaborators and leader in a way that respects privacy while maintaining an open communication line with our community. I am very interested in helping to develop process for this. If you would like to chat about this at all please feel free to message me privately [on twitter](twitter.com/mylesborins) or via DM. As a heads up I will likely not be able to fully engage until after labor day due to being on vacation right now.
