### ISSUE TITLE
Should we auto-close stale issues?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#342]
There is a tool for this https://github.com/twbs/no-carrier

Not sure if this is something we want to explore or not.

**Comment by ljharb** [comment]
Whenever an issue is closed by a non-human for any reason other than "it's merged or resolved", it feels hostile.

npm does this, for example, and it seems very unpleasant for all the people it happens to, including me. I feel pretty strongly that it makes life harder for users (and also makes them feel less welcome) in order to make life slightly easier for maintainers.

**Comment by MylesBorins** [comment]
@ljharb thanks for the response. Taking that into mind I think I'm going to close this for now.

To other maintainers in the project please feel free to reopen if you feel passionately about it
