### ISSUE TITLE
Regular WG Status updates in TSC Meetings

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#352]
Ping @mhdawson... I would like to propose that a segment of each TSC meeting be formally set aside for regular WG status updates. These can be quick 5 minute updates about what each WG is currently working on. It needs to be a formally scheduled part of the agenda or it will not actually happen.

**Comment by mcollina** [comment]
5 min for each WG will eat time pretty quickly. I'd say 1-2 minutes for each WG, if there is anything relevant to say (but the question should be asked every time).

**Comment by jasnell** [comment]
I'm not concerned about the specific amount of time given, it just needs to be explicitly scheduled.

**Comment by MylesBorins** [comment]
I think that it important to figure out what the purpose of this is.

Is it to update the TSC on what is currently happening with the WGs? Is it to give the community insight into what is going on?

We use to have the standup which kind of did this... although it was focused on individuals rather than wgs.

If the purpose is to update the TSC this could likely be done via a meta meeting that is recorded or through an email. If the purpose is to update the community this could likely be done in a different meeting specifically for the purpose of this.

This is not to say I don't think this is important, more that it isn't clear that this is the best use of our time during the meeting when it could be done async

**Comment by jasnell** [comment]
> Is it to update the TSC on what is currently happening with the WGs?

Yes. It is to ensure that there is appropriate visibility into what is happening across the project.

It is also to ensure that WGs have sufficient representation and attention within the TSC. The Website WG, for instance, has been fairly well neglected by the TSC for quite some time. Fortunately that WG has been productive on it's own regardless of that neglect.

To be honest, I couldn't care less what the exact process or format is here. As I have consistently advocated, the Working Groups, if they are going to continue to be formal autonomous entities, need to be (a) empowered to do more on their own and (b) need to have more attention given to them by the TSC. Case in point: how many TSC members know what the primary issues the website WG is looking at? How about the Build WG? What issues are the Stream WG looking at? I'm sure we all have bits and pieces of all this but exceedingly few of us have access to the bigger picture... which is bad.

> more that it isn't clear that this is the best use of our time during the meeting when it could be done async

Sure, it *could* be. We *could* have been doing it all along, but we haven't been. This is about making syncing up with the working groups a *priority* to ensure that what *could* be done *is being done*.

**Comment by mhdawson** [comment]
I like the idea of having a section on the agenda for WGs.  it fits with trying to look at some "bigger picture" issues in the meetings versus just handling specific immediate issues that need TSC input.

In order to avoid having it be 1-2 min per WG, I'd suggest we rotate, so that each meeting we cover a subset of the WGs and give them a bit more time.

**Comment by jasnell** [comment]
Whichever works the best for you @mhdawson

**Comment by mcollina** [comment]
SGTM

**Comment by Fishrock123** [comment]
I think we should at least try this out.

**Comment by mhdawson** [comment]
Agreed in TSC meeting to try it out. I'm going to add 1 WG to the agenda each week, initially looking for the allocation to be 5-10 mins.

**Comment by mhdawson** [comment]
We have it on the next agenda closing.
