### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/TSC#370]
The [Hacktoberfest](https://hacktoberfest.digitalocean.com) just came up again and I think we should label multiple issues (especially the good first contribution ones) with the according label. What do you all think?

**Comment by MylesBorins** [comment]
There were complaints last year with people gaming the system. I think if we want to participate we may want to make sure everyone is on board

/cc @nodejs/community-committee who is likely a good group to chime in on this

**Comment by gr2m** [comment]
It's a nice initiative, but don’t expect any retention, and a lot of noise. Last year lots of folks sent non-sense PRs just to get the t-shirt, I think they have better rules this time, I’d need to check though. 

I just created this issue, folks clearly don’t read the instructions lol:
https://github.com/gr2m/initials/issues/32

**Comment by BridgeAR** [comment]
The rules still seem very simple and do not prevent a lot of misuse. I think they should have stricter rules as e.g. getting a PR merged but that is obviously out of our control.

> Rules
>
> To get a shirt, you must make four pull requests between October 1–31 in any timezone. Pull requests can be to any public repo on GitHub, not just the ones we’ve highlighted. The pull request must contains commits you made yourself. Pull requests reported by maintainers as spam or that are automated will be marked as invalid and won’t count towards the shirt.

**Comment by gr2m** [comment]
when you sign up they warn about spam pull requests

![image](https://user-images.githubusercontent.com/39992/30941781-16ff1998-a39c-11e7-9265-27047361005d.png)

**Comment by Trott** [comment]
Also note that "participating" in this context seems to simply mean creating a label in the repo and applying it to some issues. **Whether or not we actually do that, people can get their Hacktoberfest t-shirt by opening PRs against our repo.** So this is not a high-stakes decision, as I see it anyway. 

(I'm totally neutral. Sure, let's create a label. Or no, because it _might_ attract low-quality PRs and we're going to have our hands full reviewing/CI'ing/merging with 200-ish PRs coming in during Code + Learn next week. Or whatever. No opinion from me.)

**Comment by Trott** [comment]
(Compromise: Let's create the label, but only *after* Node Interactive. :-D )

**Comment by fhinkel** [comment]
As Node Interactive is over, ping @BridgeAR

**Comment by richardlau** [comment]
I'm guessing this can be closed now?
