### ISSUE TITLE
Provide Code and Learn Agendas Prior to Events

### ISSUE THREAD

**Issue by cjihrig** [nodejs/TSC#374]
Sorry if this is already documented somewhere that I'm unaware of.

I think it would be nice if Code and Learn tasks were documented prior to the actual event. This might even be done in private if you're worried about people coming along and working on all of the tasks.

My reasoning is that each C&L event seems to generally have some theme (change all the `var` to `const`, wrap everything in `common.mustCall()`, etc.). Under normal, non-C&L circumstances, a contributor would open a single PR, or multiple small incremental PRs to make the same changes. This would go through a normal code review process, and potentially end up closed without merging.

However, these C&L events are essentially opening huge distributed PRs to do the same thing. There is no way to provide feedback on a general concept without commenting on many similar PRs and potentially discouraging new contributors.

Notifying the TSC of the agenda prior to the event could likely prevent this scenario. My guess is that the majority of the time, there would be little to no feedback needed or given.

**Comment by Trott** [comment]
I'm on board with running these things by a small group of interested parties ahead of time. I already do that with @addaleax and sometimes @bengl. Moving to the next letter of the alphabet, I can add @cjihrig, if you want.

**Comment by Trott** [comment]
I'm going to close this, 'cause I basically think this is resolved. If you feel otherwise, feel free to re-open, but it might be better suited in the code-and-learn repo than here.

**Comment by cjihrig** [comment]
I think I'd like to see the plans ahead of time. I can't speak for anyone else though.

**Comment by jasnell** [comment]
@Trott... I know you do quite a bit of tedious thankless work getting these things organized (well, you and @addaleax) and I'm absolutely grateful. I'm good with whatever process you'd like since you're the ones doing the work and I've had zero issues with the workshop tasks. If there's anything that could be done here to increase transparency, perhaps just having a github repo of the task descriptions (you're typing them up anyway to print them... so pushing them to a repo wouldn't be too difficult as an additional step). Anyone who is interested in reviewing those could then easily do so).
