### ISSUE TITLE
Proposed New TSC Meeting Schedule

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#444]
Current meeting times in UTC are 12:00, 17:00, and 22:00.

End of the year seems like a good time to review the meeting times. (I think a six-month cadence on that is probably about right.) 

If nobody on @nodejs/tsc has any changes to make to the availability spreadsheet then the fairness algorithm I use to suggest times is recommending UTC 00:00 (midnight), 13:00, and 20:00.

|UTC|Berlin|Moscow|Chennai|Beijing|Sydney|San Francisco|New York|
|----|------|--------|---------|-------|------|---|-----|
|midnight|1:00&nbsp;AM|3:00&nbsp;AM|5:30&nbsp;AM|8:00&nbsp;AM|11:00&nbsp;AM| 4:00&nbsp;PM| 7:00&nbsp;PM|
| 1:00 PM | 2:00&nbsp;PM|4:00 PM|6:30 PM|9:00 PM|midnight|5:00 AM|8:00&nbsp;AM|
| 8:00 PM | 9:00 PM | 11:00&nbsp;PM | 1:30 AM | 4:00 AM | 7:00 AM | 12:00 PM | 3:00 PM|

If you want to influence the time slot selection, please update your row in the spreadsheet and let me know to re-run on the new data.

(And, of course, the algorithm is just an algorithm. We can debate/discuss appropriate times and don't have to accept these. Matteo and I already had a talk in IRC while I was typing up this issue!)

**Comment by Trott** [comment]
Some folks have updated their availability. This could be a wild ride. Here's the new fair times proposal:

|UTC|Berlin|Moscow|Chennai|Beijing|Sydney|San Francisco|New York|
|----|------|--------|---------|-------|------|---|-----|
| 1:00&nbsp;PM | 2:00&nbsp;PM|4:00 PM|6:30 PM|9:00 PM|midnight|5:00&nbsp;AM|8:00&nbsp;AM|
| 3:00&nbsp;PM | 4:00&nbsp;PM|6:00 PM|8:30 PM|11:00&nbsp;PM|2:00 AM|7:00&nbsp;AM|10:00&nbsp;AM|
| 10:00&nbsp;PM | 11:00&nbsp;PM | 1:00&nbsp;AM | 3:30 AM | 6:00&nbsp;AM | 9:00 AM | 2:00 PM | 5:00 PM|

**Comment by Trott** [comment]
Wait, I'm wrong! We're back to the original times. I'm going to delete this comment and the one above.

**Comment by ChALkeR** [comment]
Looks good to me.

What is the exact proposed schedule, i.e. starting with which date should it become effective _(assuming next+1 meeting?)_ and at what time should the first meeting using this new schedule happen?

**Comment by joyeecheung** [comment]
LGTM

**Comment by mhdawson** [comment]
LGTM

**Comment by rvagg** [comment]
Works really nicely for me but perhaps that's not a good thing because there's only one of us down my way and in this schedule Europe, Russia and Asia get worse time slots than I do. The 5am Pacific (1pm UTC) is a concern too, lots of black, red and orange in that column and I have I reckon that reds and oranges are more likely to be black in practice when a 5am meeting rolls around (speaking from lots and lots of experience with regular early morning meetings!). Moving it an hour later would likely knock me out but I think we'd get more likely attendees in that slot. Both the sum and average of the ratings in that slot go up by quite a bit if moved later by an hour.

**Comment by jasnell** [comment]
I'd prefer to keep the current times as they are.

**Comment by fhinkel** [comment]
I think everybody except the East coast, has at least one time slot that's in the middle of the night. Chennai has only one slot that I'd consider not in the middle of the night. Is that OK?

**Comment by mcollina** [comment]
I had a chat with @Trott about this. Unfortunately, we are truly global group and this means __it is fine if we join only 1 every 3 meetings__, with some incovenience to join 2 over 3.
The current criteria are exactly how @fhinkel  frames them in https://github.com/nodejs/TSC/issues/444#issuecomment-352727932: one meeting in working hours.

This means it is fine if we are __never__ all in the same room. If we want to optimize for maximum attendance it's a completely different metric.

Anyway, I see more people have updated, so it's time for an update @Trott.

**Comment by Trott** [comment]
> __it is fine if we join only 1 every 3 meetings__

Er...I think you mean it is fine if we **miss** 1 out of every 3 meetings.... At least, that's been what I've been using as a rule of thumb....

**Comment by Trott** [comment]
Re-running with updated data changes the results significantly. UTC times proposed are now, 12:00, 20:00, and 22:00. 

This is the same as our current times except that the current 17:00 UTC meeting is shifted three hours later to 20:00 UTC.

I do like that it's a minor tweak to our current schedule rather than a completely different schedule.

**Comment by ChALkeR** [comment]
LGTM as long as that's the optimal result.

I also think that the algorithm itself that selects the optimal dates (i.e. the code) should live inside this (or some other nodejs/*) repo, so that it could potentially be updated using the regular process. That should not block this issue — that's a separate one ;-).

**Comment by jasnell** [comment]
Since I see you thumbs'd down my comment @Trott, let me clarify... the proposed new schedule would work for me, but I have a personal preference on keeping the current one as the times are actually far more convenient for me. I certainly don't want to block changing the schedule tho if it makes it more convenient for others.

(and just as a side note, using the thumb's down when someone expresses their personal preference when feedback is explicitly being asked for does little to encourage those folks to offer their input in the future).

**Comment by Trott** [comment]
> (and just as a side note, using the thumb's down when someone expresses their personal preference when feedback is explicitly being asked for does little to encourage those folks to offer their input in the future).

@jasnell That's fair. Sorry about that. In the future, I'll respond instead with comments along the lines of "This comment needs more information to be useful/actionable. Can you elaborate?".

I had been thinking that I was OK with using thumbs-down when "established" folks leave these sorts of "+1" or "-1" comments. Clearly, that was a miscalculation. In retrospect, I failed to consider that I myself am "established" and therefore a thumbs down from me is likely to be more disconcerting than a thumbs-down from a GitHub handle you've never heard of before. And the "established" thing aside, there's probably also something more troubling about a thumbs-down from someone you know than someone you don't.

I'll go back to basically never using thumbs-down (except for when specified for voting and on egregiously bad posts such as trolling behavior), which was pretty much what I had been doing.

Thanks for the feedback.

**Comment by Trott** [comment]
Because the proposal has changed, I'm going to close this and open a new issue.
