### ISSUE TITLE
TSC Meeting 2/14/2018

### ISSUE THREAD

**Issue by fhinkel** [nodejs/TSC#487]
I can't chair the 2/14 meeting because I'm traveling. If we move it 2 hours back, I can participate. 

We cancelled the last meeting that was at this time slot, there were just not enough people there. Can we reconsider moving this meeting time? (I know, we talked about this 2 month ago...)

**Comment by mcollina** [comment]
I will be traveling as well and unable to join. I propose to skip.

**Comment by Trott** [comment]
I will also be very unlikely to make this one. I would love to look at moving the meeting times again since we have added a member and removed another member since the last time, so that's likely to change things.

@gibfahn Can you fill out your column in the spreadsheet? I sent the URL and some explanatory text in email to your gmail account. Let me know if you have any questions!

**Comment by rvagg** [comment]
I'll be on Pacific time for this so won't be attending either.

**Comment by mhdawson** [comment]
As usual, I won't be able to make it.

**Comment by cjihrig** [comment]
I'm also unable to attend.

**Comment by Fishrock123** [comment]
Is this the early time slot? If so, I can’t make it.

Otherwise, I could chair / stream (but not take notes)

**Comment by mhdawson** [comment]
@Fishrock123 it is the early slot.

**Comment by Fishrock123** [comment]
Ah, yeah I won't be able to attend.

**Comment by mhdawson** [comment]
Closing, meeting was canceled.
