### ISSUE TITLE
What does "success" look like

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#493]
Hey All.

At the moment it does not seem like we have a good definition of what a "successful" TSC member looks like. This ambiguity makes it hard to self-assess and effects our ability to nominate candidates who are likely to be successful.

I think that we should brainstorm, and likely document, what the criteria for success are.

**Comment by mhdawson** [comment]
Sounds reasonable to me.  

Two things I'd start the list off with is participation in one or more working groups and/or strategic initiatives and consistent involvement in the TSC discussions through one or more of email/github/meetings.  

This may not quite be the right way to document as we may want to document more through outcomes versus actions, but we can probably re-write them with that viewpoint if necessary.

**Comment by Trott** [comment]
@MylesBorins Are you talking about criteria for a TSC nominee or a member? First sentence suggests member and @mhdawson's reply seems to assume that (since there's no way for someone else to have consistent involvement in TSC email threads). But your second sentence seems to suggest nominees.

For nominees, my sole criteria: A track record of *constructive* engagement in the project.

**Comment by Trott** [comment]
For nominees, my sole criterion: A track record of constructive engagement in the project.

(Felt like that warranted being in a comment by itself. Sorry for the repetition.)

**Comment by MylesBorins** [comment]
@Trott Both

I think that by defining a successful TSC member we can help to better determine what makes a good candidate

**Comment by MylesBorins** [comment]
Closing for now, we can revisit this another time
