### ISSUE TITLE
List of things to do for new TSC members

### ISSUE THREAD

**Issue by targos** [nodejs/TSC#524]
I couldn't find a document listing things that we have to do when we welcome a new TSC member (and undo when a someone steps down). Should we have one in this repo?

Things that I can think of:
- Add them to the `@nodejs/tsc` and `@nodejs/security-tsc` teams
- Make them an owner of the `nodejs` org
- Invite them to the `nodejs-private` org (as an owner)
- Add them to the `@nodejs-private/security-tsc` team
- Add them to the `tsc` mailing list

Anything else?

**Comment by richardlau** [comment]
Update https://github.com/nodejs/node/blob/master/README.md#current-project-team-members.

**Comment by fhinkel** [comment]
In which document should this go? With that info, this would make a good first issue for a new contributor (though it's tsc and not node).

**Comment by mhdawson** [comment]
@fhinkel how about TSC/BasePolicies/OnboardingProcess.md ?

**Comment by Trott** [comment]
If I understand correctly, I don't think it should go in BasePolicies. Those are for boilerplate for other projects (not that we do the "other projects" thing much or at all anymore, but still). 

I think it can go in an onboarding.md in this repo to mirror the onboarding.md in the main repo. (We don't have a docs directory the way the main repo does but that's because this whole repo is basically a docs repo so our docs just end up right in the top directory.)

**Comment by mhdawson** [comment]
@Trott having onboarding.md in this repo sounds good to me.

**Comment by TimothyGu** [comment]
Also need to add the person to https://github.com/mhdawson/create-node-meeting-artifacts/blob/master/templates/invited_tsc.
