### ISSUE TITLE
Transparency vs Communication

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#55]
There's an interesting problem we seem to have.

As the level of transparency is quite high in the TSC and in various projects the participants feel as though what they are doing is easily understandable to external observers. In reality, the level of understanding of what is going on in these projects is on the decline.

Part of this decline is because the volume of work has _rapidly_ increased. Anyone who's unlucky enough to be on the owners list and auto-follows every new repo knows how dramatic this has been.

Another reason is that all the transparency we've imposed has increased the shared understanding between the _existing_ participants and it gets harder and harder to reconcile that with the external understanding.

I'd like to discuss ways in which we might do a better job of improving this. Whether it's regular "state of the union" reports from different projects, better foundation wide metrics, etc.

**Comment by jasnell** [comment]
There's an additional angle to this that I've been stewing on for a while -- currently, GitHub does not provide a good mechanism for doing broadcast type messages to the collaborators. We've ended up having to use meta issues in the tracker which are clumsy at best. I've been wondering if it would be possible to carve off a section of the nodejs.org site to allow each WG that so desires to have their own blog channel. This can be promoted first and foremost as a way for the WG to communicate with the broader collaborator community for exactly the kind of thing you're suggesting above. It would be informal and optional (e.g. no apache incubator style mandatory monthly report type of thing).

**Comment by nebrius** [comment]
> I've been wondering if it would be possible to carve off a section of the nodejs.org site to allow each WG that so desires to have their own blog channel. This can be promoted first and foremost as a way for the WG to communicate with the broader collaborator community for exactly the kind of thing you're suggesting above. It would be informal and optional (e.g. no apache incubator style mandatory monthly report type of thing).

I think this is a great idea! One possible angle is to have WGs/etc take meeting minutes and turn that into a more digestible blog post. I think that would reduce the barrier to entry for writing these posts, since topics are laid out in advance.

Part of me is thinking it might be a good idea to have one WG/whoever sort of prototype this with, say, a wordpress-hosted or medium blog or something before getting the infrastructure set up on the node.js site. Thoughts?

**Comment by mikeal** [comment]
The code to add this to our site could be done in less than an hour. The real question is where is the content going to come from. Do we expect these groups to write up docs *in addition* to what they are already doing? Is there anything they are already producing or that we could automate to help them write produce this on a more regular basis?

**Comment by jasnell** [comment]
The content could include minute notes (copied over from the shared google docs) so that those don't have to be checked into the code repositories, announcements such as calls for participation, etc. It would really be up to each WG to figure out how to make use of it. Generally, however, it would be for anything that the WGs want to use it for. Automation tools could help (a tool that pulls down a google doc and automatically converts it into markdown for a blog post would be quite handy).

**Comment by williamkapke** [comment]
IMHO, blog posts are great for google search results but not so great for distributing announcements/news. Maaaaybe if it was a blog post + opt-in mailing list it would be better. I don't think I want 20 mailing lists though. Github notifications work out well for me... but probably not for others.

What Projects/Committees/Working Groups seems to be lacking, is something like "product managers" but I hate to use that title because it tends to give people the idea of a "product owner"... which implies control of the product .... which is completely incorrect.

Words like a `wrangler`, `organizer`, or `communicator` might be more appropriate. Whatever it is called, it's a role that monitors the action and facilitates communication. It requires a great communication and networking skills. @mikeal, it seems like you have been doing TONs of this. Maybe much of it on your own? The problem with a type of role like this is that it is pretty intense and requires a significant (unpaid) commitment and has a really harsh rampup time (because there's sooo much backstory to learn). I was pretty hopeful for [code-and-learn](https://github.com/nodejs/code-and-learn) but [I'm not sure if that will pan out](https://github.com/nodejs/code-and-learn/issues/54). It *seems* like a good start to getting people past SOME of the crazy learning curve. It will all hinge on how much commitment it will get from contributors- and it has been silent for a 1/2 year now.

I don't think it is the best idea for people that volunteered to contribute code to be (kinda) expected to produce communications. I know **many** amazing developers that do not have communication skills. 

>  the volume of work has rapidly increased

Yes, yes it has. Is this one of those "good problems to have"..? I guess so. But I will confirm that it is getting harder and harder to get involved because the backstory is either really hard to find, lost in multiple threads with hundred(s) of messages, or held offline within the group of contributors. The velocity **is** increasing and the communication **is not**.

Thanks for bringing this up. It would be nice if it was added to a tsc-agenda and placed on a high priority.

**Comment by mikeal** [comment]
> Thanks for bringing this up. It would be nice if it was added to a tsc-agenda and placed on a high priority.

This is factoring into the flatten proposal. I'm also writing some code that should give us the big picture in terms of org activity metrics.

**Comment by jasnell** [comment]
Closing as there's been no further discussion
