### ISSUE TITLE
Ask TSC members - Community Corner TSC panel

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#602]
At the Node+JS Interactive Community Corner, the following TSC members will answer some questions!

* Micheal Dawson (@mhdawson)
* James Snell (@jasnell)
* Anatoli Papirovski (@apapirovski)
* Anna Henningsen (@addaleax)
* Myles Borins (@MylesBorins)

The TSC panel will happen at the Community Corner on Wednesday 10th of October between 4:10pm and 4:40pm. See you all in Vancouver!

Have you got any specific question for the TSC members? Just reply to this issue.

**Comment by mcollina** [comment]
Here are the questions that I am planning to ask:

1. We often say that Node.js has no roadmap. What does that means in practice?

2. How are security vulnerabilities reported?

3. Node.js is getting bigger over time. Is the "small core" principle gone?

---

Are here any more questions that we would like to answer?

**Comment by mhdawson** [comment]
How about 

4. What are some of the key areas that you think we should focus on in Node.js over the next years?

**Comment by mcollina** [comment]
5. How do I become a member of the TSC?

**Comment by LRagji** [comment]
Not sure if this is still active, as i see it closed a week ago but still here is my question;

console.log() is supposed to be blocking operation is a big of a taboo to use it in prod systems, are there any chances that we have a enhancement coming up for this like writing to mem buff over stdout or stderr to avoid blocking calls?, as console.log seems to be the like the first thing any js developer picks up as first level of debugging and this becomes a pretty much of a trip wire for prod.

**Comment by joyeecheung** [comment]
@LRagji Can you open an issue in https://github.com/nodejs/node/issues ? For one, this is not something whose answer has to come from the TSC - any human being can create an enhancement either as a proposal or as a PR in the core repo.

**Comment by LRagji** [comment]
@joyeecheung This was more of a question for roadmap cause it seem as an identified issue but i dont see anyone working on it so is there anything ln the roadmap for future..? i understand enhancement and PRs

**Comment by joyeecheung** [comment]
@LRagji As I understand, the project does not have a roadmap and that is intentional - whether we should revisit the no-roadmap-policy can be discussed in a separate issue in this repo, I guess.

**Comment by Trott** [comment]
One of the unfortunate side effects of a panel like this is that it perpetuates the impression that the TSC steers the project. While it's true that the TSC is empowered to do things like that should it so choose, in practice, the project is steered by its contributors, particularly Collaborators. There is no official roadmap and the TSC does not decide what features are implemented. (The TSC *does* track so-called "strategic initiatives" but that would not be something relevant to this particular question.) When there *was* a roadmap, it was always horribly out-of-date and never consulted.

One of the things I said during the panel discussion was that the TSC membership is not (or should not be) a sign of power or even status. We are (or should be) more like custodians or stewards. Yeah, we keep things from going off the rails, but we don't direct things, at least not as a group. (Certainly, some of us do long-term planning, but only in the areas that are of interest to us as individuals. No one does it comprehensively, which is intentional.)

For these reasons, as @joyeecheung noted, the right place to ask/discuss is in the main repo.

**Comment by mcollina** [comment]
From an event perspective, the panel has been a success: there was a sizable crowd having a good time and learning something meaningful on how we work. I stand by the decision to have one.

I think we should put the description of “no official roadmap” somewhere in the project repo. This is something that very few people know about (unfortunately).

(Also, one of the reasons to have such a panel is to share this typo of info).

**Comment by Trott** [comment]
> From an event perspective, the panel has been a success: there was a sizable crowd having a good time and learning something meaningful on how we work. I stand by the decision to have one.

Oh, yes, there was definitely an audience. It was the best-attended session in the Community Corner that I witnessed. Didn't mean to imply that it was a failure.

**Comment by mcollina** [comment]
@Trott also @MylesBorins helped a lot in actually getting everybody up :).

**Comment by Trott** [comment]
> From an event perspective, the panel has been a success: there was a sizable crowd having a good time and learning something meaningful on how we work. I stand by the decision to have one.

Oh, yes, there was definitely an audience. It was the best-attended session in the Community Corner that I witnessed. Didn't mean to imply that it was a failure.

And since I listed what I thought was a downside, here's an upside: Things like this humanize the TSC and makes it clear that we're Just A Bunch Of People and not some kind of organized puppeteers for the project or something like that.

If I were to suggest one change, it would be to take a page from the Google I/O events and call this something like a Fireside Chat or whatever rather than a panel. A panel suggests a bunch of people on a stage, and one of the cool things about having this in the Community Corner is that we *weren't* on a stage. Sure, we had a microphone, but the format hopefully encourages a dialogue, and the lack of an elevated stage helped, in my opinion.

Also, I thought the way you (@mcollina) insisted that all the TSC members who were in the audience participate even though most of us hadn't planned on it...that was great. By inviting everyone up, it made it possible for people who didn't have a platform elsewhere at the conference to have a voice. Some TSC members do public speaking more than others, but it's often the less-heard voices that have the most interesting things to say.
