### ISSUE TITLE
Node.js "Users" feedback

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#66]
I'm not sure if the TSC or CTC is the right forum for this but I'll start here. 

I had a discussion with Yunong Xiao from Netflix today around the concern that we may not have enough input/representation from companies using Node.js as part of their application deployments.   It seems like there is no obvious channel for them to provide this feedback and they are not well represented directly on the TSC or CTC at this point (as opposed to companies involved in building tools/products for Node.js which are well represented).

I think that in the past there have been discussions around a "user council" and/or other ways of getting input from companies like netflix which are depending on Node.js.  

I'm volunteering to push this forward and would like feedback from the TSC in terms of if there are any efforts already underway that I'm not aware of and agreement that me pushing it forward makes sense.  Of the top of my head I think a regular meeting that includes interested companies where they can raise concerns, discuss common experiences, provide feedback to the TSC/CTC and get updates on the direction we are planning would make sense.

**Comment by williamkapke** [comment]
I have a personal vested interest in the success of Netflix- but I am -1 in the idea of a "user council" as described. The Node.js Foundation already **looks** heavily guided by large companies via the Membership structure. There are 2 Individual slots there that where just filled where companies **could** have tried to fill with reps for their company (it was a minor concern of mine). 

Companies have equal opportunity to open issues in the various repos, tag them for committee review, and watch/participate in the live meetings. If this approach isn't working, please highlight the issues with them. 

Netflix, in particular, already has representation on TC39! Participating here is a welcome addition- but I don't feel we should carve out something special for them or other companies and risk further alienating the community.

**Comment by cjihrig** [comment]
Have they tried the issue tracker and been unsuccessful?

**Comment by rvagg** [comment]
Well said @williamkapke.

In my discussions with Netflix I've also encouraged them to invest more in people time around core if they want their concerns better represented. Our governance (and therefore guidance) model dictates that the people that invest time and resources get to guide the project. If an individual, group or company feels unrepresented then then they should step up and get involved. We willingly hand decision-making power to people who invest, you can see this through the slow evolution of the Collaborators group and the CTC group. Working Groups also have similar structures where those who put in the work get to guide what is done.

If we are not making those opportunities clear or the entry-point for them obvious then we should do better. I'm a **very strong** -1 on forming any kind of advisory body because there's no way it'll be representative of users, in any sector, users, companies, whatever, Node is just too big for this. Even talking about "community" is stupid because it's such a massive user-base that any view of the users can only be narrow and short-sighted.

**The way we solve for this is with open governance. If you care about Node, then invest in it, if you invest in it then you get to hold the steering wheel. Simple as that.** Buy influence by investing in the project, we're happy to share it if you're going to step up. It's certainly not going to be perfect but it's better than any alternative I'm aware of to date.

I'd also like to see Netflix step up and join the Foundation tbh, contributing monetary resources is a step in the right direction at least. It doesn't necessarily buy any power (although a Platinum would buy a seat on the board which would give a pretty good level of influence over non-technical matters) but it's an easier first-step for a company with enough resources to do so. I'm also happy to keep an eye out for potential hires for companies like Netflix that want to hire-to-contribute, but the problem faced by many companies doing this is that they almost never want to hire a 100% open source dev, which rules out a number of candidates who have certain ideological inclinations or preferences.

With regard to "feedback" more generally. This is something that we've actively tried to do in the LTS working group. We see this as being much more focused on the needs of big companies, like Netflix, and are always looking for ways to connect and understand their perspective. However, it still comes down to the same governance model. LTS is basically me and a couple of IBM folks and we're representing the interests of our companies, our companies customers and our own personal opinions (also heavily influenced by our commercial interactions and understanding of the needs of the various enterprises we have contact with). I'd absolutely love to have more help on the LTS WG but it's apparently not an interesting place for individuals to invest their time and to date we haven't had much interest from companies outside of the service-provider space.

**Comment by mhdawson** [comment]
Hmm, I may have started on the wrong foot by suggesting a possible approach which I thought has been previously discussed.  

My key interest is to ensure that we understand the needs of all of the different types of users.  If we think we already have that well covered then I guess there would not be anything to discuss.  Otherwise, it could make sense to discuss how we improve coverage.

**Comment by Fishrock123** [comment]
I think this is mostly a cultural problem with some of our user companies that our governance model more or less stands against. If you suffer from "not invented here" syndrome for whatever reason, we probably should not cater to that. Doing regular and routine issue and feedback in private hurts everyone else.

**Comment by mikeal** [comment]
I don't disagree with anything that has been said but I will note that just as an advisory group would have a selection bias the "gets involved with core" group also has, and will always have, a selection bias as well.

Node.js is so widely adopted that the view any one person or group has of it is incomplete. Every time I've been able to get data in order to guide a decision my assumptions about what the data was going to say were wrong.

If we're looking to do some kind of roadmaping or other directional work the best approach would be to let whatever data we can gather guide that work rather than whoever happens to show up to be involved.

**Comment by williamkapke** [comment]
> let whatever data we can gather guide that work rather than whoever happens to show up to be involved

HEY- that's how Netflix does things!... wouldn't it be great if they brought that expertise to the project(s)!? :D 

<sub>Although: They might insist on AB testing `Buffer.alloc()` vs `Buffer.unsafe()` before approving the PR  :P</sub>

**Comment by jasnell** [comment]
Closing given that there's been no further discussion in nearly a year
