### ISSUE TITLE
Is it possible to send from iojs.org email addresses?

### ISSUE THREAD

**Issue by sam-github** [nodejs/TSC#684]
Is it possible to send email from an iojs.org address? Mitre uses that as an indication of authenticity, and a CVE request by @rvagg  got put in the slow-queue because it wasn't from our org.

Alternatively, I might be able to get personal email addresses (multiple of them) setup with mitre as our CVE contacts.

@rvagg, why aren't you in nodejs/email to get emails from mitre? Is it because you didn't want to be? It seem that you should be, though I don't mind always replying with "yes, he's allowed" when they send me the questions.

cc: @mhdawson @bnoordhuis @vdeturckheim  (the other two contacts in nodejs/email)

See: https://github.com/nodejs/email/blob/4d495d887214aa9f0ce99e5dedbfe68f04162e93/iojs.org/aliases.json#L179-L184

```
From: Cherwell Service Management <CSMSYSTEM@mitre.org>
To: Rod Vagg <r@va.gg>, Sam Roberts <vieuxtech@gmail.com>, CVE Request <CVE-Request@mitre.org>
CC: "cve-mitre-contact@iojs.org" <cve-mitre-contact@iojs.org>
Subject: RE: [EXT] Re: Regarding service request 649319
Date: Mon, 1 Apr 2019 14:45:53 +0000
Message-ID: <MW2PR0901MB23950408537B0A460BA4C9DBB1550@MW2PR0901MB2395.namprd09.prod.outlook.com>

Hi Rod,

Thank you for asking. We are still working on the backlog, but the reason t=
his request had a 30+ day delay was because we didn't recognize the email o=
f the requestor (r@va.gg) and, thus, was sent to the non-cna ticket pool. I=
t would be best that request made from Node.js came from an iojs.org email =
to eliminate confusion and avoid something like this to occur in the near f=
uture. Does that make sense?

Do not hesitate to contact the CVE Team by replying to this email if you ha=
ve any questions, or to provide more details.

Please do not change the subject line, which allows us to effectively track=
 your request.



Cristina Padro

CVE Assignment Team

202 Burlington Road, Bedford, MA 01730 USA

[A PGP key is available for encrypted communications at

http://cve.mitre.org/cve/request_id.html]



-----Original Message-----

Priority: Normal

From: (Rod Vagg)  r@va.gg

Sent: 3/28/2019

To: (Sam Roberts) vieuxtech@gmail.com; (CVE Request) CVE-Request@mitre.org

Cc: (cve-mitre-contact@iojs.org) cve-mitre-contact@iojs.org

Subject: [EXT] Re: Regarding service request 649319



Sam: No, I don't. You, Michael and Ben according to nodejs/email.



Christina: this is exactly a month since I sent in the request. Does that m=
ean there's a 30-day delay on publishing? When we send in notifications the=
y are usually on the day of publication on our end so immediate publication=
 by Mitre would be appropriate. Do we need to make that clear somewhere or =
adjust our processes in some way?



Cheers,

 -- Rod





On Fri, 29 Mar 2019, at 3:45 AM, Sam Roberts wrote:

Yes, it is.



Rod, do you get these emails via the @iojs.org address? Maybe I don't

have to authorize them, because you are?





On Thu, Mar 28, 2019 at 8:52 AM CVE Request <CVE-Request@mitre.org> wrote:

>

> Hi,

>

> A requestor (r@va.gg) is requesting the CVE Team to publish information f=
or CVE-2019-5737. Is his request on behalf of Node.js CNA?

>

> Thanks,

>

> Do not hesitate to contact the CVE Team by replying to this email if you =
have any questions, or to provide more details.

> Please do not change the subject line, which allows us to effectively tra=
ck your request.

>

> Cristina Padro

> CVE Assignment Team

> 202 Burlington Road, Bedford, MA 01730 USA

> [A PGP key is available for encrypted communications at

> http://cve.mitre.org/cve/request_id.html]

>

> {CMI: MCID3132332}
```

**Comment by rvagg** [comment]
> Is it possible to send email from an iojs.org address

Yes, you just need the alias working and then your email program and smtp service need to be set up to send as that. If using gmail then it's just a matter of gmail checking that you can receive those emails. I'm not aware of anyone sending anything _as_ iojs.org at the moment, however, and I also don't think it's necessary here. See below.

> @rvagg, why aren't you in nodejs/email to get emails from mitre

I don't know, it never came up? I wasn't involved in setting up the CVE authority stuff so I don't think I've needed to be.

So the email conversation continue on from what has been copied here and I suggested that we just change our process to use a cve...@iojs.org address when submitting to mitre. It's only a web form and I normally just stick my address in, but as you can see that's a problem. Since cve-mitre-contact@iojs.org is what Mitre has for us we could just use that. All it means is:

1. Update https://github.com/nodejs/security-wg/blob/master/processes/cve_management_process.md#cve-management-process-for-nodejs-vulnerabilities to insert a note about using that address on the form.
2. Anyone submitting to Mitre should be added to that list (arguably this isn't strictly necessary but it might streamline things).

**Comment by mhdawson** [comment]
@sam-github if you can update our security release process with @rvagg's suggestion that would let us close this out.

**Comment by sam-github** [comment]
- https://github.com/nodejs/email/pull/137
- https://github.com/nodejs/security-wg/pull/509
