### ISSUE TITLE
New collaborator roles

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#712]
This week GitHub announced two new collaborator roles: triage and maintainer. As far as I know, these have not yet been enabled for our organization but they are coming and we should decide how to use them, if at all.

```
Triage (beta): Recommended for contributors who need to proactively manage issues and pull requests without write access

Maintain (beta): Recommended for project managers who need to manage the repository without access to sensitive or destructive actions
```

The Maintain roles includes all of the permissions of the write role and adds: editing repo description, managing topics, enabling/disabling wikis, and managing project boards. As such, I don't think it provides enough additional benefit for us to make use of it.

The Triage role adds the ability to label, close, or assign issues without giving full write access to the repo. This one, I think will be super useful and we should consider using it. We just need to determine how.

**Comment by targos** [comment]
The permissions are enabled for the `nodejs` org:
![image](https://user-images.githubusercontent.com/2352663/58333124-0e53f980-7e3d-11e9-89f7-002b678ba458.png)

**Comment by richardlau** [comment]
I'd suggest Triage could be helpful for projects that have restricted write access but could use help managing issues, e.g. build? cc @nodejs/build

**Comment by jasnell** [comment]
Ah, nice, that's new then. They weren't there yesterday when I checked.

**Comment by cjihrig** [comment]
Maybe we could create a new role in the project for people that are interested in helping triage issues, but not necessarily committing code. I can't remember specific examples off the top of my head, but I do recall people requesting that ability in the past. Or maybe emeriti could retain triage permissions.

**Comment by sam-github** [comment]
I remember one person who was reluctant to become a collaborator, despite doing lots of useful work around docs and issues, out of fear of inadvertently messing something up. The triage role might have helped with that, but that person accepted collab nomination eventually.

It's not clear to me that the triage role is useful to us. Managing another flavour of collab status seems overly bureaucratic. If we trust people to close issues I think we can trust them to not push code if they don't intend to, or to not use the github "edit in place" UI to modify code. Both of which would be reversible even if they did do it. I think the node.js collab spirit is more one of trusting in people to not be malicious, and knowing that we can fix things if a mistake is made (which is relatively infrequent, though I have personally rolled back master once _blush_).

The only admin capability I ever envied was the ability to move issues between repos, specifically to the help repo. If that could be enabled for all collaborators, that would be pretty useful, IMO. Right now, I think only TSC (aka admin) members can do that.

Myself, looking at the new roles, I'd be more tempted to use the new "Maintain" role by giving it to all collaborators, so that more people can help out with github maintenance.

**Comment by targos** [comment]
> The only admin capability I ever envied was the ability to move issues between repos, specifically to the help repo. If that could be enabled for all collaborators, that would be pretty useful, IMO. Right now, I think only TSC (aka admin) members can do that.

Maybe if someone has the "Maintain" role for both `nodejs/node` and `nodejs/help` they are able to move issues? That would be awesome.

**Comment by jasnell** [comment]
I believe moving issues is considered to be a "destructive" action and therefore limited to org owners.

**Comment by targos** [comment]
Well, now everyone with write access to two repositories can move issues between them 🎉 
https://github.blog/changelog/2019-05-29-improvements-to-issue-transfer-permissions/

**Comment by mhdawson** [comment]
@jasnell  is there anything more we should do on this?

**Comment by Trott** [comment]
I don't think there's anything to do here. Repositories that want/need this can use it or open requests in the admin repo to have an org Owner handle it for them. I think our current situation in the main repo is fine, at least for now. Anyone that has a proposal to change it can open an issue for discussion either here or in the main node repo.

Closing, but feel free to comment or re-open if I'm being hasty with the "close" button.
