### ISSUE TITLE
One of the new tsc times conflicts with long standing modules team time

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#730]
Hey All,

I just noticed that we have a conflict with meeting next wednesday. It overlaps with the long standing time of the modules team.

This has us now at 2 of our new times having a conflict (CPC meeting and Module meeting). Should we re-evaluate the times?

**Comment by Trott** [comment]
Unless there's a conflict for the Zoom account or something like that such that two meetings can not take place at the same time, I think conflicts are fine. People who have the conflicts should note it in the spreadsheet appropriately (put a 0 if you will choose modules over TSC every time, but more like a 1 if it's modules over TSC most of the time, etc.) and that's how we can determine if the meeting time should be changed. I definitely do not think we should black out any times because that biases the algorithm to favor some people's schedules over others. (Also, conflicts can be healthy in some situations if they cause people who may be stretched too thin to choose to do one less thing and make space for others. Not saying that's happening here. Just noting a hypothetical.)

**Comment by mhdawson** [comment]
@Trott currently we can't host or stream 2 webinars at the same time so it is a problem.  

In the short term what I suggest is that we swap the times for the meetings next week and the week after which would avoid the conflicts.

**Comment by Trott** [comment]
> In the short term what I suggest is that we swap the times for the meetings next week and the week after which would avoid the conflicts.

+1 to that as a short-term solution. You'd probably do this anyway, but I'd say let's email TSC ane/or use the team discussion board to let people know about the change so everyone has plenty of notice to update their personal calendars or whatever.

**Comment by mhdawson** [comment]
I'll send an email

**Comment by mhdawson** [comment]
Time has been changed. Closing
