### ISSUE TITLE
the nodejs/npm team doesn't contain members who maintain deps/npm

### ISSUE THREAD

**Issue by sam-github** [nodejs/TSC#736]
I'd like it to be useful, to list members who maintain deps/npm, I think that's its intention.

@nodejs/npm - do you all want to be on this team, https://github.com/orgs/nodejs/teams/npm/members, currently this is @bcoe and @iarna 

https://github.com/nodejs/node/commits/master/deps/npm suggests to me that these users should be on the team: @isaacs @jkunkee @zkat @ljharb 

This came up in https://github.com/nodejs/build/issues/1873#issuecomment-514715194

I'd hoped that members of the nodejs/npm team would be the ones using the node-test-npm job (or not using it, in which case it can be deleted).

**Comment by ljharb** [comment]
I have slightly contributed and frequently commented on npm projects, and once I've upgraded npm in node, so I'm happy to be on the team, but it's also not particularly necessary ¯\\\_(ツ)_/¯

**Comment by mhdawson** [comment]
@ahmadnassri could you help to get the list of people who should be on the list updated?

**Comment by mhdawson** [comment]
@isaacs, @ahmadnassri  any thoughts on who should be in this team?

**Comment by Trott** [comment]
It probably makes sense to add @claudiahdz (if they express willingness and/or npm says "do it") and call it a day for now.

There are currently two members: @isaacs (who I assume should stay on there) and @iarna who (because I asked) would like to stay on the GitHub team.

I think of the team as "people who can make highly-informed and intelligent comments on npm CLI issues" so I don't think it needs to be (or even should be) exclusively current employees of npm Inc.

**Comment by mhdawson** [comment]
@sam-github do you want to update the list as suggested and then close out this issue?

**Comment by sam-github** [comment]
OK. The current list contains the two who are active, @isaacs and @iarna, no one else requested membership. Closing.
