### ISSUE TITLE
Proposal: Add @williamkapke as a committer in this repo

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#74]
Right now the only committers in this repo are TSC members and org owners.

The problem is that this repo is mostly for transparency and documentation purposes and to date the people most involved in TSC work aren't great at documenting and explaining that to the rest of the world.

William has been logging issues and fixing/cleaning stuff up a lot. If this were any other repo he'd be added as a committer but the TSC hasn't instituted a similar process for this repo, which is an oversight.

**Comment by williamkapke** [comment]
Neeto- I actually enjoy trying to make process & documentation digestible/useable/approachable.
I'm happy to help :+1:

**Comment by jasnell** [comment]
SGTM

**Comment by nebrius** [comment]
I like this idea...we have a similar setup growing in the inclusivity WG, where it's mostly members, but a few other (really awesome) people that contribute without being members

**Comment by rvagg** [comment]
+1 I've enjoyed watching @williamkapke engage and try and improve some of the administrative side of what we do, it's a weak spot for us so additional help is a good thing!

**Comment by williamkapke** [comment]
Thanks everyone for showing appreciation of my efforts.

The Node.js Foundation has made a commitment to the community to be [open and transparent](https://github.com/nodejs/TSC/blob/master/TSC-Charter.md#section-1-guiding-principle). From closely observing the activity in the Node.js repos and drudging through any documentation/videos I can find, everyone seems to really want that. It is hard and, debatably, less cool & rewarding as contributing code.

I have been heavily involved in Node.js since 0.4 and have followed it very closely since. For many years, my attempts to participate were harshly shut down. I am very active in local community events in SF/Oakland/LA and have found this to be the perception of _almost_ everyone that I've spoken to (easily hundreds of developers).

Some of you presented at Node Interactive in Portland showed a strong effort to convince people that Node.js, under the Node.js Foundation, IS very open and you wanted people to come help out. So, I decided to give it another go.

I've found the barrier to entry is very high, you're very aware of it, and are working to improve it. *I* believe a good portion of it is due to information being unintentionally hard to find or just unavailable.

The [Guiding Principles](https://github.com/nodejs/TSC/blob/master/TSC-Charter.md#section-1-guiding-principle) ends with:
> must not merely be open, but also easily visible to outsiders.

I hope a good part of _my_ contribution will be towards those last 4 words.

**Comment by rvagg** [comment]
Brilliant @williamkapke! This is exactly in line with what we are trying to do and I believe you're seeing that we are having trouble simply because there's so much to do but we absolutely want to be operating in a spirit of openness and transparency and welcome both critique of our efforts and also the energies of others who are willing to give of their time and resources.

We did discuss this issue briefly in our meeting today (perhaps it was in the private section, I don't recall) and everyone was enthusiastic about the idea of giving you write access to this repo so I'll go and get that done right now.

**Comment by mikeal** [comment]
Thanks for that post @williamkapke, you're touching on what I brought up [here](https://github.com/nodejs/TSC/issues/55) regarding the difference between transparency and communication. We're very transparent but as things have gotten more complicated the communication of what is going has gotten less and less accessible. You've already done some great work making that better and I'm excited to see what you do in the future :)
