### ISSUE TITLE
Early access to security releases

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#786]
Currently we don't offer early access to security releases, which means whenever we do a new release everyone downstream is affected by a zero day. I'd love to see us introduce some sort of early access program so that certain organizations (e.g. cloud providers) can get early access to releases.

Envoy has a program [documented here](https://github.com/envoyproxy/envoy/blob/master/SECURITY.md)

Thoughts?

**Comment by tniessen** [comment]
I think we brought up the idea in a discussion at Node.js Interactive 2017 and the main problem was: How do we decide who has access and who doesn't? There were concerns that it might put small companies at a disadvantage.

**Comment by MylesBorins** [comment]
Envoy outlines how they do it here 

https://github.com/envoyproxy/envoy/blob/master/SECURITY.md#membership-criteria

```

### Membership Criteria

To be eligible for the cncf-envoy-distributors-announce mailing list, your
distribution should:

1. Be either:
   1. An actively maintained distribution of Envoy components. An example is
      "SuperAwesomeLinuxDistro" which offers Envoy pre-built packages. Another
      example is "SuperAwesomeServiceMesh" which offers a service mesh product
      that includes Envoy as a component.

   OR

   2. Offer Envoy as a publicly available infrastructure or platform service, in
      which the product clearly states (e.g. public documentation, blog posts,
      marketing copy, etc.) that it is built on top of Envoy. E.g.,
      "SuperAwesomeCloudProvider's Envoy as a Service (EaaS)". An infrastructure
      service that uses Envoy for a product but does not publicly say they are
      using Envoy does not qualify. This is essentially IaaS or PaaS, if you use
      Envoy to support a SaaS, e.g. "SuperAwesomeCatVideoService", this does not
      qualify.
2. Have a user or customer base not limited to your own organization. We will use the size
   of the user or customer base as part of the criteria to determine
   eligibility.
3. Have a publicly verifiable track record up to present day of fixing security
   issues.
4. Not be a downstream or rebuild of another distribution.
5. Be a participant and active contributor in the community.
6. Accept the [Embargo Policy](#embargo-policy) that is outlined above. You must
   have a way to privately stage and validate your updates that does not violate
   the embargo.
7. Be willing to [contribute back](#contributing-back) as outlined above.
8. Be able to perform a security release of your product within a two week window from candidate fix
   patch availability.
9. Have someone already on the list vouch for the person requesting membership
   on behalf of your distribution.
10. Nominate an e-mail alias or list for your organization to receive updates. This should not be
    an individual user address, but instead a list that can be maintained by your organization as
    individuals come and go. A good example is envoy-security@seven.com, a bad example is
    acidburn@seven.com. You must accept the invite sent to this address or you will not receive any
    e-mail updates. This e-mail address will be [shared with the Envoy community](#Members).

Note that Envoy maintainers are members of the Envoy security team. [Members of the Envoy security
team](OWNERS.md#envoy-security-team) and the organizations that they represents are implicitly
included in the private distributor list. These organizations do not need to meet the above list of
criteria with the exception of the acceptance of the embargo policy.
```

**Comment by targos** [comment]
What kind of early access do you have in mind? To source code? To built binaries?

**Comment by mhdawson** [comment]
Last time I think there was also not enough of a "demand" in terms of those who were interested and willing to help move the concept forward.

@targos is a good question as well as that will greatly affect the work/overhead/cost.

**Comment by mhdawson** [comment]
@MylesBorins ping to answer @targos's questions in comment: https://github.com/nodejs/TSC/issues/786#issuecomment-561321517

**Comment by sam-github** [comment]
I don't have any problem with a reasonable early access program.

For context, links to previous discussions of this:
- https://github.com/nodejs/security-wg/issues/58
- https://github.com/nodejs/security-wg/issues/68

**Comment by mcollina** [comment]
I'm overall +1 with that as long as whoever gets access to things commits to testing and validation of the fixes: we would like _feedback_ on the fixes before we ship them as well.

**Comment by sam-github** [comment]
@MarshallOfSound  re: https://twitter.com/MarshallOfSound/status/1221529896733724672, you may wish to weigh in on whether this proposal would be useful. cc: @codebytere

**Comment by jasnell** [comment]
+1 on this so long as the list is actively curated and available to the TSC for periodic review.

Just so I understand the guidelines... For a company like NearForm, the majority of our projects are customer projects, which means while we would have early access to security releases, those only become useful for us in testing those with customers, which means we need to be able to turn around and selectively make those early releases available to those specific customers. How do the policy requirements impact that scenario?

**Comment by MylesBorins** [comment]
@jasnell tbh I'm not comfortable with individuals who have early embargo access to selectively disclose, especially to customers. If specific customers would like to have early embargo access it would seem prudent to have them apply for access. We could likely have clear policy allowing organizations that have early access to collaborate which would unblock your specific case of testing with a customer if both nearform and the customer had been individually approved.

**Comment by jasnell** [comment]
Ok good. That's actually the answer I was hoping for :).

**Comment by lirantal** [comment]
I wanted to chime in here and add that after sharing about the upcoming security release in February, several folks, namely the Electron and GraalVM projects, expressed interest in getting more information or some sort of early access to the release before it goes out.

I've pointed both to this thread for further discussion.

**Comment by RoxaBee** [comment]
@lirantal thanks for the pointer! Looking through the Envoy program. Looks pretty reasonable overall. Though is "Be able to perform a security release of your product within a two week window from candidate fix patch availability" a requirement regarding ability or release? No issue with requirement around ability to release in two weeks. I would feel comfortable unconditionally committing to security releases of GraalVM in two weeks for any vulnerability. Maybe could consider score, project release cadence if one exists, etc.

**Comment by sam-github** [comment]
I think the idea with that was that if an entity wants pre-release information, its because they want to release their project that incorporates the node security patches close to simultaneously, rather than node releasing, and they have vulns open while they try to get the node release integrated so they can do their own sec release, which might need timeconsuming acceptance tests.

In my very personal (and not very strong) opinion, I think 2 weeks is on the long end of reasonable. If its not an organizations intention to re-release their node.js based product/platform/whatever within hours, or at least a day or two, of node.js's official release, then its not clear why they need access to the code before we release it to everyone.

**Comment by MarshallOfSound** [comment]
Hey folks, I'm from the Electron Security Working Group.  Thanks for pointing me over here @lirantal Having advance access to the patches for security issues would allow us to avoid the scramble we always go through whenever a node.js security release goes out.  Not all node security issues affect Electron (E.g. things specific to bundled deps don't always apply for things like npm or openssl) but for the ones that do it would be great for us to get early access to at least the patch file.

Whatever the wording is it would have to account for our frameworks/products/systems not being vulnerable or exploitable for a vuln that impacts node generically.

As for timelines, 2 weeks is very easily do-able and if you want to get a faster guarantee we could quite comfortably go down to a few days.  The thing to realize as @sam-github pointed out that we won't just take the patch, throw it on Electron and ship that to the world.  We'll want to run our own CI, run our own analysis on the patch to make sure it won't break Electron in weird ways, etc. and that all takes time.

**Comment by RoxaBee** [comment]
@sam-github GraalVM has a regular cadence for releases including security releases that we publish so customers/partners can plan. If there's a critical vulnerability in node that impacts GraalVM we would do a one off security release so we could release fix at the same time e.g. hours as node. Early access with 2 weeks is fine for that.

For a less severe vulnerability or a vulnerability that may not impact our project we we may choose to include it as part of a regular release v do a one off security release. That may mean we don't release the fix for say 3 weeks but we would still need early access to do the analysis, test, etc. 

I guess the point is downstream projects may not always need to release security fixes at the same time but would still need early access to figure it out.

**Comment by mhdawson** [comment]
@RoxaBee this is off topic but I did not know that GraalVM integrates the Node.js core code.  I'm wondering if there is a reference you can point me to that covers how the code is integrated. I'm also interested in how support for native-addons is provided.

**Comment by RoxaBee** [comment]
@mhdawson don't want to hijack the early access discussion.
The project link is below and please feel free to reach out directly or on the graaljs channel at graalvm.slack.com 
https://github.com/graalvm/graaljs/tree/master/graal-nodejs

**Comment by RoxaBee** [comment]
@lirantal @sam-github  any sense for timing on early access program? anything doable for next week?

**Comment by lirantal** [comment]
Sam can provide more detailed information if possible

**Comment by sam-github** [comment]
@RoxaBee Sorry, I would guess that @MylesBorins would have PR a proposal to the nodejs/TSC repo. ATM, there is no concrete proposal, this is the entire discussion you see here.

How to do this will have to go to the full TSC, but some personal thoughts follow.

Questions to answer:
- What is the criteria?
- What is the application process?
- What, exactly, would "early access" mean?

The current process is documented: https://github.com/nodejs/node/blob/master/doc/guides/security_release_process.md#announcement-one-week-in-advance-of-the-planned-release, its worth reading for anyone wanting early access.

Its not clear where

> early access to security releases

would fit in there.

Its possible to give individuals access to the hackerone vulnerability reports, because it has fine-grained control. Anyone in an 'early access' program group could be added to the vulns to be fixed at any time we decide, and they would see only those vuls reports they have been invited to.

However, the releases themselves don't exist at this moment. I wish I could just show everyone what it looks like in nodejs-private/node-private right now, but of course I can't.

The current state is there is an issue that lists all the vulns to be fixed, and each has a link to the private PRs that fix each issue *for each release line*. The process of integrating those into a release candidate is in progress right now (by @BethGriggs). Once the rc candidate branches exist in private, the next step is that the CI gets locked down so noone by security folks can see it (unfortunate), and the release candidates start building and testing against those branches. This is much like what happens on the public RCs.

All of which is to say that 

1. Actual release candidate tarballs aren't available even to the sec team internally until days before the release happens, so "early access" to them isn't going to be very early.
2. We don't currently have the technical means to open up specific PRs in a private repo to non-security parties. With github, you either have read access to the entire repo, or you don't. This would require a major overhaul of how patches are managed.
3. Adding a group to the vuln reports themselves at some time before the release is technically easy, it just needs a process defined around it (if its what people want).

Its possible, in theory, to radically change the patch management process. To create new private repos, for example, for every sec release, do all the work is there, and then invite an "early access" team to read access some time (how long?) before release, but this is a fair bit of work on a process that's already long and detailed. Its got some pluses from my point of view, besides early access, because it would allow the PRs and the review commentary to be made public to everyone after the release. I like the transparency that would give, but there isn't exactly a legion of people available to work on this, so anything that increases the work can be a problem in itself.

**Comment by MarshallOfSound** [comment]
> We don't currently have the technical means to open up specific PRs in a private repo to non-security parties. With github, you either have read access to the entire repo, or you don't. This would require a major overhaul of how patches are managed.

Have y'all looked into [GitHub Security Advisories](https://help.github.com/en/github/managing-security-vulnerabilities/about-github-security-advisories#about-github-security-advisories).  They use temporary private forks _for each vulnerability_ and you can make many PRs for each vuln that remain private until you disclose.

That would handle your need for per-PR privacy (it's actually how Electron now manages their security fixes).

> Adding a group to the vuln reports themselves at some time before the release is technically easy, it just needs a process defined around it (if its what people want).

This would be helpful but the actual patches are the most helpful thing we could get out of this process.

**Comment by mhdawson** [comment]
Since this has been open for going on 10 months and its not been moved forward I would suggest closing unless we have a champion to move it forward. @MylesBorins what do you think?

**Comment by MylesBorins** [comment]
This is something I'd like to see us do, but don't have time to champion atm. In lieu of anyone else picking it up it would seem reasonable to close this
