### ISSUE TITLE
Move to monthly meeting?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#792]
2 hour meeting with more meaningful agenda.

We can do out of band meetings for important issues.

**Comment by Trott** [comment]
Probably harder to schedule fairly. I'd rather keep weekly meetings on the calendar that get canceled frequently than move to can't-miss monthly meetings that people will miss anyway because time zones are a thing. At least with weekly meetings, we can prune the agenda based on who can attend.

Is this trying to solve a problem that we have? I think the current thing is working pretty well.

**Comment by mhdawson** [comment]
I'm in agreement with @Trott, keeping a weekly meeting on the calendar and cancelling when not needed seems to be working pretty well.

**Comment by MylesBorins** [comment]
based on sentiment I'm going to close this

**Comment by jasnell** [comment]
I'd much prefer the monthly schedule but ok.
