### ISSUE TITLE
Proposal: Collect questions for Q&A prior to meeting

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#82]
I'm not suggesting cutting the live Q&A but it would be good to collect questions from the community before each meeting as well. We could solicit them in the meeting Issue that gets created.

**Comment by williamkapke** [comment]
Any more thoughts/comments on https://github.com/nodejs/TSC/issues/60?

**Comment by mhdawson** [comment]
Collecting questions in advance seems reasonable to me.

**Comment by jasnell** [comment]
We can also solicit in advance via twitter and irc. SGTM

**Comment by williamkapke** [comment]
@mikeal I'm all for soliciting questions. Consider, however, since the beginning of the year, [meeting issues have been created same-day](https://github.com/nodejs/TSC/issues?utf8=%E2%9C%93&q=is%3Aissue+meeting+in%3Atitle). It isn't a reasonable amount of time.

Also consider that a GH issue could be opened to ask a question at any time. We all know I've utilized this ;) 

As one of the few people that ask questions during meetings I can attest to how disparaging it is to have the comments part ditched and questions ignored. I don't find the tone at Q&A time very welcoming of feedback IMO. I'd rather see the live questions just go away- especially since I there isn't even an answer to [my question about questions](https://github.com/nodejs/TSC/issues/60)!

/cc @nodejs/inclusivity as it relates to the [first item on their list of responsibilities](https://github.com/nodejs/inclusivity#list-of-responsibilities).

**Comment by jasnell** [comment]
Closing given that there has been no further discussion and activity on this. It is still likely something that we should do better at.
