### ISSUE TITLE
Nominating Kat Marchán to the TSC

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/TSC#83]
The TSC has long discussed this in private, and last I've heard everyone was OK with this, so I'm just going to move it forward and do the public nomination for @zkat.

In general, the current TSC is not that representative of node.js users and similar stakeholders. Here are some reasons if anyone needs them:

- While @chrisdickinson is on the TSC, he is consistently too busy to attend discussions. npm is an important stakeholder in the community and in core. Representation from them is very valuable in many of our discussions.
- Being on the CLI team for npm, Kat has close communication both with a large amount of users, and in core itself, given that we bundle the npm client.
- The current TSC is only minorly representative of the node.js user-base globally. We have some representation of timezones and languages, but little else. Kat brings much-needed new background perspective.

The recommendation is that we invite her as an observer until the board meeting talks about our goals, as described in multiple issues but especially in https://github.com/nodejs/TSC/pull/77, and take the formal vote to become a voting member afterwards.

**Comment by Fishrock123** [comment]
@zkat

**Comment by thefourtheye** [comment]
+1 to @zkat :) Also,

> The current CTC is only minorly representative of the node.js user-base globally.

Did you mean `The current TSC is only a minor representative...`?

**Comment by Fishrock123** [comment]
@thefourtheye No, I mean that it's current composition is not all that reflective of the global community.

**Comment by Trott** [comment]
@Fishrock123 I think @thefourtheye was trying to say "you wrote `CTC` but probably meant `TSC`".

**Comment by rvagg** [comment]
As I mentioned in the last meeting I wouldn't mind putting a pause on expansion plans for the TSC untl we sort out questions of mission and scope for the Foundation.

At the moment it's not clear that we have a goal to be "representative of node.js users and similar stakeholders" as separate to our existing open governance processes that reward contribution with a seat at the table. Having the TSC membership evolve too far outside of that existing process we have in core has the potential to create problems between the two groups _unless_ the scope of the TSC is significantly expanded. Since we haven't resolved the question of scope I'm hesitant to support expansion that's not tied to the existing processes we have for Node.

Consider this: if we end up rolling back on some of the expansion we've taken steps toward and turn the TSC into a body that provides an administrative function for the core project and surrounding working groups, in what direction should the TSC expand? In @zkat's case, she's already a Collaborator so it's _probably_ not going to pose any problems for our existing governance model, but what about beyond the Collaborator group? If the CTC is answerable to the TSC in some way, does it undermine the governance structure which we have put so much effort into protecting and has been explicitly endorsed by members of the Foundation?

Food for thought, but as I said, I'd prefer holding off on expansion for now until we've got more clarity on mission and scope.

**Comment by Fishrock123** [comment]
Hmmm, my understanding was that we were moving to add her as an observer for now regardless.

**Comment by Fishrock123** [comment]
removing from agenda for the mean time then

**Comment by jasnell** [comment]
Closing given that @zkat has withdrawn from the Inclusivity WG and has publicly stated on Twitter that she does not intend to participate further in foundation efforts (https://twitter.com/maybekatz/status/759529456138539008)
