### ISSUE TITLE
More visibility for TSC on performance issues

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#940]
I'm wondering if we need a better way to keep the TSC up to date on performance issues. For example:

https://github.com/nodejs/node/issues/34322

Creating this issue, adding to agenda for discussion.

**Comment by mcollina** [comment]
I'm highly aware of that issue and I do not really have a solution for it :/. Happy to discuss the story behind that.

(Note that the severe degradation was present in node-v8 last I checked).

**Comment by Trott** [comment]
> I'm wondering if we need a better way to keep the TSC up to date on performance issues.

What do you hope greater TSC awareness will achieve?

**Comment by mhdawson** [comment]
@Trott I'm thinking that the TSC  should be aware of significant performance regressions affecting the LTS releases, and any which are known in advance of cutting a new Major release.

I understand that people can go search for them, but it seems to like something we should be more proactive about.

**Comment by mmarchini** [comment]
I'm not sure granular awareness is relevant unless we have a plan to act on it (revert offending commits, block releases, etc.). The problem is most of the recent performance issues I've seen reported on our issue tracker are V8 related and not Node.js related, which makes it harder for us to act on it.

Preventing and fixing regressions is definitely important, but I'm wondering if a working group/task force/strategic initiative would make more sense than making the whole TSC aware. If just awareness is wanted, we can list all issues with `performance` label on meetings (and maybe discuss recent ones), but that feels a bit out of scope for us.

**Comment by mhdawson** [comment]
@mmarchini I agree that listing all of the issues does not make sense, I was more thinking that the TSC should be aware of significant regressions which are not going to be fixed quickly, even if they are in v8.  Still not sure what the best way to address is though.

**Comment by mhdawson** [comment]
Going to close this until I come up with more concrete suggestions.
